version: 2
updates:
- package-ecosystem: gradle
  directories:
  - "/"
  - "/java-8"
  schedule:
    interval: weekly
    time: "09:00" # 9am UTC
  open-pull-requests-limit: 10
  groups:
    kiota-dependencies:
      patterns:
        - "*kiota*"
    junit-dependencies:
      patterns:
        - "*junit*"
    open-telemetry:
      patterns:
        - "*opentelemetry*"
    
- package-ecosystem: gradle
  directory: "/android"
  schedule:
    interval: weekly
    time: "10:00" # 10am UTC. Scheduled after core java dependencies to prevent duplicate PRs
  open-pull-requests-limit: 10
  groups:
    kiota-dependencies:
      patterns:
        - "*kiota*"
    junit-dependencies:
      patterns:
        - "*junit*"
    open-telemetry:
      patterns:
        - "*opentelemetry*"
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  groups:
    kiota-dependencies:
      patterns:
        - "*kiota*"
    junit-dependencies:
      patterns:
        - "*junit*"
    open-telemetry:
      patterns:
        - "*opentelemetry*"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  groups:
    github-actions-dependencies:
      patterns:
        - "actions/*"

