// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests.extensions;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.concurrency.ICallback;
import com.microsoft.graph.models.extensions.AndroidManagedStoreAccountEnterpriseSettings;
import java.util.Arrays;
import java.util.EnumSet;
import com.microsoft.graph.core.IBaseClient;
import com.microsoft.graph.http.BaseRequestBuilder;
import com.microsoft.graph.options.Option;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Android Managed Store Account Enterprise Settings Request Builder.
 */
public class AndroidManagedStoreAccountEnterpriseSettingsRequestBuilder extends BaseRequestBuilder implements IAndroidManagedStoreAccountEnterpriseSettingsRequestBuilder {

    /**
     * The request builder for the AndroidManagedStoreAccountEnterpriseSettings
     *
     * @param requestUrl     the request URL
     * @param client         the service client
     * @param requestOptions the options for this request
     */
    public AndroidManagedStoreAccountEnterpriseSettingsRequestBuilder(final String requestUrl, final IBaseClient client, final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        super(requestUrl, client, requestOptions);
    }

    /**
     * Creates the request
     *
     * @return the IAndroidManagedStoreAccountEnterpriseSettingsRequest instance
     */
    public IAndroidManagedStoreAccountEnterpriseSettingsRequest buildRequest() {
        return buildRequest(getOptions());
    }

    /**
     * Creates the request with specific requestOptions instead of the existing requestOptions
     *
     * @param requestOptions the options for this request
     * @return the IAndroidManagedStoreAccountEnterpriseSettingsRequest instance
     */
    public IAndroidManagedStoreAccountEnterpriseSettingsRequest buildRequest(final java.util.List<? extends Option> requestOptions) {
        return new com.microsoft.graph.requests.extensions.AndroidManagedStoreAccountEnterpriseSettingsRequest(getRequestUrl(), getClient(), requestOptions);
    }



    public IAndroidManagedStoreAccountEnterpriseSettingsApproveAppsRequestBuilder approveApps(final java.util.List<String> packageIds, final Boolean approveAllPermissions) {
        return new AndroidManagedStoreAccountEnterpriseSettingsApproveAppsRequestBuilder(getRequestUrlWithAdditionalSegment("microsoft.graph.approveApps"), getClient(), null, packageIds, approveAllPermissions);
    }

    public IAndroidManagedStoreAccountEnterpriseSettingsRequestSignupUrlRequestBuilder requestSignupUrl(final String hostName) {
        return new AndroidManagedStoreAccountEnterpriseSettingsRequestSignupUrlRequestBuilder(getRequestUrlWithAdditionalSegment("microsoft.graph.requestSignupUrl"), getClient(), null, hostName);
    }

    public IAndroidManagedStoreAccountEnterpriseSettingsCompleteSignupRequestBuilder completeSignup(final String enterpriseToken) {
        return new AndroidManagedStoreAccountEnterpriseSettingsCompleteSignupRequestBuilder(getRequestUrlWithAdditionalSegment("microsoft.graph.completeSignup"), getClient(), null, enterpriseToken);
    }

    public IAndroidManagedStoreAccountEnterpriseSettingsSyncAppsRequestBuilder syncApps() {
        return new AndroidManagedStoreAccountEnterpriseSettingsSyncAppsRequestBuilder(getRequestUrlWithAdditionalSegment("microsoft.graph.syncApps"), getClient(), null);
    }

    public IAndroidManagedStoreAccountEnterpriseSettingsUnbindRequestBuilder unbind() {
        return new AndroidManagedStoreAccountEnterpriseSettingsUnbindRequestBuilder(getRequestUrlWithAdditionalSegment("microsoft.graph.unbind"), getClient(), null);
    }

    public IAndroidManagedStoreAccountEnterpriseSettingsCreateGooglePlayWebTokenRequestBuilder createGooglePlayWebToken(final String parentUri) {
        return new AndroidManagedStoreAccountEnterpriseSettingsCreateGooglePlayWebTokenRequestBuilder(getRequestUrlWithAdditionalSegment("microsoft.graph.createGooglePlayWebToken"), getClient(), null, parentUri);
    }

    public IAndroidManagedStoreAccountEnterpriseSettingsSetAndroidDeviceOwnerFullyManagedEnrollmentStateRequestBuilder setAndroidDeviceOwnerFullyManagedEnrollmentState(final Boolean enabled) {
        return new AndroidManagedStoreAccountEnterpriseSettingsSetAndroidDeviceOwnerFullyManagedEnrollmentStateRequestBuilder(getRequestUrlWithAdditionalSegment("microsoft.graph.setAndroidDeviceOwnerFullyManagedEnrollmentState"), getClient(), null, enabled);
    }
}
