// Template Source: BaseEntityRequest.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests.extensions;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.concurrency.ICallback;
import com.microsoft.graph.models.extensions.BookingBusiness;
import com.microsoft.graph.requests.extensions.BookingAppointmentCollectionRequestBuilder;
import com.microsoft.graph.requests.extensions.BookingAppointmentRequestBuilder;
import com.microsoft.graph.requests.extensions.BookingCustomerCollectionRequestBuilder;
import com.microsoft.graph.requests.extensions.BookingCustomerRequestBuilder;
import com.microsoft.graph.requests.extensions.BookingServiceCollectionRequestBuilder;
import com.microsoft.graph.requests.extensions.BookingServiceRequestBuilder;
import com.microsoft.graph.requests.extensions.BookingStaffMemberCollectionRequestBuilder;
import com.microsoft.graph.requests.extensions.BookingStaffMemberRequestBuilder;
import java.util.Arrays;
import java.util.EnumSet;
import javax.annotation.Nullable;
import javax.annotation.Nonnull;
import com.microsoft.graph.core.IBaseClient;
import com.microsoft.graph.http.BaseRequest;
import com.microsoft.graph.http.HttpMethod;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Booking Business Request.
 */
public class BookingBusinessRequest extends BaseRequest<BookingBusiness> {
	
    /**
     * The request for the BookingBusiness
     *
     * @param requestUrl     the request URL
     * @param client         the service client
     * @param requestOptions the options for this request
     */
    public BookingBusinessRequest(@Nonnull final String requestUrl, @Nonnull final IBaseClient client, @Nullable final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        super(requestUrl, client, requestOptions, BookingBusiness.class);
    }

    /**
     * Gets the BookingBusiness from the service
     *
     * @param callback the callback to be called after success or failure
     */
    public void get(@Nonnull final ICallback<? super BookingBusiness> callback) {
        send(HttpMethod.GET, callback, null);
    }

    /**
     * Gets the BookingBusiness from the service
     *
     * @return the BookingBusiness from the request
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public BookingBusiness get() throws ClientException {
       return send(HttpMethod.GET, null);
    }

    /**
     * Delete this item from the service
     *
     * @param callback the callback when the deletion action has completed
     */
    public void delete(@Nonnull final ICallback<? super BookingBusiness> callback) {
        send(HttpMethod.DELETE, callback, null);
    }

    /**
     * Delete this item from the service
     *
     * @throws ClientException if there was an exception during the delete operation
     */
    public void delete() throws ClientException {
        send(HttpMethod.DELETE, null);
    }

    /**
     * Patches this BookingBusiness with a source
     *
     * @param sourceBookingBusiness the source object with updates
     * @param callback the callback to be called after success or failure
     */
    public void patch(@Nonnull final BookingBusiness sourceBookingBusiness, @Nonnull final ICallback<? super BookingBusiness> callback) {
        send(HttpMethod.PATCH, callback, sourceBookingBusiness);
    }

    /**
     * Patches this BookingBusiness with a source
     *
     * @param sourceBookingBusiness the source object with updates
     * @return the updated BookingBusiness
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public BookingBusiness patch(@Nonnull final BookingBusiness sourceBookingBusiness) throws ClientException {
        return send(HttpMethod.PATCH, sourceBookingBusiness);
    }

    /**
     * Creates a BookingBusiness with a new object
     *
     * @param newBookingBusiness the new object to create
     * @param callback the callback to be called after success or failure
     */
    public void post(@Nonnull final BookingBusiness newBookingBusiness, @Nonnull final ICallback<? super BookingBusiness> callback) {
        send(HttpMethod.POST, callback, newBookingBusiness);
    }

    /**
     * Creates a BookingBusiness with a new object
     *
     * @param newBookingBusiness the new object to create
     * @return the created BookingBusiness
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public BookingBusiness post(@Nonnull final BookingBusiness newBookingBusiness) throws ClientException {
        return send(HttpMethod.POST, newBookingBusiness);
    }

    /**
     * Creates a BookingBusiness with a new object
     *
     * @param newBookingBusiness the object to create/update
     * @param callback the callback to be called after success or failure
     */
    public void put(@Nonnull final BookingBusiness newBookingBusiness, @Nonnull final ICallback<? super BookingBusiness> callback) {
        send(HttpMethod.PUT, callback, newBookingBusiness);
    }

    /**
     * Creates a BookingBusiness with a new object
     *
     * @param newBookingBusiness the object to create/update
     * @return the created BookingBusiness
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public BookingBusiness put(@Nonnull final BookingBusiness newBookingBusiness) throws ClientException {
        return send(HttpMethod.PUT, newBookingBusiness);
    }

    /**
     * Sets the select clause for the request
     *
     * @param value the select clause
     * @return the updated request
     */
     @Nonnull
     public BookingBusinessRequest select(@Nonnull final String value) {
         addSelectOption(value);
         return this;
     }

    /**
     * Sets the expand clause for the request
     *
     * @param value the expand clause
     * @return the updated request
     */
     @Nonnull
     public BookingBusinessRequest expand(@Nonnull final String value) {
         addExpandOption(value);
         return this;
     }

}

