// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests.extensions;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.concurrency.ICallback;
import com.microsoft.graph.models.extensions.BusinessFlowTemplate;
import java.util.Arrays;
import java.util.EnumSet;
import com.microsoft.graph.core.IBaseClient;
import com.microsoft.graph.http.BaseRequest;
import com.microsoft.graph.http.HttpMethod;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Business Flow Template Request.
 */
public class BusinessFlowTemplateRequest extends BaseRequest implements IBusinessFlowTemplateRequest {
	
    /**
     * The request for the BusinessFlowTemplate
     *
     * @param requestUrl     the request URL
     * @param client         the service client
     * @param requestOptions the options for this request
     */
    public BusinessFlowTemplateRequest(final String requestUrl, final IBaseClient client, final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        super(requestUrl, client, requestOptions, BusinessFlowTemplate.class);
    }

    /**
     * Gets the BusinessFlowTemplate from the service
     *
     * @param callback the callback to be called after success or failure
     */
    public void get(final ICallback<? super BusinessFlowTemplate> callback) {
        send(HttpMethod.GET, callback, null);
    }

    /**
     * Gets the BusinessFlowTemplate from the service
     *
     * @return the BusinessFlowTemplate from the request
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    public BusinessFlowTemplate get() throws ClientException {
       return send(HttpMethod.GET, null);
    }

    /**
     * Delete this item from the service
     *
     * @param callback the callback when the deletion action has completed
     */
    public void delete(final ICallback<? super BusinessFlowTemplate> callback) {
        send(HttpMethod.DELETE, callback, null);
    }

    /**
     * Delete this item from the service
     *
     * @throws ClientException if there was an exception during the delete operation
     */
    public void delete() throws ClientException {
        send(HttpMethod.DELETE, null);
    }

    /**
     * Patches this BusinessFlowTemplate with a source
     *
     * @param sourceBusinessFlowTemplate the source object with updates
     * @param callback the callback to be called after success or failure
     */
    public void patch(final BusinessFlowTemplate sourceBusinessFlowTemplate, final ICallback<? super BusinessFlowTemplate> callback) {
        send(HttpMethod.PATCH, callback, sourceBusinessFlowTemplate);
    }

    /**
     * Patches this BusinessFlowTemplate with a source
     *
     * @param sourceBusinessFlowTemplate the source object with updates
     * @return the updated BusinessFlowTemplate
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    public BusinessFlowTemplate patch(final BusinessFlowTemplate sourceBusinessFlowTemplate) throws ClientException {
        return send(HttpMethod.PATCH, sourceBusinessFlowTemplate);
    }

    /**
     * Creates a BusinessFlowTemplate with a new object
     *
     * @param newBusinessFlowTemplate the new object to create
     * @param callback the callback to be called after success or failure
     */
    public void post(final BusinessFlowTemplate newBusinessFlowTemplate, final ICallback<? super BusinessFlowTemplate> callback) {
        send(HttpMethod.POST, callback, newBusinessFlowTemplate);
    }

    /**
     * Creates a BusinessFlowTemplate with a new object
     *
     * @param newBusinessFlowTemplate the new object to create
     * @return the created BusinessFlowTemplate
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    public BusinessFlowTemplate post(final BusinessFlowTemplate newBusinessFlowTemplate) throws ClientException {
        return send(HttpMethod.POST, newBusinessFlowTemplate);
    }

    /**
     * Creates a BusinessFlowTemplate with a new object
     *
     * @param newBusinessFlowTemplate the object to create/update
     * @param callback the callback to be called after success or failure
     */
    public void put(final BusinessFlowTemplate newBusinessFlowTemplate, final ICallback<? super BusinessFlowTemplate> callback) {
        send(HttpMethod.PUT, callback, newBusinessFlowTemplate);
    }

    /**
     * Creates a BusinessFlowTemplate with a new object
     *
     * @param newBusinessFlowTemplate the object to create/update
     * @return the created BusinessFlowTemplate
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    public BusinessFlowTemplate put(final BusinessFlowTemplate newBusinessFlowTemplate) throws ClientException {
        return send(HttpMethod.PUT, newBusinessFlowTemplate);
    }

    /**
     * Sets the select clause for the request
     *
     * @param value the select clause
     * @return the updated request
     */
     public IBusinessFlowTemplateRequest select(final String value) {
         getQueryOptions().add(new com.microsoft.graph.options.QueryOption("$select", value));
         return (BusinessFlowTemplateRequest)this;
     }

    /**
     * Sets the expand clause for the request
     *
     * @param value the expand clause
     * @return the updated request
     */
     public IBusinessFlowTemplateRequest expand(final String value) {
         getQueryOptions().add(new com.microsoft.graph.options.QueryOption("$expand", value));
         return (BusinessFlowTemplateRequest)this;
     }

}

