// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests.extensions;
import com.microsoft.graph.requests.extensions.IDepOnboardingSettingRequest;
import com.microsoft.graph.requests.extensions.DepOnboardingSettingRequest;
import com.microsoft.graph.requests.extensions.IDepIOSEnrollmentProfileWithReferenceRequestBuilder;
import com.microsoft.graph.requests.extensions.DepIOSEnrollmentProfileWithReferenceRequestBuilder;
import com.microsoft.graph.requests.extensions.IDepMacOSEnrollmentProfileWithReferenceRequestBuilder;
import com.microsoft.graph.requests.extensions.DepMacOSEnrollmentProfileWithReferenceRequestBuilder;
import com.microsoft.graph.requests.extensions.IEnrollmentProfileCollectionRequestBuilder;
import com.microsoft.graph.requests.extensions.EnrollmentProfileCollectionRequestBuilder;
import com.microsoft.graph.requests.extensions.IEnrollmentProfileRequestBuilder;
import com.microsoft.graph.requests.extensions.EnrollmentProfileRequestBuilder;
import com.microsoft.graph.requests.extensions.IImportedAppleDeviceIdentityCollectionRequestBuilder;
import com.microsoft.graph.requests.extensions.ImportedAppleDeviceIdentityCollectionRequestBuilder;
import com.microsoft.graph.requests.extensions.IImportedAppleDeviceIdentityRequestBuilder;
import com.microsoft.graph.requests.extensions.ImportedAppleDeviceIdentityRequestBuilder;
import com.microsoft.graph.requests.extensions.IDepOnboardingSettingGenerateEncryptionPublicKeyRequestBuilder;
import com.microsoft.graph.requests.extensions.DepOnboardingSettingGenerateEncryptionPublicKeyRequestBuilder;
import com.microsoft.graph.requests.extensions.IDepOnboardingSettingUploadDepTokenRequestBuilder;
import com.microsoft.graph.requests.extensions.DepOnboardingSettingUploadDepTokenRequestBuilder;
import com.microsoft.graph.requests.extensions.IDepOnboardingSettingSyncWithAppleDeviceEnrollmentProgramRequestBuilder;
import com.microsoft.graph.requests.extensions.DepOnboardingSettingSyncWithAppleDeviceEnrollmentProgramRequestBuilder;
import com.microsoft.graph.requests.extensions.IDepOnboardingSettingShareForSchoolDataSyncServiceRequestBuilder;
import com.microsoft.graph.requests.extensions.DepOnboardingSettingShareForSchoolDataSyncServiceRequestBuilder;
import com.microsoft.graph.requests.extensions.IDepOnboardingSettingUnshareForSchoolDataSyncServiceRequestBuilder;
import com.microsoft.graph.requests.extensions.DepOnboardingSettingUnshareForSchoolDataSyncServiceRequestBuilder;
import com.microsoft.graph.requests.extensions.IDepOnboardingSettingGetEncryptionPublicKeyRequestBuilder;
import com.microsoft.graph.requests.extensions.DepOnboardingSettingGetEncryptionPublicKeyRequestBuilder;

import com.microsoft.graph.core.IBaseClient;
import com.microsoft.graph.http.BaseRequestBuilder;
import com.microsoft.graph.options.Option;
import java.util.EnumSet;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Dep Onboarding Setting Request Builder.
 */
public class DepOnboardingSettingRequestBuilder extends BaseRequestBuilder implements IDepOnboardingSettingRequestBuilder {

    /**
     * The request builder for the DepOnboardingSetting
     *
     * @param requestUrl     the request URL
     * @param client         the service client
     * @param requestOptions the options for this request
     */
    public DepOnboardingSettingRequestBuilder(final String requestUrl, final IBaseClient client, final java.util.List<? extends Option> requestOptions) {
        super(requestUrl, client, requestOptions);
    }

    /**
     * Creates the request
     *
     * @return the IDepOnboardingSettingRequest instance
     */
    public IDepOnboardingSettingRequest buildRequest() {
        return buildRequest(getOptions());
    }

    /**
     * Creates the request with specific requestOptions instead of the existing requestOptions
     *
     * @param requestOptions the options for this request
     * @return the IDepOnboardingSettingRequest instance
     */
    public IDepOnboardingSettingRequest buildRequest(final java.util.List<? extends Option> requestOptions) {
        return new DepOnboardingSettingRequest(getRequestUrl(), getClient(), requestOptions);
    }



    /**
     * Gets the request builder for DepIOSEnrollmentProfile
     *
     * @return the IDepIOSEnrollmentProfileWithReferenceRequestBuilder instance
     */
    public IDepIOSEnrollmentProfileWithReferenceRequestBuilder defaultIosEnrollmentProfile() {
        return new DepIOSEnrollmentProfileWithReferenceRequestBuilder(getRequestUrlWithAdditionalSegment("defaultIosEnrollmentProfile"), getClient(), null);
    }

    /**
     * Gets the request builder for DepMacOSEnrollmentProfile
     *
     * @return the IDepMacOSEnrollmentProfileWithReferenceRequestBuilder instance
     */
    public IDepMacOSEnrollmentProfileWithReferenceRequestBuilder defaultMacOsEnrollmentProfile() {
        return new DepMacOSEnrollmentProfileWithReferenceRequestBuilder(getRequestUrlWithAdditionalSegment("defaultMacOsEnrollmentProfile"), getClient(), null);
    }
    public IEnrollmentProfileCollectionRequestBuilder enrollmentProfiles() {
        return new EnrollmentProfileCollectionRequestBuilder(getRequestUrlWithAdditionalSegment("enrollmentProfiles"), getClient(), null);
    }

    public IEnrollmentProfileRequestBuilder enrollmentProfiles(final String id) {
        return new EnrollmentProfileRequestBuilder(getRequestUrlWithAdditionalSegment("enrollmentProfiles") + "/" + id, getClient(), null);
    }
    public IImportedAppleDeviceIdentityCollectionRequestBuilder importedAppleDeviceIdentities() {
        return new ImportedAppleDeviceIdentityCollectionRequestBuilder(getRequestUrlWithAdditionalSegment("importedAppleDeviceIdentities"), getClient(), null);
    }

    public IImportedAppleDeviceIdentityRequestBuilder importedAppleDeviceIdentities(final String id) {
        return new ImportedAppleDeviceIdentityRequestBuilder(getRequestUrlWithAdditionalSegment("importedAppleDeviceIdentities") + "/" + id, getClient(), null);
    }

    public IDepOnboardingSettingGenerateEncryptionPublicKeyRequestBuilder generateEncryptionPublicKey() {
        return new DepOnboardingSettingGenerateEncryptionPublicKeyRequestBuilder(getRequestUrlWithAdditionalSegment("microsoft.graph.generateEncryptionPublicKey"), getClient(), null);
    }

    public IDepOnboardingSettingUploadDepTokenRequestBuilder uploadDepToken(final String appleId, final String depToken) {
        return new DepOnboardingSettingUploadDepTokenRequestBuilder(getRequestUrlWithAdditionalSegment("microsoft.graph.uploadDepToken"), getClient(), null, appleId, depToken);
    }

    public IDepOnboardingSettingSyncWithAppleDeviceEnrollmentProgramRequestBuilder syncWithAppleDeviceEnrollmentProgram() {
        return new DepOnboardingSettingSyncWithAppleDeviceEnrollmentProgramRequestBuilder(getRequestUrlWithAdditionalSegment("microsoft.graph.syncWithAppleDeviceEnrollmentProgram"), getClient(), null);
    }

    public IDepOnboardingSettingShareForSchoolDataSyncServiceRequestBuilder shareForSchoolDataSyncService() {
        return new DepOnboardingSettingShareForSchoolDataSyncServiceRequestBuilder(getRequestUrlWithAdditionalSegment("microsoft.graph.shareForSchoolDataSyncService"), getClient(), null);
    }

    public IDepOnboardingSettingUnshareForSchoolDataSyncServiceRequestBuilder unshareForSchoolDataSyncService() {
        return new DepOnboardingSettingUnshareForSchoolDataSyncServiceRequestBuilder(getRequestUrlWithAdditionalSegment("microsoft.graph.unshareForSchoolDataSyncService"), getClient(), null);
    }

    public IDepOnboardingSettingGetEncryptionPublicKeyRequestBuilder getEncryptionPublicKey() {
        return new DepOnboardingSettingGetEncryptionPublicKeyRequestBuilder(getRequestUrlWithAdditionalSegment("microsoft.graph.getEncryptionPublicKey"), getClient(), null);
    }
}

