// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests.extensions;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.concurrency.ICallback;
import com.microsoft.graph.models.extensions.DeviceManagement;

import java.util.Arrays;
import java.util.EnumSet;

import com.microsoft.graph.requests.extensions.IDeviceAndAppManagementAssignmentFilterCollectionRequestBuilder;
import com.microsoft.graph.requests.extensions.IDeviceAndAppManagementAssignmentFilterRequestBuilder;
import com.microsoft.graph.requests.extensions.IDeviceAndAppManagementAssignmentFilterCollectionRequest;
import com.microsoft.graph.models.extensions.DeviceAndAppManagementAssignmentFilter;
import com.microsoft.graph.options.Option;
import com.microsoft.graph.http.BaseRequestBuilder;
import com.microsoft.graph.core.IBaseClient;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Device And App Management Assignment Filter Collection Request Builder.
 */
public class DeviceAndAppManagementAssignmentFilterCollectionRequestBuilder extends BaseRequestBuilder implements IDeviceAndAppManagementAssignmentFilterCollectionRequestBuilder {

    /**
     * The request builder for this collection of DeviceManagement
     *
     * @param requestUrl     the request URL
     * @param client         the service client
     * @param requestOptions the options for this request
     */
    public DeviceAndAppManagementAssignmentFilterCollectionRequestBuilder(final String requestUrl, final IBaseClient client, final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        super(requestUrl, client, requestOptions);
    }

    public IDeviceAndAppManagementAssignmentFilterCollectionRequest buildRequest() {
        return buildRequest(getOptions());
    }

    public IDeviceAndAppManagementAssignmentFilterCollectionRequest buildRequest(final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        return new DeviceAndAppManagementAssignmentFilterCollectionRequest(getRequestUrl(), getClient(), requestOptions);
    }

    public IDeviceAndAppManagementAssignmentFilterRequestBuilder byId(final String id) {
        return new DeviceAndAppManagementAssignmentFilterRequestBuilder(getRequestUrlWithAdditionalSegment(id), getClient(), getOptions());
    }


}
