// Template Source: BaseEntityRequest.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests.extensions;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.concurrency.ICallback;
import com.microsoft.graph.models.extensions.DeviceManagementCollectionSettingInstance;
import com.microsoft.graph.requests.extensions.DeviceManagementSettingInstanceCollectionRequestBuilder;
import com.microsoft.graph.requests.extensions.DeviceManagementSettingInstanceRequestBuilder;
import java.util.Arrays;
import java.util.EnumSet;
import javax.annotation.Nullable;
import javax.annotation.Nonnull;
import com.microsoft.graph.core.IBaseClient;
import com.microsoft.graph.http.BaseRequest;
import com.microsoft.graph.http.HttpMethod;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Device Management Collection Setting Instance Request.
 */
public class DeviceManagementCollectionSettingInstanceRequest extends BaseRequest<DeviceManagementCollectionSettingInstance> {
	
    /**
     * The request for the DeviceManagementCollectionSettingInstance
     *
     * @param requestUrl     the request URL
     * @param client         the service client
     * @param requestOptions the options for this request
     */
    public DeviceManagementCollectionSettingInstanceRequest(@Nonnull final String requestUrl, @Nonnull final IBaseClient client, @Nullable final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        super(requestUrl, client, requestOptions, DeviceManagementCollectionSettingInstance.class);
    }

    /**
     * Gets the DeviceManagementCollectionSettingInstance from the service
     *
     * @param callback the callback to be called after success or failure
     */
    public void get(@Nonnull final ICallback<? super DeviceManagementCollectionSettingInstance> callback) {
        send(HttpMethod.GET, callback, null);
    }

    /**
     * Gets the DeviceManagementCollectionSettingInstance from the service
     *
     * @return the DeviceManagementCollectionSettingInstance from the request
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public DeviceManagementCollectionSettingInstance get() throws ClientException {
       return send(HttpMethod.GET, null);
    }

    /**
     * Delete this item from the service
     *
     * @param callback the callback when the deletion action has completed
     */
    public void delete(@Nonnull final ICallback<? super DeviceManagementCollectionSettingInstance> callback) {
        send(HttpMethod.DELETE, callback, null);
    }

    /**
     * Delete this item from the service
     *
     * @throws ClientException if there was an exception during the delete operation
     */
    public void delete() throws ClientException {
        send(HttpMethod.DELETE, null);
    }

    /**
     * Patches this DeviceManagementCollectionSettingInstance with a source
     *
     * @param sourceDeviceManagementCollectionSettingInstance the source object with updates
     * @param callback the callback to be called after success or failure
     */
    public void patch(@Nonnull final DeviceManagementCollectionSettingInstance sourceDeviceManagementCollectionSettingInstance, @Nonnull final ICallback<? super DeviceManagementCollectionSettingInstance> callback) {
        send(HttpMethod.PATCH, callback, sourceDeviceManagementCollectionSettingInstance);
    }

    /**
     * Patches this DeviceManagementCollectionSettingInstance with a source
     *
     * @param sourceDeviceManagementCollectionSettingInstance the source object with updates
     * @return the updated DeviceManagementCollectionSettingInstance
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public DeviceManagementCollectionSettingInstance patch(@Nonnull final DeviceManagementCollectionSettingInstance sourceDeviceManagementCollectionSettingInstance) throws ClientException {
        return send(HttpMethod.PATCH, sourceDeviceManagementCollectionSettingInstance);
    }

    /**
     * Creates a DeviceManagementCollectionSettingInstance with a new object
     *
     * @param newDeviceManagementCollectionSettingInstance the new object to create
     * @param callback the callback to be called after success or failure
     */
    public void post(@Nonnull final DeviceManagementCollectionSettingInstance newDeviceManagementCollectionSettingInstance, @Nonnull final ICallback<? super DeviceManagementCollectionSettingInstance> callback) {
        send(HttpMethod.POST, callback, newDeviceManagementCollectionSettingInstance);
    }

    /**
     * Creates a DeviceManagementCollectionSettingInstance with a new object
     *
     * @param newDeviceManagementCollectionSettingInstance the new object to create
     * @return the created DeviceManagementCollectionSettingInstance
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public DeviceManagementCollectionSettingInstance post(@Nonnull final DeviceManagementCollectionSettingInstance newDeviceManagementCollectionSettingInstance) throws ClientException {
        return send(HttpMethod.POST, newDeviceManagementCollectionSettingInstance);
    }

    /**
     * Creates a DeviceManagementCollectionSettingInstance with a new object
     *
     * @param newDeviceManagementCollectionSettingInstance the object to create/update
     * @param callback the callback to be called after success or failure
     */
    public void put(@Nonnull final DeviceManagementCollectionSettingInstance newDeviceManagementCollectionSettingInstance, @Nonnull final ICallback<? super DeviceManagementCollectionSettingInstance> callback) {
        send(HttpMethod.PUT, callback, newDeviceManagementCollectionSettingInstance);
    }

    /**
     * Creates a DeviceManagementCollectionSettingInstance with a new object
     *
     * @param newDeviceManagementCollectionSettingInstance the object to create/update
     * @return the created DeviceManagementCollectionSettingInstance
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public DeviceManagementCollectionSettingInstance put(@Nonnull final DeviceManagementCollectionSettingInstance newDeviceManagementCollectionSettingInstance) throws ClientException {
        return send(HttpMethod.PUT, newDeviceManagementCollectionSettingInstance);
    }

    /**
     * Sets the select clause for the request
     *
     * @param value the select clause
     * @return the updated request
     */
     @Nonnull
     public DeviceManagementCollectionSettingInstanceRequest select(@Nonnull final String value) {
         addSelectOption(value);
         return this;
     }

    /**
     * Sets the expand clause for the request
     *
     * @param value the expand clause
     * @return the updated request
     */
     @Nonnull
     public DeviceManagementCollectionSettingInstanceRequest expand(@Nonnull final String value) {
         addExpandOption(value);
         return this;
     }

}

