// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests.extensions;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.concurrency.ICallback;

import java.util.Arrays;
import java.util.EnumSet;

import com.microsoft.graph.requests.extensions.IDeviceConfigurationGetTargetedUsersAndDevicesCollectionRequestBuilder;
import com.microsoft.graph.requests.extensions.IDeviceConfigurationGetTargetedUsersAndDevicesCollectionRequest;
import com.microsoft.graph.requests.extensions.DeviceConfigurationGetTargetedUsersAndDevicesCollectionRequest;
import com.microsoft.graph.models.extensions.DeviceConfigurationTargetedUserAndDevice;
import com.microsoft.graph.options.Option;
import com.microsoft.graph.options.FunctionOption;
import com.microsoft.graph.core.IBaseClient;
import com.microsoft.graph.core.BaseActionRequestBuilder;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Device Configuration Get Targeted Users And Devices Collection Request Builder.
 */
public class DeviceConfigurationGetTargetedUsersAndDevicesCollectionRequestBuilder extends BaseActionRequestBuilder implements IDeviceConfigurationGetTargetedUsersAndDevicesCollectionRequestBuilder {

    /**
     * The request builder for this collection of DeviceConfiguration
     *
     * @param requestUrl     the request URL
     * @param client         the service client
     * @param requestOptions the options for this request
     * @param deviceConfigurationIds the deviceConfigurationIds
     */
    public DeviceConfigurationGetTargetedUsersAndDevicesCollectionRequestBuilder(final String requestUrl, final IBaseClient client, final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions, final java.util.List<String> deviceConfigurationIds) {
        super(requestUrl, client, requestOptions);
  	 if(deviceConfigurationIds!=null){
			bodyParams.put("deviceConfigurationIds", deviceConfigurationIds);
		}
      }

    public IDeviceConfigurationGetTargetedUsersAndDevicesCollectionRequest buildRequest() {
        return buildRequest(getOptions());
    }

    public IDeviceConfigurationGetTargetedUsersAndDevicesCollectionRequest buildRequest(final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        DeviceConfigurationGetTargetedUsersAndDevicesCollectionRequest request = new DeviceConfigurationGetTargetedUsersAndDevicesCollectionRequest(
                getRequestUrl(),
                getClient(),
                requestOptions
        );

        if (hasParameter("deviceConfigurationIds")) {
            request.body.deviceConfigurationIds = getParameter("deviceConfigurationIds");
        }
  
        return request;
    }
}
