// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests.extensions;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.concurrency.ICallback;
import com.microsoft.graph.models.extensions.DeviceManagementConfigurationPolicy;
import com.microsoft.graph.models.extensions.DeviceManagementConfigurationPolicyAssignment;
import com.microsoft.graph.requests.extensions.IDeviceManagementConfigurationPolicyAssignmentCollectionRequestBuilder;
import com.microsoft.graph.requests.extensions.IDeviceManagementConfigurationPolicyAssignmentRequestBuilder;
import com.microsoft.graph.requests.extensions.DeviceManagementConfigurationPolicyAssignmentCollectionRequestBuilder;
import com.microsoft.graph.requests.extensions.DeviceManagementConfigurationPolicyAssignmentRequestBuilder;
import com.microsoft.graph.requests.extensions.IDeviceManagementConfigurationSettingCollectionRequestBuilder;
import com.microsoft.graph.requests.extensions.IDeviceManagementConfigurationSettingRequestBuilder;
import com.microsoft.graph.requests.extensions.DeviceManagementConfigurationSettingCollectionRequestBuilder;
import com.microsoft.graph.requests.extensions.DeviceManagementConfigurationSettingRequestBuilder;
import java.util.Arrays;
import java.util.EnumSet;
import com.microsoft.graph.core.IBaseClient;
import com.microsoft.graph.http.BaseRequestBuilder;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Device Management Configuration Policy Request Builder.
 */
public class DeviceManagementConfigurationPolicyRequestBuilder extends BaseRequestBuilder implements IDeviceManagementConfigurationPolicyRequestBuilder {

    /**
     * The request builder for the DeviceManagementConfigurationPolicy
     *
     * @param requestUrl     the request URL
     * @param client         the service client
     * @param requestOptions the options for this request
     */
    public DeviceManagementConfigurationPolicyRequestBuilder(final String requestUrl, final IBaseClient client, final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        super(requestUrl, client, requestOptions);
    }

    /**
     * Creates the request
     *
     * @param requestOptions the options for this request
     * @return the IDeviceManagementConfigurationPolicyRequest instance
     */
    public IDeviceManagementConfigurationPolicyRequest buildRequest(final com.microsoft.graph.options.Option... requestOptions) {
        return buildRequest(getOptions(requestOptions));
    }

    /**
     * Creates the request with specific requestOptions instead of the existing requestOptions
     *
     * @param requestOptions the options for this request
     * @return the IDeviceManagementConfigurationPolicyRequest instance
     */
    public IDeviceManagementConfigurationPolicyRequest buildRequest(final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        return new com.microsoft.graph.requests.extensions.DeviceManagementConfigurationPolicyRequest(getRequestUrl(), getClient(), requestOptions);
    }


    public IDeviceManagementConfigurationPolicyAssignmentCollectionRequestBuilder assignments() {
        return new DeviceManagementConfigurationPolicyAssignmentCollectionRequestBuilder(getRequestUrlWithAdditionalSegment("assignments"), getClient(), null);
    }

    public IDeviceManagementConfigurationPolicyAssignmentRequestBuilder assignments(final String id) {
        return new DeviceManagementConfigurationPolicyAssignmentRequestBuilder(getRequestUrlWithAdditionalSegment("assignments") + "/" + id, getClient(), null);
    }
    public IDeviceManagementConfigurationSettingCollectionRequestBuilder settings() {
        return new DeviceManagementConfigurationSettingCollectionRequestBuilder(getRequestUrlWithAdditionalSegment("settings"), getClient(), null);
    }

    public IDeviceManagementConfigurationSettingRequestBuilder settings(final String id) {
        return new DeviceManagementConfigurationSettingRequestBuilder(getRequestUrlWithAdditionalSegment("settings") + "/" + id, getClient(), null);
    }

    public IDeviceManagementConfigurationPolicyAssignCollectionRequestBuilder assign(final java.util.List<DeviceManagementConfigurationPolicyAssignment> assignments) {
        return new DeviceManagementConfigurationPolicyAssignCollectionRequestBuilder(getRequestUrlWithAdditionalSegment("microsoft.graph.assign"), getClient(), null, assignments);
    }
}
