// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests.extensions;
import com.microsoft.graph.requests.extensions.IDocumentRequest;
import com.microsoft.graph.requests.extensions.IDocumentCommentCollectionRequestBuilder;
import com.microsoft.graph.requests.extensions.DocumentCommentCollectionRequestBuilder;
import com.microsoft.graph.requests.extensions.IDocumentCommentRequestBuilder;
import com.microsoft.graph.requests.extensions.DocumentCommentRequestBuilder;

import com.microsoft.graph.core.IBaseClient;
import com.microsoft.graph.http.BaseRequestBuilder;
import com.microsoft.graph.options.Option;
import java.util.EnumSet;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Document Request Builder.
 */
public class DocumentRequestBuilder extends BaseRequestBuilder implements IDocumentRequestBuilder {

    /**
     * The request builder for the Document
     *
     * @param requestUrl     the request URL
     * @param client         the service client
     * @param requestOptions the options for this request
     */
    public DocumentRequestBuilder(final String requestUrl, final IBaseClient client, final java.util.List<? extends Option> requestOptions) {
        super(requestUrl, client, requestOptions);
    }

    /**
     * Creates the request
     *
     * @return the IDocumentRequest instance
     */
    public IDocumentRequest buildRequest() {
        return buildRequest(getOptions());
    }

    /**
     * Creates the request with specific requestOptions instead of the existing requestOptions
     *
     * @param requestOptions the options for this request
     * @return the IDocumentRequest instance
     */
    public IDocumentRequest buildRequest(final java.util.List<? extends Option> requestOptions) {
        return new com.microsoft.graph.requests.extensions.DocumentRequest(getRequestUrl(), getClient(), requestOptions);
    }


    public IDocumentCommentCollectionRequestBuilder comments() {
        return new DocumentCommentCollectionRequestBuilder(getRequestUrlWithAdditionalSegment("comments"), getClient(), null);
    }

    public IDocumentCommentRequestBuilder comments(final String id) {
        return new DocumentCommentRequestBuilder(getRequestUrlWithAdditionalSegment("comments") + "/" + id, getClient(), null);
    }
}
