// Template Source: BaseEntityCollectionReferenceRequest.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests.extensions;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.concurrency.ICallback;
import com.microsoft.graph.models.extensions.GroupPolicyDefinitionFile;
import com.microsoft.graph.models.extensions.GroupPolicyDefinition;
import java.util.Arrays;
import java.util.EnumSet;
import javax.annotation.Nullable;
import javax.annotation.Nonnull;

import com.microsoft.graph.requests.extensions.GroupPolicyDefinitionWithReferenceRequest;
import com.microsoft.graph.requests.extensions.GroupPolicyDefinitionReferenceRequestBuilder;
import com.microsoft.graph.requests.extensions.GroupPolicyDefinitionWithReferenceRequestBuilder;
import com.microsoft.graph.requests.extensions.GroupPolicyDefinitionCollectionWithReferencesRequest;
import com.microsoft.graph.requests.extensions.GroupPolicyDefinitionCollectionWithReferencesRequestBuilder;
import com.microsoft.graph.models.extensions.GroupPolicyDefinition;
import com.microsoft.graph.options.QueryOption;
import com.microsoft.graph.core.IBaseClient;
import com.microsoft.graph.http.BaseCollectionWithReferencesRequest;
import com.microsoft.graph.http.BaseCollectionWithReferencesRequestBuilder;
import com.microsoft.graph.http.ReferenceRequestBody;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Group Policy Definition Collection Reference Request.
 */
public class GroupPolicyDefinitionCollectionReferenceRequest extends BaseCollectionWithReferencesRequest<GroupPolicyDefinition, GroupPolicyDefinitionWithReferenceRequest, GroupPolicyDefinitionReferenceRequestBuilder, GroupPolicyDefinitionWithReferenceRequestBuilder, GroupPolicyDefinitionCollectionResponse, GroupPolicyDefinitionCollectionWithReferencesPage, GroupPolicyDefinitionCollectionWithReferencesRequest> {

    /**
     * The request builder for this collection of GroupPolicyDefinition
     *
     * @param requestUrl     the request URL
     * @param client         the service client
     * @param requestOptions the options for this request
     */
    public GroupPolicyDefinitionCollectionReferenceRequest(@Nonnull final String requestUrl, @Nonnull final IBaseClient client, @Nullable final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        super(requestUrl, client, requestOptions, GroupPolicyDefinitionCollectionResponse.class, GroupPolicyDefinitionCollectionWithReferencesPage.class, GroupPolicyDefinitionCollectionWithReferencesRequestBuilder.class);
    }

    /**
     * Creates a new GroupPolicyDefinition
     * @param newGroupPolicyDefinition the GroupPolicyDefinition to create
     * @param callback the callback to invoke once the object has been created
     */
    public void post(@Nonnull final GroupPolicyDefinition newGroupPolicyDefinition, @Nonnull final ICallback<? super GroupPolicyDefinition> callback) {
        final String requestUrl = getBaseRequest().getRequestUrl().toString();
        final ReferenceRequestBody body = new ReferenceRequestBody(getBaseRequest().getClient().getServiceRoot() + "/deviceManagement/definitions/" + newGroupPolicyDefinition.id);
        new GroupPolicyDefinitionWithReferenceRequestBuilder(requestUrl, getBaseRequest().getClient(), /* Options */ null)
            .buildRequest(getBaseRequest().getHeaders())
            .post(newGroupPolicyDefinition, body, callback);
    }

    /**
     * Creates a new GroupPolicyDefinition
     * @param newGroupPolicyDefinition the GroupPolicyDefinition to create
     * @return the newly created object
     */
    @Nonnull
    public GroupPolicyDefinition post(@Nonnull final GroupPolicyDefinition newGroupPolicyDefinition) throws ClientException {
        final String requestUrl = getBaseRequest().getRequestUrl().toString();
        final ReferenceRequestBody body = new ReferenceRequestBody(getBaseRequest().getClient().getServiceRoot() + "/deviceManagement/definitions/" + newGroupPolicyDefinition.id);
        return new GroupPolicyDefinitionWithReferenceRequestBuilder(requestUrl,getBaseRequest().getClient(), /* Options */ null)
                .buildRequest(getBaseRequest().getHeaders())
                .post(newGroupPolicyDefinition, body);
    }
    /**
     * Sets the expand clause for the request
     *
     * @param value the expand clause
     * @return the updated request
     */
    @Nonnull
    public GroupPolicyDefinitionCollectionReferenceRequest expand(@Nonnull final String value) {
        addExpandOption(value);
        return this;
    }

    /**
     * Sets the filter clause for the request
     *
     * @param value the filter clause
     * @return the updated request
     */
    @Nonnull
    public GroupPolicyDefinitionCollectionReferenceRequest filter(@Nonnull final String value) {
        addFilterOption(value);
        return this;
    }

    /**
     * Sets the order by clause for the request
     *
     * @param value the sort clause
     * @return the updated request
     */
    @Nonnull
    public GroupPolicyDefinitionCollectionReferenceRequest orderBy(@Nonnull final String value) {
        addOrderByOption(value);
        return this;
    }

    /**
     * Sets the select clause for the request
     *
     * @param value the select clause
     * @return the updated request
     */
    @Nonnull
    public GroupPolicyDefinitionCollectionReferenceRequest select(@Nonnull final String value) {
        addSelectOption(value);
        return this;
    }

    /**
     * Sets the top value for the request
     *
     * @param value the max number of items to return
     * @return the updated request
     */
    @Nonnull
    public GroupPolicyDefinitionCollectionReferenceRequest top(final int value) {
        addTopOption(value);
        return this;
    }
    /**
     * Sets the count value for the request
     *
     * @param value whether or not to return the count of objects with the request
     * @return the updated request
     */
    @Nonnull
    public GroupPolicyDefinitionCollectionReferenceRequest count(final boolean value) {
        addCountOption(value);
        return this;
    }
    /**
     * Sets the count value to true for the request
     *
     * @return the updated request
     */
    @Nonnull
    public GroupPolicyDefinitionCollectionReferenceRequest count() {
        addCountOption(true);
        return this;
    }
}
