// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests.extensions;
import com.microsoft.graph.requests.extensions.IAndroidForWorkEnterpriseWiFiConfigurationRequest;
import com.microsoft.graph.requests.extensions.IAndroidForWorkTrustedRootCertificateWithReferenceRequestBuilder;
import com.microsoft.graph.requests.extensions.IAndroidForWorkCertificateProfileBaseWithReferenceRequestBuilder;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.options.Option;
import java.util.EnumSet;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The interface for the Android For Work Enterprise Wi Fi Configuration Request Builder.
 */
public interface IAndroidForWorkEnterpriseWiFiConfigurationRequestBuilder extends IRequestBuilder {
    /**
     * Creates the request
     *
     * @return the IAndroidForWorkEnterpriseWiFiConfigurationRequest instance
     */
    IAndroidForWorkEnterpriseWiFiConfigurationRequest buildRequest();

    /**
     * Creates the request with specific options instead of the existing options
     *
     * @param requestOptions the options for this request
     * @return the IAndroidForWorkEnterpriseWiFiConfigurationRequest instance
     */
    IAndroidForWorkEnterpriseWiFiConfigurationRequest buildRequest(final java.util.List<? extends Option> requestOptions);


    /**
     * Gets the request builder for AndroidForWorkTrustedRootCertificate
     *
     * @return the IAndroidForWorkTrustedRootCertificateWithReferenceRequestBuilder instance
     */
    IAndroidForWorkTrustedRootCertificateWithReferenceRequestBuilder rootCertificateForServerValidation();

    /**
     * Gets the request builder for AndroidForWorkCertificateProfileBase
     *
     * @return the IAndroidForWorkCertificateProfileBaseWithReferenceRequestBuilder instance
     */
    IAndroidForWorkCertificateProfileBaseWithReferenceRequestBuilder identityCertificateForClientAuthentication();

}
