// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests.extensions;
import com.microsoft.graph.requests.extensions.IDepOnboardingSettingRequest;
import com.microsoft.graph.requests.extensions.IDepIOSEnrollmentProfileWithReferenceRequestBuilder;
import com.microsoft.graph.requests.extensions.IDepMacOSEnrollmentProfileWithReferenceRequestBuilder;
import com.microsoft.graph.requests.extensions.IEnrollmentProfileCollectionRequestBuilder;
import com.microsoft.graph.requests.extensions.IEnrollmentProfileRequestBuilder;
import com.microsoft.graph.requests.extensions.IImportedAppleDeviceIdentityCollectionRequestBuilder;
import com.microsoft.graph.requests.extensions.IImportedAppleDeviceIdentityRequestBuilder;
import com.microsoft.graph.requests.extensions.IDepOnboardingSettingGenerateEncryptionPublicKeyRequestBuilder;
import com.microsoft.graph.requests.extensions.IDepOnboardingSettingUploadDepTokenRequestBuilder;
import com.microsoft.graph.requests.extensions.IDepOnboardingSettingSyncWithAppleDeviceEnrollmentProgramRequestBuilder;
import com.microsoft.graph.requests.extensions.IDepOnboardingSettingShareForSchoolDataSyncServiceRequestBuilder;
import com.microsoft.graph.requests.extensions.IDepOnboardingSettingUnshareForSchoolDataSyncServiceRequestBuilder;
import com.microsoft.graph.requests.extensions.IDepOnboardingSettingGetEncryptionPublicKeyRequestBuilder;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.options.Option;
import java.util.EnumSet;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The interface for the Dep Onboarding Setting Request Builder.
 */
public interface IDepOnboardingSettingRequestBuilder extends IRequestBuilder {
    /**
     * Creates the request
     *
     * @return the IDepOnboardingSettingRequest instance
     */
    IDepOnboardingSettingRequest buildRequest();

    /**
     * Creates the request with specific options instead of the existing options
     *
     * @param requestOptions the options for this request
     * @return the IDepOnboardingSettingRequest instance
     */
    IDepOnboardingSettingRequest buildRequest(final java.util.List<? extends Option> requestOptions);


    /**
     * Gets the request builder for DepIOSEnrollmentProfile
     *
     * @return the IDepIOSEnrollmentProfileWithReferenceRequestBuilder instance
     */
    IDepIOSEnrollmentProfileWithReferenceRequestBuilder defaultIosEnrollmentProfile();

    /**
     * Gets the request builder for DepMacOSEnrollmentProfile
     *
     * @return the IDepMacOSEnrollmentProfileWithReferenceRequestBuilder instance
     */
    IDepMacOSEnrollmentProfileWithReferenceRequestBuilder defaultMacOsEnrollmentProfile();

    IEnrollmentProfileCollectionRequestBuilder enrollmentProfiles();

    IEnrollmentProfileRequestBuilder enrollmentProfiles(final String id);

    IImportedAppleDeviceIdentityCollectionRequestBuilder importedAppleDeviceIdentities();

    IImportedAppleDeviceIdentityRequestBuilder importedAppleDeviceIdentities(final String id);
    IDepOnboardingSettingGenerateEncryptionPublicKeyRequestBuilder generateEncryptionPublicKey();
    IDepOnboardingSettingUploadDepTokenRequestBuilder uploadDepToken(final String appleId, final String depToken);
    IDepOnboardingSettingSyncWithAppleDeviceEnrollmentProgramRequestBuilder syncWithAppleDeviceEnrollmentProgram();
    IDepOnboardingSettingShareForSchoolDataSyncServiceRequestBuilder shareForSchoolDataSyncService();
    IDepOnboardingSettingUnshareForSchoolDataSyncServiceRequestBuilder unshareForSchoolDataSyncService();
    IDepOnboardingSettingGetEncryptionPublicKeyRequestBuilder getEncryptionPublicKey();

}
