// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests.extensions;
import com.microsoft.graph.requests.extensions.IDeviceManagementScriptAssignRequest;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.options.Option;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The interface for the Device Management Script Assign Request Builder.
 */
public interface IDeviceManagementScriptAssignRequestBuilder extends IRequestBuilder {

    /**
     * Creates the IDeviceManagementScriptAssignRequest
     *
     * @return the IDeviceManagementScriptAssignRequest instance
     */
    IDeviceManagementScriptAssignRequest buildRequest();

    /**
     * Creates the IDeviceManagementScriptAssignRequest with specific options instead of the existing options
     *
     * @param requestOptions the options for the request
     * @return the IDeviceManagementScriptAssignRequest instance
     */
    IDeviceManagementScriptAssignRequest buildRequest(final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions);
}
