// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests.extensions;
import com.microsoft.graph.models.extensions.ItemAddress;

import com.microsoft.graph.concurrency.ICallback;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.http.IHttpRequest;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The interface for the Item Address Request.
 */
public interface IItemAddressRequest extends IHttpRequest {

    /**
     * Gets the ItemAddress from the service
     *
     * @param callback the callback to be called after success or failure
     */
    void get(final ICallback<ItemAddress> callback);

    /**
     * Gets the ItemAddress from the service
     *
     * @return the ItemAddress from the request
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    ItemAddress get() throws ClientException;

    /**
     * Delete this item from the service
     *
     * @param callback the callback when the deletion action has completed
     */
    void delete(final ICallback<ItemAddress> callback);

    /**
     * Delete this item from the service
     *
     * @throws ClientException if there was an exception during the delete operation
     */
    void delete() throws ClientException;

    /**
     * Patches this ItemAddress with a source
     *
     * @param sourceItemAddress the source object with updates
     * @param callback the callback to be called after success or failure
     */
    void patch(final ItemAddress sourceItemAddress, final ICallback<ItemAddress> callback);

    /**
     * Patches this ItemAddress with a source
     *
     * @param sourceItemAddress the source object with updates
     * @return the updated ItemAddress
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    ItemAddress patch(final ItemAddress sourceItemAddress) throws ClientException;

    /**
     * Posts a ItemAddress with a new object
     *
     * @param newItemAddress the new object to create
     * @param callback the callback to be called after success or failure
     */
    void post(final ItemAddress newItemAddress, final ICallback<ItemAddress> callback);

    /**
     * Posts a ItemAddress with a new object
     *
     * @param newItemAddress the new object to create
     * @return the created ItemAddress
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    ItemAddress post(final ItemAddress newItemAddress) throws ClientException;

    /**
     * Posts a ItemAddress with a new object
     *
     * @param newItemAddress the object to create/update
     * @param callback the callback to be called after success or failure
     */
    void put(final ItemAddress newItemAddress, final ICallback<ItemAddress> callback);

    /**
     * Posts a ItemAddress with a new object
     *
     * @param newItemAddress the object to create/update
     * @return the created ItemAddress
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    ItemAddress put(final ItemAddress newItemAddress) throws ClientException;

    /**
     * Sets the select clause for the request
     *
     * @param value the select clause
     * @return the updated request
     */
    IItemAddressRequest select(final String value);

    /**
     * Sets the expand clause for the request
     *
     * @param value the expand clause
     * @return the updated request
     */
    IItemAddressRequest expand(final String value);

}

