// Template Source: IBaseEntityRequestBuilder.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests.extensions;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.concurrency.ICallback;
import com.microsoft.graph.models.extensions.Profile;
import com.microsoft.graph.requests.extensions.IUserAccountInformationCollectionRequestBuilder;
import com.microsoft.graph.requests.extensions.IUserAccountInformationRequestBuilder;
import com.microsoft.graph.requests.extensions.IItemAddressCollectionRequestBuilder;
import com.microsoft.graph.requests.extensions.IItemAddressRequestBuilder;
import com.microsoft.graph.requests.extensions.IPersonAnnualEventCollectionRequestBuilder;
import com.microsoft.graph.requests.extensions.IPersonAnnualEventRequestBuilder;
import com.microsoft.graph.requests.extensions.IPersonAwardCollectionRequestBuilder;
import com.microsoft.graph.requests.extensions.IPersonAwardRequestBuilder;
import com.microsoft.graph.requests.extensions.IPersonCertificationCollectionRequestBuilder;
import com.microsoft.graph.requests.extensions.IPersonCertificationRequestBuilder;
import com.microsoft.graph.requests.extensions.IEducationalActivityCollectionRequestBuilder;
import com.microsoft.graph.requests.extensions.IEducationalActivityRequestBuilder;
import com.microsoft.graph.requests.extensions.IItemEmailCollectionRequestBuilder;
import com.microsoft.graph.requests.extensions.IItemEmailRequestBuilder;
import com.microsoft.graph.requests.extensions.IPersonInterestCollectionRequestBuilder;
import com.microsoft.graph.requests.extensions.IPersonInterestRequestBuilder;
import com.microsoft.graph.requests.extensions.ILanguageProficiencyCollectionRequestBuilder;
import com.microsoft.graph.requests.extensions.ILanguageProficiencyRequestBuilder;
import com.microsoft.graph.requests.extensions.IPersonNameCollectionRequestBuilder;
import com.microsoft.graph.requests.extensions.IPersonNameRequestBuilder;
import com.microsoft.graph.requests.extensions.IPersonAnnotationCollectionRequestBuilder;
import com.microsoft.graph.requests.extensions.IPersonAnnotationRequestBuilder;
import com.microsoft.graph.requests.extensions.IItemPatentCollectionRequestBuilder;
import com.microsoft.graph.requests.extensions.IItemPatentRequestBuilder;
import com.microsoft.graph.requests.extensions.IItemPhoneCollectionRequestBuilder;
import com.microsoft.graph.requests.extensions.IItemPhoneRequestBuilder;
import com.microsoft.graph.requests.extensions.IWorkPositionCollectionRequestBuilder;
import com.microsoft.graph.requests.extensions.IWorkPositionRequestBuilder;
import com.microsoft.graph.requests.extensions.IProjectParticipationCollectionRequestBuilder;
import com.microsoft.graph.requests.extensions.IProjectParticipationRequestBuilder;
import com.microsoft.graph.requests.extensions.IItemPublicationCollectionRequestBuilder;
import com.microsoft.graph.requests.extensions.IItemPublicationRequestBuilder;
import com.microsoft.graph.requests.extensions.ISkillProficiencyCollectionRequestBuilder;
import com.microsoft.graph.requests.extensions.ISkillProficiencyRequestBuilder;
import com.microsoft.graph.requests.extensions.IWebAccountCollectionRequestBuilder;
import com.microsoft.graph.requests.extensions.IWebAccountRequestBuilder;
import com.microsoft.graph.requests.extensions.IPersonWebsiteCollectionRequestBuilder;
import com.microsoft.graph.requests.extensions.IPersonWebsiteRequestBuilder;
import java.util.Arrays;
import java.util.EnumSet;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The interface for the Profile Request Builder.
 */
public interface IProfileRequestBuilder extends IRequestBuilder {
    /**
     * Creates the request
     *
     * @param requestOptions the options for this request
     * @return the IProfileRequest instance
     */
    IProfileRequest buildRequest(final com.microsoft.graph.options.Option... requestOptions);

    /**
     * Creates the request with specific options instead of the existing options
     *
     * @param requestOptions the options for this request
     * @return the IProfileRequest instance
     */
    IProfileRequest buildRequest(final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions);


    IUserAccountInformationCollectionRequestBuilder account();

    IUserAccountInformationRequestBuilder account(final String id);

    IItemAddressCollectionRequestBuilder addresses();

    IItemAddressRequestBuilder addresses(final String id);

    IPersonAnnualEventCollectionRequestBuilder anniversaries();

    IPersonAnnualEventRequestBuilder anniversaries(final String id);

    IPersonAwardCollectionRequestBuilder awards();

    IPersonAwardRequestBuilder awards(final String id);

    IPersonCertificationCollectionRequestBuilder certifications();

    IPersonCertificationRequestBuilder certifications(final String id);

    IEducationalActivityCollectionRequestBuilder educationalActivities();

    IEducationalActivityRequestBuilder educationalActivities(final String id);

    IItemEmailCollectionRequestBuilder emails();

    IItemEmailRequestBuilder emails(final String id);

    IPersonInterestCollectionRequestBuilder interests();

    IPersonInterestRequestBuilder interests(final String id);

    ILanguageProficiencyCollectionRequestBuilder languages();

    ILanguageProficiencyRequestBuilder languages(final String id);

    IPersonNameCollectionRequestBuilder names();

    IPersonNameRequestBuilder names(final String id);

    IPersonAnnotationCollectionRequestBuilder notes();

    IPersonAnnotationRequestBuilder notes(final String id);

    IItemPatentCollectionRequestBuilder patents();

    IItemPatentRequestBuilder patents(final String id);

    IItemPhoneCollectionRequestBuilder phones();

    IItemPhoneRequestBuilder phones(final String id);

    IWorkPositionCollectionRequestBuilder positions();

    IWorkPositionRequestBuilder positions(final String id);

    IProjectParticipationCollectionRequestBuilder projects();

    IProjectParticipationRequestBuilder projects(final String id);

    IItemPublicationCollectionRequestBuilder publications();

    IItemPublicationRequestBuilder publications(final String id);

    ISkillProficiencyCollectionRequestBuilder skills();

    ISkillProficiencyRequestBuilder skills(final String id);

    IWebAccountCollectionRequestBuilder webAccounts();

    IWebAccountRequestBuilder webAccounts(final String id);

    IPersonWebsiteCollectionRequestBuilder websites();

    IPersonWebsiteRequestBuilder websites(final String id);

}