// Template Source: IBaseEntityCollectionRequestBuilder.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests.extensions;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.concurrency.ICallback;

import com.microsoft.graph.models.extensions.UnifiedRoleAssignmentRequest;import com.microsoft.graph.models.extensions.RbacApplication;
import com.microsoft.graph.models.extensions.UnifiedRoleAssignmentRequest;
import com.microsoft.graph.models.generated.RoleAssignmentRequestFilterByCurrentUserOptions;
import java.util.Arrays;
import java.util.EnumSet;

import com.microsoft.graph.requests.extensions.IUnifiedRoleAssignmentRequestRequestBuilder;
import com.microsoft.graph.requests.extensions.IUnifiedRoleAssignmentRequestCollectionRequest;
import com.microsoft.graph.requests.extensions.IUnifiedRoleAssignmentRequestFilterByCurrentUserCollectionRequestBuilder;
import com.microsoft.graph.http.IBaseCollectionPage;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The interface for the Unified Role Assignment Request Collection Request Builder.
 */
public interface IUnifiedRoleAssignmentRequestCollectionRequestBuilder extends IRequestBuilder {

    /**
     * Creates the request
     *
     * @param requestOptions the options for this request
     * @return the IUserRequest instance
     */
    IUnifiedRoleAssignmentRequestCollectionRequest buildRequest(final com.microsoft.graph.options.Option... requestOptions);

    /**
     * Creates the request
     *
     * @param requestOptions the options for this request
     * @return the IUserRequest instance
     */
    IUnifiedRoleAssignmentRequestCollectionRequest buildRequest(final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions);

    IUnifiedRoleAssignmentRequestRequestBuilder byId(final String id);


    IUnifiedRoleAssignmentRequestFilterByCurrentUserCollectionRequestBuilder filterByCurrentUser(final RoleAssignmentRequestFilterByCurrentUserOptions on);
}
