// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests.extensions;
import com.microsoft.graph.models.extensions.Windows10VpnConfiguration;

import com.microsoft.graph.concurrency.ICallback;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.http.IHttpRequest;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The interface for the Windows10Vpn Configuration Request.
 */
public interface IWindows10VpnConfigurationRequest extends IHttpRequest {

    /**
     * Gets the Windows10VpnConfiguration from the service
     *
     * @param callback the callback to be called after success or failure
     */
    void get(final ICallback<Windows10VpnConfiguration> callback);

    /**
     * Gets the Windows10VpnConfiguration from the service
     *
     * @return the Windows10VpnConfiguration from the request
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    Windows10VpnConfiguration get() throws ClientException;

    /**
     * Delete this item from the service
     *
     * @param callback the callback when the deletion action has completed
     */
    void delete(final ICallback<Windows10VpnConfiguration> callback);

    /**
     * Delete this item from the service
     *
     * @throws ClientException if there was an exception during the delete operation
     */
    void delete() throws ClientException;

    /**
     * Patches this Windows10VpnConfiguration with a source
     *
     * @param sourceWindows10VpnConfiguration the source object with updates
     * @param callback the callback to be called after success or failure
     */
    void patch(final Windows10VpnConfiguration sourceWindows10VpnConfiguration, final ICallback<Windows10VpnConfiguration> callback);

    /**
     * Patches this Windows10VpnConfiguration with a source
     *
     * @param sourceWindows10VpnConfiguration the source object with updates
     * @return the updated Windows10VpnConfiguration
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    Windows10VpnConfiguration patch(final Windows10VpnConfiguration sourceWindows10VpnConfiguration) throws ClientException;

    /**
     * Posts a Windows10VpnConfiguration with a new object
     *
     * @param newWindows10VpnConfiguration the new object to create
     * @param callback the callback to be called after success or failure
     */
    void post(final Windows10VpnConfiguration newWindows10VpnConfiguration, final ICallback<Windows10VpnConfiguration> callback);

    /**
     * Posts a Windows10VpnConfiguration with a new object
     *
     * @param newWindows10VpnConfiguration the new object to create
     * @return the created Windows10VpnConfiguration
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    Windows10VpnConfiguration post(final Windows10VpnConfiguration newWindows10VpnConfiguration) throws ClientException;

    /**
     * Sets the select clause for the request
     *
     * @param value the select clause
     * @return the updated request
     */
    IWindows10VpnConfigurationRequest select(final String value);

    /**
     * Sets the expand clause for the request
     *
     * @param value the expand clause
     * @return the updated request
     */
    IWindows10VpnConfigurationRequest expand(final String value);

}

