// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests.extensions;
import com.microsoft.graph.requests.extensions.IMobileAppInstallStatusRequest;
import com.microsoft.graph.requests.extensions.MobileAppInstallStatusRequest;
import com.microsoft.graph.requests.extensions.IMobileAppWithReferenceRequestBuilder;
import com.microsoft.graph.requests.extensions.MobileAppWithReferenceRequestBuilder;

import com.microsoft.graph.core.IBaseClient;
import com.microsoft.graph.http.BaseRequestBuilder;
import com.microsoft.graph.options.Option;
import java.util.EnumSet;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Mobile App Install Status Request Builder.
 */
public class MobileAppInstallStatusRequestBuilder extends BaseRequestBuilder implements IMobileAppInstallStatusRequestBuilder {

    /**
     * The request builder for the MobileAppInstallStatus
     *
     * @param requestUrl     the request URL
     * @param client         the service client
     * @param requestOptions the options for this request
     */
    public MobileAppInstallStatusRequestBuilder(final String requestUrl, final IBaseClient client, final java.util.List<? extends Option> requestOptions) {
        super(requestUrl, client, requestOptions);
    }

    /**
     * Creates the request
     *
     * @return the IMobileAppInstallStatusRequest instance
     */
    public IMobileAppInstallStatusRequest buildRequest() {
        return buildRequest(getOptions());
    }

    /**
     * Creates the request with specific requestOptions instead of the existing requestOptions
     *
     * @param requestOptions the options for this request
     * @return the IMobileAppInstallStatusRequest instance
     */
    public IMobileAppInstallStatusRequest buildRequest(final java.util.List<? extends Option> requestOptions) {
        return new MobileAppInstallStatusRequest(getRequestUrl(), getClient(), requestOptions);
    }



    /**
     * Gets the request builder for MobileApp
     *
     * @return the IMobileAppWithReferenceRequestBuilder instance
     */
    public IMobileAppWithReferenceRequestBuilder app() {
        return new MobileAppWithReferenceRequestBuilder(getRequestUrlWithAdditionalSegment("app"), getClient(), null);
    }
}

