// Template Source: BaseEntityRequest.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests.extensions;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.concurrency.ICallback;
import com.microsoft.graph.models.extensions.OneDriveUsageFileCounts;
import java.util.Arrays;
import java.util.EnumSet;
import javax.annotation.Nullable;
import javax.annotation.Nonnull;
import com.microsoft.graph.core.IBaseClient;
import com.microsoft.graph.http.BaseRequest;
import com.microsoft.graph.http.HttpMethod;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the One Drive Usage File Counts Request.
 */
public class OneDriveUsageFileCountsRequest extends BaseRequest<OneDriveUsageFileCounts> {
	
    /**
     * The request for the OneDriveUsageFileCounts
     *
     * @param requestUrl     the request URL
     * @param client         the service client
     * @param requestOptions the options for this request
     */
    public OneDriveUsageFileCountsRequest(@Nonnull final String requestUrl, @Nonnull final IBaseClient client, @Nullable final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        super(requestUrl, client, requestOptions, OneDriveUsageFileCounts.class);
    }

    /**
     * Gets the OneDriveUsageFileCounts from the service
     *
     * @param callback the callback to be called after success or failure
     */
    public void get(@Nonnull final ICallback<? super OneDriveUsageFileCounts> callback) {
        send(HttpMethod.GET, callback, null);
    }

    /**
     * Gets the OneDriveUsageFileCounts from the service
     *
     * @return the OneDriveUsageFileCounts from the request
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public OneDriveUsageFileCounts get() throws ClientException {
       return send(HttpMethod.GET, null);
    }

    /**
     * Delete this item from the service
     *
     * @param callback the callback when the deletion action has completed
     */
    public void delete(@Nonnull final ICallback<? super OneDriveUsageFileCounts> callback) {
        send(HttpMethod.DELETE, callback, null);
    }

    /**
     * Delete this item from the service
     *
     * @throws ClientException if there was an exception during the delete operation
     */
    public void delete() throws ClientException {
        send(HttpMethod.DELETE, null);
    }

    /**
     * Patches this OneDriveUsageFileCounts with a source
     *
     * @param sourceOneDriveUsageFileCounts the source object with updates
     * @param callback the callback to be called after success or failure
     */
    public void patch(@Nonnull final OneDriveUsageFileCounts sourceOneDriveUsageFileCounts, @Nonnull final ICallback<? super OneDriveUsageFileCounts> callback) {
        send(HttpMethod.PATCH, callback, sourceOneDriveUsageFileCounts);
    }

    /**
     * Patches this OneDriveUsageFileCounts with a source
     *
     * @param sourceOneDriveUsageFileCounts the source object with updates
     * @return the updated OneDriveUsageFileCounts
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public OneDriveUsageFileCounts patch(@Nonnull final OneDriveUsageFileCounts sourceOneDriveUsageFileCounts) throws ClientException {
        return send(HttpMethod.PATCH, sourceOneDriveUsageFileCounts);
    }

    /**
     * Creates a OneDriveUsageFileCounts with a new object
     *
     * @param newOneDriveUsageFileCounts the new object to create
     * @param callback the callback to be called after success or failure
     */
    public void post(@Nonnull final OneDriveUsageFileCounts newOneDriveUsageFileCounts, @Nonnull final ICallback<? super OneDriveUsageFileCounts> callback) {
        send(HttpMethod.POST, callback, newOneDriveUsageFileCounts);
    }

    /**
     * Creates a OneDriveUsageFileCounts with a new object
     *
     * @param newOneDriveUsageFileCounts the new object to create
     * @return the created OneDriveUsageFileCounts
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public OneDriveUsageFileCounts post(@Nonnull final OneDriveUsageFileCounts newOneDriveUsageFileCounts) throws ClientException {
        return send(HttpMethod.POST, newOneDriveUsageFileCounts);
    }

    /**
     * Creates a OneDriveUsageFileCounts with a new object
     *
     * @param newOneDriveUsageFileCounts the object to create/update
     * @param callback the callback to be called after success or failure
     */
    public void put(@Nonnull final OneDriveUsageFileCounts newOneDriveUsageFileCounts, @Nonnull final ICallback<? super OneDriveUsageFileCounts> callback) {
        send(HttpMethod.PUT, callback, newOneDriveUsageFileCounts);
    }

    /**
     * Creates a OneDriveUsageFileCounts with a new object
     *
     * @param newOneDriveUsageFileCounts the object to create/update
     * @return the created OneDriveUsageFileCounts
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public OneDriveUsageFileCounts put(@Nonnull final OneDriveUsageFileCounts newOneDriveUsageFileCounts) throws ClientException {
        return send(HttpMethod.PUT, newOneDriveUsageFileCounts);
    }

    /**
     * Sets the select clause for the request
     *
     * @param value the select clause
     * @return the updated request
     */
     @Nonnull
     public OneDriveUsageFileCountsRequest select(@Nonnull final String value) {
         addSelectOption(value);
         return this;
     }

    /**
     * Sets the expand clause for the request
     *
     * @param value the expand clause
     * @return the updated request
     */
     @Nonnull
     public OneDriveUsageFileCountsRequest expand(@Nonnull final String value) {
         addExpandOption(value);
         return this;
     }

}

