// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests.extensions;
import com.microsoft.graph.requests.extensions.IPrivilegedRoleAssignmentMakePermanentRequest;
import com.microsoft.graph.requests.extensions.PrivilegedRoleAssignmentMakePermanentRequest;

import com.microsoft.graph.core.BaseActionRequestBuilder;
import com.microsoft.graph.core.BaseFunctionRequestBuilder;
import com.microsoft.graph.core.IBaseClient;
import com.microsoft.graph.options.Option;
import com.microsoft.graph.options.FunctionOption;
import com.google.gson.JsonElement;
import com.microsoft.graph.core.BaseActionRequestBuilder;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Privileged Role Assignment Make Permanent Request Builder.
 */
public class PrivilegedRoleAssignmentMakePermanentRequestBuilder extends BaseActionRequestBuilder implements IPrivilegedRoleAssignmentMakePermanentRequestBuilder {

    /**
     * The request builder for this PrivilegedRoleAssignmentMakePermanent
     *
     * @param requestUrl     the request URL
     * @param client         the service client
     * @param requestOptions the options for this request
     * @param reason the reason
     * @param ticketNumber the ticketNumber
     * @param ticketSystem the ticketSystem
     */
    public PrivilegedRoleAssignmentMakePermanentRequestBuilder(final String requestUrl, final IBaseClient client, final java.util.List<? extends Option> requestOptions, final String reason, final String ticketNumber, final String ticketSystem) {
        super(requestUrl, client, requestOptions);
        bodyParams.put("reason", reason);
        bodyParams.put("ticketNumber", ticketNumber);
        bodyParams.put("ticketSystem", ticketSystem);
    }

    /**
     * Creates the IPrivilegedRoleAssignmentMakePermanentRequest
     *
     * @return the IPrivilegedRoleAssignmentMakePermanentRequest instance
     */
    public IPrivilegedRoleAssignmentMakePermanentRequest buildRequest() {
        return buildRequest(getOptions());
    }

    /**
     * Creates the IPrivilegedRoleAssignmentMakePermanentRequest with specific requestOptions instead of the existing requestOptions
     *
     * @param requestOptions the options for the request
     * @return the IPrivilegedRoleAssignmentMakePermanentRequest instance
     */
    public IPrivilegedRoleAssignmentMakePermanentRequest buildRequest(final java.util.List<? extends Option> requestOptions) {
        PrivilegedRoleAssignmentMakePermanentRequest request = new PrivilegedRoleAssignmentMakePermanentRequest(
                getRequestUrl(),
                getClient(),
                requestOptions
        );

        if (hasParameter("reason")) {
            request.body.reason = getParameter("reason");
        }

        if (hasParameter("ticketNumber")) {
            request.body.ticketNumber = getParameter("ticketNumber");
        }

        if (hasParameter("ticketSystem")) {
            request.body.ticketSystem = getParameter("ticketSystem");
        }

        return request;
    }
}
