// Template Source: BaseEntityRequest.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests.extensions;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.concurrency.ICallback;
import com.microsoft.graph.models.extensions.PrivilegedAccess;
import com.microsoft.graph.requests.extensions.GovernanceResourceCollectionRequestBuilder;
import com.microsoft.graph.requests.extensions.GovernanceResourceRequestBuilder;
import com.microsoft.graph.requests.extensions.GovernanceRoleAssignmentRequestCollectionRequestBuilder;
import com.microsoft.graph.requests.extensions.GovernanceRoleAssignmentRequestRequestBuilder;
import com.microsoft.graph.requests.extensions.GovernanceRoleAssignmentCollectionRequestBuilder;
import com.microsoft.graph.requests.extensions.GovernanceRoleAssignmentRequestBuilder;
import com.microsoft.graph.requests.extensions.GovernanceRoleDefinitionCollectionRequestBuilder;
import com.microsoft.graph.requests.extensions.GovernanceRoleDefinitionRequestBuilder;
import com.microsoft.graph.requests.extensions.GovernanceRoleSettingCollectionRequestBuilder;
import com.microsoft.graph.requests.extensions.GovernanceRoleSettingRequestBuilder;
import java.util.Arrays;
import java.util.EnumSet;
import javax.annotation.Nullable;
import javax.annotation.Nonnull;
import com.microsoft.graph.core.IBaseClient;
import com.microsoft.graph.http.BaseRequest;
import com.microsoft.graph.http.HttpMethod;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Privileged Access Request.
 */
public class PrivilegedAccessRequest extends BaseRequest<PrivilegedAccess> {
	
    /**
     * The request for the PrivilegedAccess
     *
     * @param requestUrl     the request URL
     * @param client         the service client
     * @param requestOptions the options for this request
     */
    public PrivilegedAccessRequest(@Nonnull final String requestUrl, @Nonnull final IBaseClient client, @Nullable final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        super(requestUrl, client, requestOptions, PrivilegedAccess.class);
    }

    /**
     * Gets the PrivilegedAccess from the service
     *
     * @param callback the callback to be called after success or failure
     */
    public void get(@Nonnull final ICallback<? super PrivilegedAccess> callback) {
        send(HttpMethod.GET, callback, null);
    }

    /**
     * Gets the PrivilegedAccess from the service
     *
     * @return the PrivilegedAccess from the request
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public PrivilegedAccess get() throws ClientException {
       return send(HttpMethod.GET, null);
    }

    /**
     * Delete this item from the service
     *
     * @param callback the callback when the deletion action has completed
     */
    public void delete(@Nonnull final ICallback<? super PrivilegedAccess> callback) {
        send(HttpMethod.DELETE, callback, null);
    }

    /**
     * Delete this item from the service
     *
     * @throws ClientException if there was an exception during the delete operation
     */
    public void delete() throws ClientException {
        send(HttpMethod.DELETE, null);
    }

    /**
     * Patches this PrivilegedAccess with a source
     *
     * @param sourcePrivilegedAccess the source object with updates
     * @param callback the callback to be called after success or failure
     */
    public void patch(@Nonnull final PrivilegedAccess sourcePrivilegedAccess, @Nonnull final ICallback<? super PrivilegedAccess> callback) {
        send(HttpMethod.PATCH, callback, sourcePrivilegedAccess);
    }

    /**
     * Patches this PrivilegedAccess with a source
     *
     * @param sourcePrivilegedAccess the source object with updates
     * @return the updated PrivilegedAccess
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public PrivilegedAccess patch(@Nonnull final PrivilegedAccess sourcePrivilegedAccess) throws ClientException {
        return send(HttpMethod.PATCH, sourcePrivilegedAccess);
    }

    /**
     * Creates a PrivilegedAccess with a new object
     *
     * @param newPrivilegedAccess the new object to create
     * @param callback the callback to be called after success or failure
     */
    public void post(@Nonnull final PrivilegedAccess newPrivilegedAccess, @Nonnull final ICallback<? super PrivilegedAccess> callback) {
        send(HttpMethod.POST, callback, newPrivilegedAccess);
    }

    /**
     * Creates a PrivilegedAccess with a new object
     *
     * @param newPrivilegedAccess the new object to create
     * @return the created PrivilegedAccess
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public PrivilegedAccess post(@Nonnull final PrivilegedAccess newPrivilegedAccess) throws ClientException {
        return send(HttpMethod.POST, newPrivilegedAccess);
    }

    /**
     * Creates a PrivilegedAccess with a new object
     *
     * @param newPrivilegedAccess the object to create/update
     * @param callback the callback to be called after success or failure
     */
    public void put(@Nonnull final PrivilegedAccess newPrivilegedAccess, @Nonnull final ICallback<? super PrivilegedAccess> callback) {
        send(HttpMethod.PUT, callback, newPrivilegedAccess);
    }

    /**
     * Creates a PrivilegedAccess with a new object
     *
     * @param newPrivilegedAccess the object to create/update
     * @return the created PrivilegedAccess
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public PrivilegedAccess put(@Nonnull final PrivilegedAccess newPrivilegedAccess) throws ClientException {
        return send(HttpMethod.PUT, newPrivilegedAccess);
    }

    /**
     * Sets the select clause for the request
     *
     * @param value the select clause
     * @return the updated request
     */
     @Nonnull
     public PrivilegedAccessRequest select(@Nonnull final String value) {
         addSelectOption(value);
         return this;
     }

    /**
     * Sets the expand clause for the request
     *
     * @param value the expand clause
     * @return the updated request
     */
     @Nonnull
     public PrivilegedAccessRequest expand(@Nonnull final String value) {
         addExpandOption(value);
         return this;
     }

}

