// Template Source: BaseEntityCollectionPage.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests.extensions;
import com.microsoft.graph.models.extensions.ProgramControl;
import com.microsoft.graph.requests.extensions.ProgramControlCollectionRequestBuilder;
import javax.annotation.Nullable;
import javax.annotation.Nonnull;
import com.microsoft.graph.requests.extensions.ProgramControlCollectionResponse;
import com.microsoft.graph.http.BaseCollectionPage;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Program Control Collection Page.
 */
public class ProgramControlCollectionPage extends BaseCollectionPage<ProgramControl, ProgramControlCollectionRequestBuilder> {

    /**
     * A collection page for ProgramControl
     *
     * @param response the serialized ProgramControlCollectionResponse from the service
     * @param builder  the request builder for the next collection page
     */
    public ProgramControlCollectionPage(@Nonnull final ProgramControlCollectionResponse response, @Nonnull final ProgramControlCollectionRequestBuilder builder) {
        super(response, builder);
    }

    /**
     * Creates the collection page for ProgramControl
     *
     * @param pageContents       the contents of this page
     * @param nextRequestBuilder the request builder for the next page
     */
    public ProgramControlCollectionPage(@Nonnull final java.util.List<ProgramControl> pageContents, @Nullable final ProgramControlCollectionRequestBuilder nextRequestBuilder) {
        super(pageContents, nextRequestBuilder);
    }
}
