// Template Source: BaseEntityRequestBuilder.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests.extensions;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.concurrency.ICallback;
import com.microsoft.graph.models.extensions.UnifiedRoleAssignmentRequest;
import com.microsoft.graph.models.generated.RoleAssignmentRequestFilterByCurrentUserOptions;
import com.microsoft.graph.requests.extensions.IUnifiedRoleEligibilityScheduleWithReferenceRequestBuilder;
import com.microsoft.graph.requests.extensions.UnifiedRoleEligibilityScheduleWithReferenceRequestBuilder;
import com.microsoft.graph.requests.extensions.IAppScopeWithReferenceRequestBuilder;
import com.microsoft.graph.requests.extensions.AppScopeWithReferenceRequestBuilder;
import com.microsoft.graph.requests.extensions.IDirectoryObjectWithReferenceRequestBuilder;
import com.microsoft.graph.requests.extensions.DirectoryObjectWithReferenceRequestBuilder;
import com.microsoft.graph.requests.extensions.IUnifiedRoleDefinitionWithReferenceRequestBuilder;
import com.microsoft.graph.requests.extensions.UnifiedRoleDefinitionWithReferenceRequestBuilder;
import com.microsoft.graph.requests.extensions.IUnifiedRoleAssignmentScheduleWithReferenceRequestBuilder;
import com.microsoft.graph.requests.extensions.UnifiedRoleAssignmentScheduleWithReferenceRequestBuilder;
import java.util.Arrays;
import java.util.EnumSet;
import com.microsoft.graph.core.IBaseClient;
import com.microsoft.graph.http.BaseRequestBuilder;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Unified Role Assignment Request Request Builder.
 */
public class UnifiedRoleAssignmentRequestRequestBuilder extends BaseRequestBuilder implements IUnifiedRoleAssignmentRequestRequestBuilder {

    /**
     * The request builder for the UnifiedRoleAssignmentRequest
     *
     * @param requestUrl     the request URL
     * @param client         the service client
     * @param requestOptions the options for this request
     */
    public UnifiedRoleAssignmentRequestRequestBuilder(final String requestUrl, final IBaseClient client, final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        super(requestUrl, client, requestOptions);
    }

    /**
     * Creates the request
     *
     * @param requestOptions the options for this request
     * @return the IUnifiedRoleAssignmentRequestRequest instance
     */
    public IUnifiedRoleAssignmentRequestRequest buildRequest(final com.microsoft.graph.options.Option... requestOptions) {
        return buildRequest(getOptions(requestOptions));
    }

    /**
     * Creates the request with specific requestOptions instead of the existing requestOptions
     *
     * @param requestOptions the options for this request
     * @return the IUnifiedRoleAssignmentRequestRequest instance
     */
    public IUnifiedRoleAssignmentRequestRequest buildRequest(final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        return new com.microsoft.graph.requests.extensions.UnifiedRoleAssignmentRequestRequest(getRequestUrl(), getClient(), requestOptions);
    }



    /**
     * Gets the request builder for UnifiedRoleEligibilitySchedule
     *
     * @return the IUnifiedRoleEligibilityScheduleWithReferenceRequestBuilder instance
     */
    public IUnifiedRoleEligibilityScheduleWithReferenceRequestBuilder activatedUsing() {
        return new UnifiedRoleEligibilityScheduleWithReferenceRequestBuilder(getRequestUrlWithAdditionalSegment("activatedUsing"), getClient(), null);
    }

    /**
     * Gets the request builder for AppScope
     *
     * @return the IAppScopeWithReferenceRequestBuilder instance
     */
    public IAppScopeWithReferenceRequestBuilder appScope() {
        return new AppScopeWithReferenceRequestBuilder(getRequestUrlWithAdditionalSegment("appScope"), getClient(), null);
    }

    /**
     * Gets the request builder for DirectoryObject
     *
     * @return the IDirectoryObjectWithReferenceRequestBuilder instance
     */
    public IDirectoryObjectWithReferenceRequestBuilder directoryScope() {
        return new DirectoryObjectWithReferenceRequestBuilder(getRequestUrlWithAdditionalSegment("directoryScope"), getClient(), null);
    }

    /**
     * Gets the request builder for DirectoryObject
     *
     * @return the IDirectoryObjectWithReferenceRequestBuilder instance
     */
    public IDirectoryObjectWithReferenceRequestBuilder principal() {
        return new DirectoryObjectWithReferenceRequestBuilder(getRequestUrlWithAdditionalSegment("principal"), getClient(), null);
    }

    /**
     * Gets the request builder for UnifiedRoleDefinition
     *
     * @return the IUnifiedRoleDefinitionWithReferenceRequestBuilder instance
     */
    public IUnifiedRoleDefinitionWithReferenceRequestBuilder roleDefinition() {
        return new UnifiedRoleDefinitionWithReferenceRequestBuilder(getRequestUrlWithAdditionalSegment("roleDefinition"), getClient(), null);
    }

    /**
     * Gets the request builder for UnifiedRoleAssignmentSchedule
     *
     * @return the IUnifiedRoleAssignmentScheduleWithReferenceRequestBuilder instance
     */
    public IUnifiedRoleAssignmentScheduleWithReferenceRequestBuilder targetSchedule() {
        return new UnifiedRoleAssignmentScheduleWithReferenceRequestBuilder(getRequestUrlWithAdditionalSegment("targetSchedule"), getClient(), null);
    }

    public IUnifiedRoleAssignmentRequestCancelRequestBuilder cancel() {
        return new UnifiedRoleAssignmentRequestCancelRequestBuilder(getRequestUrlWithAdditionalSegment("microsoft.graph.cancel"), getClient(), null);
    }
}
