// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests.extensions;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.concurrency.ICallback;
import com.microsoft.graph.models.extensions.UserExperienceAnalyticsRegressionSummary;

import java.util.Arrays;
import java.util.EnumSet;

import com.microsoft.graph.requests.extensions.IUserExperienceAnalyticsMetricCollectionRequestBuilder;
import com.microsoft.graph.requests.extensions.IUserExperienceAnalyticsMetricRequestBuilder;
import com.microsoft.graph.requests.extensions.IUserExperienceAnalyticsMetricCollectionRequest;
import com.microsoft.graph.models.extensions.UserExperienceAnalyticsMetric;
import com.microsoft.graph.options.Option;
import com.microsoft.graph.http.BaseRequestBuilder;
import com.microsoft.graph.core.IBaseClient;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the User Experience Analytics Metric Collection Request Builder.
 */
public class UserExperienceAnalyticsMetricCollectionRequestBuilder extends BaseRequestBuilder implements IUserExperienceAnalyticsMetricCollectionRequestBuilder {

    /**
     * The request builder for this collection of UserExperienceAnalyticsRegressionSummary
     *
     * @param requestUrl     the request URL
     * @param client         the service client
     * @param requestOptions the options for this request
     */
    public UserExperienceAnalyticsMetricCollectionRequestBuilder(final String requestUrl, final IBaseClient client, final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        super(requestUrl, client, requestOptions);
    }

    public IUserExperienceAnalyticsMetricCollectionRequest buildRequest() {
        return buildRequest(getOptions());
    }

    public IUserExperienceAnalyticsMetricCollectionRequest buildRequest(final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        return new UserExperienceAnalyticsMetricCollectionRequest(getRequestUrl(), getClient(), requestOptions);
    }

    public IUserExperienceAnalyticsMetricRequestBuilder byId(final String id) {
        return new UserExperienceAnalyticsMetricRequestBuilder(getRequestUrlWithAdditionalSegment(id), getClient(), getOptions());
    }


}
