// Template Source: BaseMethodCollectionRequestBuilder.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests.extensions;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.concurrency.ICallback;
import com.microsoft.graph.models.extensions.ManagedDevice;
import java.util.Arrays;
import java.util.EnumSet;
import javax.annotation.Nullable;
import javax.annotation.Nonnull;

import com.microsoft.graph.requests.extensions.UserGetLoggedOnManagedDevicesCollectionRequestBuilder;
import com.microsoft.graph.requests.extensions.UserGetLoggedOnManagedDevicesCollectionRequest;
import com.microsoft.graph.requests.extensions.UserGetLoggedOnManagedDevicesCollectionResponse;
import com.microsoft.graph.options.FunctionOption;
import com.microsoft.graph.core.IBaseClient;
import com.microsoft.graph.http.BaseFunctionCollectionRequestBuilder;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the User Get Logged On Managed Devices Collection Request Builder.
 */
public class UserGetLoggedOnManagedDevicesCollectionRequestBuilder extends BaseFunctionCollectionRequestBuilder<ManagedDevice, UserGetLoggedOnManagedDevicesCollectionRequestBuilder, UserGetLoggedOnManagedDevicesCollectionResponse, UserGetLoggedOnManagedDevicesCollectionPage, UserGetLoggedOnManagedDevicesCollectionRequest> {

    /**
     * The request builder for this collection of User
     *
     * @param requestUrl     the request URL
     * @param client         the service client
     * @param requestOptions the options for this request
     */
    public UserGetLoggedOnManagedDevicesCollectionRequestBuilder(@Nonnull final String requestUrl, @Nonnull final IBaseClient client, @Nullable final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        super(requestUrl, client, requestOptions, UserGetLoggedOnManagedDevicesCollectionRequestBuilder.class, UserGetLoggedOnManagedDevicesCollectionRequest.class);
    }
    /**
     * Creates the request
     *
     * @param requestOptions the options for this request
     * @return the UserGetLoggedOnManagedDevicesCollectionRequest instance
     */
    @Override
    @Nonnull
    public UserGetLoggedOnManagedDevicesCollectionRequest buildRequest(@Nullable final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        final UserGetLoggedOnManagedDevicesCollectionRequest request = super.buildRequest(requestOptions);
        return request;
    }
}
