// Template Source: BaseEntityRequest.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests.extensions;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.concurrency.ICallback;
import com.microsoft.graph.models.extensions.WindowsDomainJoinConfiguration;
import com.microsoft.graph.requests.extensions.DeviceConfigurationCollectionRequestBuilder;
import com.microsoft.graph.requests.extensions.DeviceConfigurationRequestBuilder;
import java.util.Arrays;
import java.util.EnumSet;
import javax.annotation.Nullable;
import javax.annotation.Nonnull;
import com.microsoft.graph.core.IBaseClient;
import com.microsoft.graph.http.BaseRequest;
import com.microsoft.graph.http.HttpMethod;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Windows Domain Join Configuration Request.
 */
public class WindowsDomainJoinConfigurationRequest extends BaseRequest<WindowsDomainJoinConfiguration> {
	
    /**
     * The request for the WindowsDomainJoinConfiguration
     *
     * @param requestUrl     the request URL
     * @param client         the service client
     * @param requestOptions the options for this request
     */
    public WindowsDomainJoinConfigurationRequest(@Nonnull final String requestUrl, @Nonnull final IBaseClient client, @Nullable final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        super(requestUrl, client, requestOptions, WindowsDomainJoinConfiguration.class);
    }

    /**
     * Gets the WindowsDomainJoinConfiguration from the service
     *
     * @param callback the callback to be called after success or failure
     */
    public void get(@Nonnull final ICallback<? super WindowsDomainJoinConfiguration> callback) {
        send(HttpMethod.GET, callback, null);
    }

    /**
     * Gets the WindowsDomainJoinConfiguration from the service
     *
     * @return the WindowsDomainJoinConfiguration from the request
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public WindowsDomainJoinConfiguration get() throws ClientException {
       return send(HttpMethod.GET, null);
    }

    /**
     * Delete this item from the service
     *
     * @param callback the callback when the deletion action has completed
     */
    public void delete(@Nonnull final ICallback<? super WindowsDomainJoinConfiguration> callback) {
        send(HttpMethod.DELETE, callback, null);
    }

    /**
     * Delete this item from the service
     *
     * @throws ClientException if there was an exception during the delete operation
     */
    public void delete() throws ClientException {
        send(HttpMethod.DELETE, null);
    }

    /**
     * Patches this WindowsDomainJoinConfiguration with a source
     *
     * @param sourceWindowsDomainJoinConfiguration the source object with updates
     * @param callback the callback to be called after success or failure
     */
    public void patch(@Nonnull final WindowsDomainJoinConfiguration sourceWindowsDomainJoinConfiguration, @Nonnull final ICallback<? super WindowsDomainJoinConfiguration> callback) {
        send(HttpMethod.PATCH, callback, sourceWindowsDomainJoinConfiguration);
    }

    /**
     * Patches this WindowsDomainJoinConfiguration with a source
     *
     * @param sourceWindowsDomainJoinConfiguration the source object with updates
     * @return the updated WindowsDomainJoinConfiguration
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public WindowsDomainJoinConfiguration patch(@Nonnull final WindowsDomainJoinConfiguration sourceWindowsDomainJoinConfiguration) throws ClientException {
        return send(HttpMethod.PATCH, sourceWindowsDomainJoinConfiguration);
    }

    /**
     * Creates a WindowsDomainJoinConfiguration with a new object
     *
     * @param newWindowsDomainJoinConfiguration the new object to create
     * @param callback the callback to be called after success or failure
     */
    public void post(@Nonnull final WindowsDomainJoinConfiguration newWindowsDomainJoinConfiguration, @Nonnull final ICallback<? super WindowsDomainJoinConfiguration> callback) {
        send(HttpMethod.POST, callback, newWindowsDomainJoinConfiguration);
    }

    /**
     * Creates a WindowsDomainJoinConfiguration with a new object
     *
     * @param newWindowsDomainJoinConfiguration the new object to create
     * @return the created WindowsDomainJoinConfiguration
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public WindowsDomainJoinConfiguration post(@Nonnull final WindowsDomainJoinConfiguration newWindowsDomainJoinConfiguration) throws ClientException {
        return send(HttpMethod.POST, newWindowsDomainJoinConfiguration);
    }

    /**
     * Creates a WindowsDomainJoinConfiguration with a new object
     *
     * @param newWindowsDomainJoinConfiguration the object to create/update
     * @param callback the callback to be called after success or failure
     */
    public void put(@Nonnull final WindowsDomainJoinConfiguration newWindowsDomainJoinConfiguration, @Nonnull final ICallback<? super WindowsDomainJoinConfiguration> callback) {
        send(HttpMethod.PUT, callback, newWindowsDomainJoinConfiguration);
    }

    /**
     * Creates a WindowsDomainJoinConfiguration with a new object
     *
     * @param newWindowsDomainJoinConfiguration the object to create/update
     * @return the created WindowsDomainJoinConfiguration
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public WindowsDomainJoinConfiguration put(@Nonnull final WindowsDomainJoinConfiguration newWindowsDomainJoinConfiguration) throws ClientException {
        return send(HttpMethod.PUT, newWindowsDomainJoinConfiguration);
    }

    /**
     * Sets the select clause for the request
     *
     * @param value the select clause
     * @return the updated request
     */
     @Nonnull
     public WindowsDomainJoinConfigurationRequest select(@Nonnull final String value) {
         addSelectOption(value);
         return this;
     }

    /**
     * Sets the expand clause for the request
     *
     * @param value the expand clause
     * @return the updated request
     */
     @Nonnull
     public WindowsDomainJoinConfigurationRequest expand(@Nonnull final String value) {
         addExpandOption(value);
         return this;
     }

}

