// Template Source: BaseMethodRequestBuilder.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.managedtenants.requests;
import com.microsoft.graph.managedtenants.requests.TenantOffboardTenantRequest;
import com.microsoft.graph.managedtenants.models.Tenant;
import com.microsoft.graph.http.BaseActionRequestBuilder;
import com.microsoft.graph.core.IBaseClient;
import com.google.gson.JsonElement;
import javax.annotation.Nullable;
import javax.annotation.Nonnull;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Tenant Offboard Tenant Request Builder.
 */
public class TenantOffboardTenantRequestBuilder extends BaseActionRequestBuilder<Tenant> {

    /**
     * The request builder for this TenantOffboardTenant
     *
     * @param requestUrl     the request URL
     * @param client         the service client
     * @param requestOptions the options for this request
     */
    public TenantOffboardTenantRequestBuilder(@Nonnull final String requestUrl, @Nonnull final IBaseClient<?> client, @Nullable final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        super(requestUrl, client, requestOptions);
    }

    /**
     * Creates the TenantOffboardTenantRequest
     *
     * @param requestOptions the options for the request
     * @return the TenantOffboardTenantRequest instance
     */
    @Nonnull
    public TenantOffboardTenantRequest buildRequest(@Nullable final com.microsoft.graph.options.Option... requestOptions) {
        return buildRequest(getOptions(requestOptions));
    }

    /**
     * Creates the TenantOffboardTenantRequest with specific requestOptions instead of the existing requestOptions
     *
     * @param requestOptions the options for the request
     * @return the TenantOffboardTenantRequest instance
     */
    @Nonnull
    public TenantOffboardTenantRequest buildRequest(@Nonnull final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        final TenantOffboardTenantRequest request = new TenantOffboardTenantRequest(
                getRequestUrl(),
                getClient(),
                requestOptions);
        return request;
    }
}
