// Template Source: BaseEntity.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.models;
import com.microsoft.graph.serializer.ISerializer;
import com.microsoft.graph.serializer.IJsonBackedObject;
import com.microsoft.graph.serializer.AdditionalDataManager;
import java.util.EnumSet;
import com.microsoft.graph.http.BaseCollectionPage;
import com.microsoft.graph.models.AccessPackageResourceAttribute;
import com.microsoft.graph.models.AccessPackageResourceEnvironment;
import com.microsoft.graph.models.Entity;
import com.microsoft.graph.requests.AccessPackageResourceRoleCollectionPage;
import com.microsoft.graph.requests.AccessPackageResourceScopeCollectionPage;


import com.google.gson.JsonObject;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import javax.annotation.Nullable;
import javax.annotation.Nonnull;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Access Package Resource.
 */
public class AccessPackageResource extends Entity implements IJsonBackedObject {


    /**
     * The Added By.
     * The name of the user or application that first added this resource. Read-only.
     */
    @SerializedName(value = "addedBy", alternate = {"AddedBy"})
    @Expose
	@Nullable
    public String addedBy;

    /**
     * The Added On.
     * The Timestamp type represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 is 2014-01-01T00:00:00Z. Read-only.
     */
    @SerializedName(value = "addedOn", alternate = {"AddedOn"})
    @Expose
	@Nullable
    public java.time.OffsetDateTime addedOn;

    /**
     * The Attributes.
     * Contains information about the attributes to be collected from the requestor and sent to the resource application.
     */
    @SerializedName(value = "attributes", alternate = {"Attributes"})
    @Expose
	@Nullable
    public java.util.List<AccessPackageResourceAttribute> attributes;

    /**
     * The Description.
     * A description for the resource.
     */
    @SerializedName(value = "description", alternate = {"Description"})
    @Expose
	@Nullable
    public String description;

    /**
     * The Display Name.
     * The display name of the resource, such as the application name, group name or site name.
     */
    @SerializedName(value = "displayName", alternate = {"DisplayName"})
    @Expose
	@Nullable
    public String displayName;

    /**
     * The Is Pending Onboarding.
     * True if the resource is not yet available for assignment. Read-only.
     */
    @SerializedName(value = "isPendingOnboarding", alternate = {"IsPendingOnboarding"})
    @Expose
	@Nullable
    public Boolean isPendingOnboarding;

    /**
     * The Origin Id.
     * The unique identifier of the resource in the origin system. In the case of an Azure AD group, this is the identifier of the group.
     */
    @SerializedName(value = "originId", alternate = {"OriginId"})
    @Expose
	@Nullable
    public String originId;

    /**
     * The Origin System.
     * The type of the resource in the origin system, such as SharePointOnline, AadApplication or AadGroup.
     */
    @SerializedName(value = "originSystem", alternate = {"OriginSystem"})
    @Expose
	@Nullable
    public String originSystem;

    /**
     * The Resource Type.
     * The type of the resource, such as Application if it is an Azure AD connected application, or SharePoint Online Site for a SharePoint Online site.
     */
    @SerializedName(value = "resourceType", alternate = {"ResourceType"})
    @Expose
	@Nullable
    public String resourceType;

    /**
     * The Url.
     * A unique resource locator for the resource, such as the URL for signing a user into an application.
     */
    @SerializedName(value = "url", alternate = {"Url"})
    @Expose
	@Nullable
    public String url;

    /**
     * The Access Package Resource Environment.
     * Contains the environment information for the resource. This can be set using either the @odata.bind annotation or the environment's originId.Supports $expand.
     */
    @SerializedName(value = "accessPackageResourceEnvironment", alternate = {"AccessPackageResourceEnvironment"})
    @Expose
	@Nullable
    public AccessPackageResourceEnvironment accessPackageResourceEnvironment;

    /**
     * The Access Package Resource Roles.
     * Read-only. Nullable. Supports $expand.
     */
    @SerializedName(value = "accessPackageResourceRoles", alternate = {"AccessPackageResourceRoles"})
    @Expose
	@Nullable
    public com.microsoft.graph.requests.AccessPackageResourceRoleCollectionPage accessPackageResourceRoles;

    /**
     * The Access Package Resource Scopes.
     * Read-only. Nullable. Supports $expand.
     */
    @SerializedName(value = "accessPackageResourceScopes", alternate = {"AccessPackageResourceScopes"})
    @Expose
	@Nullable
    public com.microsoft.graph.requests.AccessPackageResourceScopeCollectionPage accessPackageResourceScopes;


    /**
     * Sets the raw JSON object
     *
     * @param serializer the serializer
     * @param json the JSON object to set this object to
     */
    public void setRawObject(@Nonnull final ISerializer serializer, @Nonnull final JsonObject json) {


        if (json.has("accessPackageResourceRoles")) {
            accessPackageResourceRoles = serializer.deserializeObject(json.get("accessPackageResourceRoles"), com.microsoft.graph.requests.AccessPackageResourceRoleCollectionPage.class);
        }

        if (json.has("accessPackageResourceScopes")) {
            accessPackageResourceScopes = serializer.deserializeObject(json.get("accessPackageResourceScopes"), com.microsoft.graph.requests.AccessPackageResourceScopeCollectionPage.class);
        }
    }
}
