// Template Source: BaseEntity.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.models;
import com.microsoft.graph.serializer.ISerializer;
import com.microsoft.graph.serializer.IJsonBackedObject;
import com.microsoft.graph.serializer.AdditionalDataManager;
import java.util.EnumSet;
import com.microsoft.graph.models.DeviceManagementConfigurationSettingGroupDefinition;


import com.google.gson.JsonObject;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import javax.annotation.Nullable;
import javax.annotation.Nonnull;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Device Management Configuration Setting Group Collection Definition.
 */
public class DeviceManagementConfigurationSettingGroupCollectionDefinition extends DeviceManagementConfigurationSettingGroupDefinition implements IJsonBackedObject {


    /**
     * The Maximum Count.
     * Maximum number of setting group count in the collection. Valid values 1 to 100
     */
    @SerializedName(value = "maximumCount", alternate = {"MaximumCount"})
    @Expose
	@Nullable
    public Integer maximumCount;

    /**
     * The Minimum Count.
     * Minimum number of setting group count in the collection. Valid values 1 to 100
     */
    @SerializedName(value = "minimumCount", alternate = {"MinimumCount"})
    @Expose
	@Nullable
    public Integer minimumCount;


    /**
     * Sets the raw JSON object
     *
     * @param serializer the serializer
     * @param json the JSON object to set this object to
     */
    public void setRawObject(@Nonnull final ISerializer serializer, @Nonnull final JsonObject json) {

    }
}
