// Template Source: BaseMethodParameterSet.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.models;


import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.google.gson.JsonObject;
import java.util.EnumSet;
import java.util.ArrayList;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Education Assignment Get Resources Folder Url Parameter Set.
 */
public class EducationAssignmentGetResourcesFolderUrlParameterSet {

    /**
     * Instiaciates a new EducationAssignmentGetResourcesFolderUrlParameterSet
     */
    public EducationAssignmentGetResourcesFolderUrlParameterSet() {}
    /**
     * Instiaciates a new EducationAssignmentGetResourcesFolderUrlParameterSet
     * @param builder builder bearing the parameters to initialize from
     */
    protected EducationAssignmentGetResourcesFolderUrlParameterSet(@Nonnull final EducationAssignmentGetResourcesFolderUrlParameterSetBuilder builder) {
    }
    /**
     * Gets a new builder for the body
     * @return a new builder
     */
    @Nonnull
    public static EducationAssignmentGetResourcesFolderUrlParameterSetBuilder newBuilder() {
        return new EducationAssignmentGetResourcesFolderUrlParameterSetBuilder();
    }
    /**
     * Fluent builder for the EducationAssignmentGetResourcesFolderUrlParameterSet
     */
    public static final class EducationAssignmentGetResourcesFolderUrlParameterSetBuilder {
        /**
         * Instanciates a new EducationAssignmentGetResourcesFolderUrlParameterSetBuilder
         */
        @Nullable
        protected EducationAssignmentGetResourcesFolderUrlParameterSetBuilder(){}
        /**
         * Buils the resulting body object to be passed to the request
         * @return the body object to pass to the request
         */
        @Nonnull
        public EducationAssignmentGetResourcesFolderUrlParameterSet build() {
            return new EducationAssignmentGetResourcesFolderUrlParameterSet(this);
        }
    }
    /**
     * Gets the functions options from the properties that have been set
     * @return a list of function options for the request
     */
    @Nonnull
    public java.util.List<com.microsoft.graph.options.FunctionOption> getFunctionOptions() {
        final ArrayList<com.microsoft.graph.options.FunctionOption> result = new ArrayList<>();
        return result;
    }
}
