// Template Source: BaseEntity.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.models;
import com.microsoft.graph.serializer.ISerializer;
import com.microsoft.graph.serializer.IJsonBackedObject;
import com.microsoft.graph.serializer.AdditionalDataManager;
import java.util.EnumSet;
import com.microsoft.graph.http.BaseCollectionPage;
import com.microsoft.graph.models.GcpRoleType;
import com.microsoft.graph.models.GcpScope;
import com.microsoft.graph.models.Entity;


import com.google.gson.JsonObject;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import javax.annotation.Nullable;
import javax.annotation.Nonnull;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Gcp Role.
 */
public class GcpRole extends Entity implements IJsonBackedObject {


    /**
     * The Display Name.
     * The name of the GCP role. Supports $filter and (eq,contains).
     */
    @SerializedName(value = "displayName", alternate = {"DisplayName"})
    @Expose
	@Nullable
    public String displayName;

    /**
     * The External Id.
     * The ID of the GCP role as defined by GCP. Alternate key.
     */
    @SerializedName(value = "externalId", alternate = {"ExternalId"})
    @Expose
	@Nullable
    public String externalId;

    /**
     * The Gcp Role Type.
     * The type of GCP role. The possible values are: system, custom, unknownFutureValue. Supports $filter and (eq).
     */
    @SerializedName(value = "gcpRoleType", alternate = {"GcpRoleType"})
    @Expose
	@Nullable
    public GcpRoleType gcpRoleType;

    /**
     * The Scopes.
     * Resources that an identity assigned this GCP role can perform actions on. Supports $filter and (eq).
     */
    @SerializedName(value = "scopes", alternate = {"Scopes"})
    @Expose
	@Nullable
    public java.util.List<GcpScope> scopes;


    /**
     * Sets the raw JSON object
     *
     * @param serializer the serializer
     * @param json the JSON object to set this object to
     */
    public void setRawObject(@Nonnull final ISerializer serializer, @Nonnull final JsonObject json) {

    }
}
