// Template Source: BaseEntity.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.models;
import com.microsoft.graph.serializer.ISerializer;
import com.microsoft.graph.serializer.IJsonBackedObject;
import com.microsoft.graph.serializer.AdditionalDataManager;
import java.util.EnumSet;
import com.microsoft.graph.http.BaseCollectionPage;
import com.microsoft.graph.models.NdesConnectorState;
import com.microsoft.graph.models.Entity;


import com.google.gson.JsonObject;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import javax.annotation.Nullable;
import javax.annotation.Nonnull;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Ndes Connector.
 */
public class NdesConnector extends Entity implements IJsonBackedObject {


    /**
     * The Connector Version.
     * The build version of the Ndes Connector.
     */
    @SerializedName(value = "connectorVersion", alternate = {"ConnectorVersion"})
    @Expose
	@Nullable
    public String connectorVersion;

    /**
     * The Display Name.
     * The friendly name of the Ndes Connector.
     */
    @SerializedName(value = "displayName", alternate = {"DisplayName"})
    @Expose
	@Nullable
    public String displayName;

    /**
     * The Enrolled Date Time.
     * Timestamp when on-prem certificate connector was enrolled in Intune.
     */
    @SerializedName(value = "enrolledDateTime", alternate = {"EnrolledDateTime"})
    @Expose
	@Nullable
    public java.time.OffsetDateTime enrolledDateTime;

    /**
     * The Last Connection Date Time.
     * Last connection time for the Ndes Connector
     */
    @SerializedName(value = "lastConnectionDateTime", alternate = {"LastConnectionDateTime"})
    @Expose
	@Nullable
    public java.time.OffsetDateTime lastConnectionDateTime;

    /**
     * The Machine Name.
     * Name of the machine running on-prem certificate connector service.
     */
    @SerializedName(value = "machineName", alternate = {"MachineName"})
    @Expose
	@Nullable
    public String machineName;

    /**
     * The Role Scope Tag Ids.
     * List of Scope Tags for this Entity instance.
     */
    @SerializedName(value = "roleScopeTagIds", alternate = {"RoleScopeTagIds"})
    @Expose
	@Nullable
    public java.util.List<String> roleScopeTagIds;

    /**
     * The State.
     * Ndes Connector Status. Possible values are: none, active, inactive.
     */
    @SerializedName(value = "state", alternate = {"State"})
    @Expose
	@Nullable
    public NdesConnectorState state;


    /**
     * Sets the raw JSON object
     *
     * @param serializer the serializer
     * @param json the JSON object to set this object to
     */
    public void setRawObject(@Nonnull final ISerializer serializer, @Nonnull final JsonObject json) {

    }
}
