// Template Source: BaseEntity.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.models;
import com.microsoft.graph.serializer.ISerializer;
import com.microsoft.graph.serializer.IJsonBackedObject;
import com.microsoft.graph.serializer.AdditionalDataManager;
import java.util.EnumSet;
import com.microsoft.graph.http.BaseCollectionPage;
import com.microsoft.graph.models.TeamworkDeviceActivityState;
import com.microsoft.graph.models.IdentitySet;
import com.microsoft.graph.models.TeamworkUserIdentity;
import com.microsoft.graph.models.TeamworkDeviceType;
import com.microsoft.graph.models.TeamworkHardwareDetail;
import com.microsoft.graph.models.TeamworkDeviceHealthStatus;
import com.microsoft.graph.models.TeamworkDeviceActivity;
import com.microsoft.graph.models.TeamworkDeviceConfiguration;
import com.microsoft.graph.models.TeamworkDeviceHealth;
import com.microsoft.graph.models.TeamworkDeviceOperation;
import com.microsoft.graph.models.Entity;
import com.microsoft.graph.requests.TeamworkDeviceOperationCollectionPage;


import com.google.gson.JsonObject;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import javax.annotation.Nullable;
import javax.annotation.Nonnull;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Teamwork Device.
 */
public class TeamworkDevice extends Entity implements IJsonBackedObject {


    /**
     * The Activity State.
     * 
     */
    @SerializedName(value = "activityState", alternate = {"ActivityState"})
    @Expose
	@Nullable
    public TeamworkDeviceActivityState activityState;

    /**
     * The Company Asset Tag.
     * 
     */
    @SerializedName(value = "companyAssetTag", alternate = {"CompanyAssetTag"})
    @Expose
	@Nullable
    public String companyAssetTag;

    /**
     * The Created By.
     * 
     */
    @SerializedName(value = "createdBy", alternate = {"CreatedBy"})
    @Expose
	@Nullable
    public IdentitySet createdBy;

    /**
     * The Created Date Time.
     * 
     */
    @SerializedName(value = "createdDateTime", alternate = {"CreatedDateTime"})
    @Expose
	@Nullable
    public java.time.OffsetDateTime createdDateTime;

    /**
     * The Current User.
     * 
     */
    @SerializedName(value = "currentUser", alternate = {"CurrentUser"})
    @Expose
	@Nullable
    public TeamworkUserIdentity currentUser;

    /**
     * The Device Type.
     * 
     */
    @SerializedName(value = "deviceType", alternate = {"DeviceType"})
    @Expose
	@Nullable
    public TeamworkDeviceType deviceType;

    /**
     * The Hardware Detail.
     * 
     */
    @SerializedName(value = "hardwareDetail", alternate = {"HardwareDetail"})
    @Expose
	@Nullable
    public TeamworkHardwareDetail hardwareDetail;

    /**
     * The Health Status.
     * 
     */
    @SerializedName(value = "healthStatus", alternate = {"HealthStatus"})
    @Expose
	@Nullable
    public TeamworkDeviceHealthStatus healthStatus;

    /**
     * The Last Modified By.
     * 
     */
    @SerializedName(value = "lastModifiedBy", alternate = {"LastModifiedBy"})
    @Expose
	@Nullable
    public IdentitySet lastModifiedBy;

    /**
     * The Last Modified Date Time.
     * 
     */
    @SerializedName(value = "lastModifiedDateTime", alternate = {"LastModifiedDateTime"})
    @Expose
	@Nullable
    public java.time.OffsetDateTime lastModifiedDateTime;

    /**
     * The Notes.
     * 
     */
    @SerializedName(value = "notes", alternate = {"Notes"})
    @Expose
	@Nullable
    public String notes;

    /**
     * The Activity.
     * 
     */
    @SerializedName(value = "activity", alternate = {"Activity"})
    @Expose
	@Nullable
    public TeamworkDeviceActivity activity;

    /**
     * The Configuration.
     * 
     */
    @SerializedName(value = "configuration", alternate = {"Configuration"})
    @Expose
	@Nullable
    public TeamworkDeviceConfiguration configuration;

    /**
     * The Health.
     * 
     */
    @SerializedName(value = "health", alternate = {"Health"})
    @Expose
	@Nullable
    public TeamworkDeviceHealth health;

    /**
     * The Operations.
     * 
     */
    @SerializedName(value = "operations", alternate = {"Operations"})
    @Expose
	@Nullable
    public TeamworkDeviceOperationCollectionPage operations;


    /**
     * Sets the raw JSON object
     *
     * @param serializer the serializer
     * @param json the JSON object to set this object to
     */
    public void setRawObject(@Nonnull final ISerializer serializer, @Nonnull final JsonObject json) {


        if (json.has("operations")) {
            operations = serializer.deserializeObject(json.get("operations"), TeamworkDeviceOperationCollectionPage.class);
        }
    }
}
