// Template Source: BaseEntity.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.models;
import com.microsoft.graph.serializer.ISerializer;
import com.microsoft.graph.serializer.IJsonBackedObject;
import com.microsoft.graph.serializer.AdditionalDataManager;
import java.util.EnumSet;
import com.microsoft.graph.models.Entity;


import com.google.gson.JsonObject;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import javax.annotation.Nullable;
import javax.annotation.Nonnull;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Zebra Fota Artifact.
 */
public class ZebraFotaArtifact extends Entity implements IJsonBackedObject {


    /**
     * The Board Support Package Version.
     * The version of the Board Support Package.
     */
    @SerializedName(value = "boardSupportPackageVersion", alternate = {"BoardSupportPackageVersion"})
    @Expose
	@Nullable
    public String boardSupportPackageVersion;

    /**
     * The Device Model.
     * Artifact device model.
     */
    @SerializedName(value = "deviceModel", alternate = {"DeviceModel"})
    @Expose
	@Nullable
    public String deviceModel;

    /**
     * The Os Version.
     * Artifact OS version.
     */
    @SerializedName(value = "osVersion", alternate = {"OsVersion"})
    @Expose
	@Nullable
    public String osVersion;

    /**
     * The Patch Version.
     * Artifact patch version.
     */
    @SerializedName(value = "patchVersion", alternate = {"PatchVersion"})
    @Expose
	@Nullable
    public String patchVersion;

    /**
     * The Release Notes Url.
     * Artifact release notes URL.
     */
    @SerializedName(value = "releaseNotesUrl", alternate = {"ReleaseNotesUrl"})
    @Expose
	@Nullable
    public String releaseNotesUrl;


    /**
     * Sets the raw JSON object
     *
     * @param serializer the serializer
     * @param json the JSON object to set this object to
     */
    public void setRawObject(@Nonnull final ISerializer serializer, @Nonnull final JsonObject json) {

    }
}
