// Template Source: BaseEntityRequestBuilder.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.models.AndroidForWorkSettings;
import java.util.Arrays;
import java.util.EnumSet;
import javax.annotation.Nullable;
import javax.annotation.Nonnull;
import com.microsoft.graph.core.IBaseClient;
import com.microsoft.graph.http.BaseRequestBuilder;
import com.microsoft.graph.models.AndroidForWorkSettingsCompleteSignupParameterSet;
import com.microsoft.graph.models.AndroidForWorkSettingsRequestSignupUrlParameterSet;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Android For Work Settings Request Builder.
 */
public class AndroidForWorkSettingsRequestBuilder extends BaseRequestBuilder<AndroidForWorkSettings> {

    /**
     * The request builder for the AndroidForWorkSettings
     *
     * @param requestUrl     the request URL
     * @param client         the service client
     * @param requestOptions the options for this request
     */
    public AndroidForWorkSettingsRequestBuilder(@Nonnull final String requestUrl, @Nonnull final IBaseClient<?> client, @Nullable final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        super(requestUrl, client, requestOptions);
    }

    /**
     * Creates the request
     *
     * @param requestOptions the options for this request
     * @return the AndroidForWorkSettingsRequest instance
     */
    @Nonnull
    public AndroidForWorkSettingsRequest buildRequest(@Nullable final com.microsoft.graph.options.Option... requestOptions) {
        return buildRequest(getOptions(requestOptions));
    }

    /**
     * Creates the request with specific requestOptions instead of the existing requestOptions
     *
     * @param requestOptions the options for this request
     * @return the AndroidForWorkSettingsRequest instance
     */
    @Nonnull
    public AndroidForWorkSettingsRequest buildRequest(@Nonnull final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        return new com.microsoft.graph.requests.AndroidForWorkSettingsRequest(getRequestUrl(), getClient(), requestOptions);
    }



    /**
     * Gets a builder to execute the method
     * @return the request builder
     * @param parameters the parameters for the service method
     */
    @Nonnull
    public AndroidForWorkSettingsCompleteSignupRequestBuilder completeSignup(@Nonnull final AndroidForWorkSettingsCompleteSignupParameterSet parameters) {
        return new AndroidForWorkSettingsCompleteSignupRequestBuilder(getRequestUrlWithAdditionalSegment("microsoft.graph.completeSignup"), getClient(), null, parameters);
    }

    /**
     * Gets a builder to execute the method
     * @return the request builder
     * @param parameters the parameters for the service method
     */
    @Nonnull
    public AndroidForWorkSettingsRequestSignupUrlRequestBuilder requestSignupUrl(@Nonnull final AndroidForWorkSettingsRequestSignupUrlParameterSet parameters) {
        return new AndroidForWorkSettingsRequestSignupUrlRequestBuilder(getRequestUrlWithAdditionalSegment("microsoft.graph.requestSignupUrl"), getClient(), null, parameters);
    }

    /**
     * Gets a builder to execute the method
     * @return the request builder
     */
    @Nonnull
    public AndroidForWorkSettingsSyncAppsRequestBuilder syncApps() {
        return new AndroidForWorkSettingsSyncAppsRequestBuilder(getRequestUrlWithAdditionalSegment("microsoft.graph.syncApps"), getClient(), null);
    }

    /**
     * Gets a builder to execute the method
     * @return the request builder
     */
    @Nonnull
    public AndroidForWorkSettingsUnbindRequestBuilder unbind() {
        return new AndroidForWorkSettingsUnbindRequestBuilder(getRequestUrlWithAdditionalSegment("microsoft.graph.unbind"), getClient(), null);
    }
}
