// Template Source: BaseEntityRequest.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.models.AndroidWorkProfilePkcsCertificateProfile;
import com.microsoft.graph.models.DeviceConfigurationGroupAssignment;
import com.microsoft.graph.models.DeviceConfigurationAssignment;
import com.microsoft.graph.models.HasPayloadLinkResultItem;
import com.microsoft.graph.models.DeviceConfigurationTargetedUserAndDevice;
import com.microsoft.graph.models.WindowsAssignedAccessProfile;
import com.microsoft.graph.models.WindowsPrivacyDataAccessControlItem;
import com.microsoft.graph.models.IosAvailableUpdateVersion;
import com.microsoft.graph.requests.ManagedDeviceCertificateStateCollectionRequestBuilder;
import com.microsoft.graph.requests.ManagedDeviceCertificateStateRequestBuilder;
import java.util.Arrays;
import java.util.EnumSet;
import javax.annotation.Nullable;
import javax.annotation.Nonnull;
import com.microsoft.graph.core.IBaseClient;
import com.microsoft.graph.http.BaseRequest;
import com.microsoft.graph.http.HttpMethod;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Android Work Profile Pkcs Certificate Profile Request.
 */
public class AndroidWorkProfilePkcsCertificateProfileRequest extends BaseRequest<AndroidWorkProfilePkcsCertificateProfile> {
	
    /**
     * The request for the AndroidWorkProfilePkcsCertificateProfile
     *
     * @param requestUrl     the request URL
     * @param client         the service client
     * @param requestOptions the options for this request
     */
    public AndroidWorkProfilePkcsCertificateProfileRequest(@Nonnull final String requestUrl, @Nonnull final IBaseClient<?> client, @Nullable final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        super(requestUrl, client, requestOptions, AndroidWorkProfilePkcsCertificateProfile.class);
    }

    /**
     * Gets the AndroidWorkProfilePkcsCertificateProfile from the service
     *
     * @return a future with the result
     */
    @Nonnull
    public java.util.concurrent.CompletableFuture<AndroidWorkProfilePkcsCertificateProfile> getAsync() {
        return sendAsync(HttpMethod.GET, null);
    }

    /**
     * Gets the AndroidWorkProfilePkcsCertificateProfile from the service
     *
     * @return the AndroidWorkProfilePkcsCertificateProfile from the request
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public AndroidWorkProfilePkcsCertificateProfile get() throws ClientException {
       return send(HttpMethod.GET, null);
    }

    /**
     * Delete this item from the service
     *
     * @return a future with the deletion result
     */
    @Nonnull
    public java.util.concurrent.CompletableFuture<AndroidWorkProfilePkcsCertificateProfile> deleteAsync() {
        return sendAsync(HttpMethod.DELETE, null);
    }

    /**
     * Delete this item from the service
     * @return the resulting response if the service returns anything on deletion
     *
     * @throws ClientException if there was an exception during the delete operation
     */
    @Nullable
    public AndroidWorkProfilePkcsCertificateProfile delete() throws ClientException {
        return send(HttpMethod.DELETE, null);
    }

    /**
     * Patches this AndroidWorkProfilePkcsCertificateProfile with a source
     *
     * @param sourceAndroidWorkProfilePkcsCertificateProfile the source object with updates
     * @return a future with the result
     */
    @Nonnull
    public java.util.concurrent.CompletableFuture<AndroidWorkProfilePkcsCertificateProfile> patchAsync(@Nonnull final AndroidWorkProfilePkcsCertificateProfile sourceAndroidWorkProfilePkcsCertificateProfile) {
        return sendAsync(HttpMethod.PATCH, sourceAndroidWorkProfilePkcsCertificateProfile);
    }

    /**
     * Patches this AndroidWorkProfilePkcsCertificateProfile with a source
     *
     * @param sourceAndroidWorkProfilePkcsCertificateProfile the source object with updates
     * @return the updated AndroidWorkProfilePkcsCertificateProfile
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public AndroidWorkProfilePkcsCertificateProfile patch(@Nonnull final AndroidWorkProfilePkcsCertificateProfile sourceAndroidWorkProfilePkcsCertificateProfile) throws ClientException {
        return send(HttpMethod.PATCH, sourceAndroidWorkProfilePkcsCertificateProfile);
    }

    /**
     * Creates a AndroidWorkProfilePkcsCertificateProfile with a new object
     *
     * @param newAndroidWorkProfilePkcsCertificateProfile the new object to create
     * @return a future with the result
     */
    @Nonnull
    public java.util.concurrent.CompletableFuture<AndroidWorkProfilePkcsCertificateProfile> postAsync(@Nonnull final AndroidWorkProfilePkcsCertificateProfile newAndroidWorkProfilePkcsCertificateProfile) {
        return sendAsync(HttpMethod.POST, newAndroidWorkProfilePkcsCertificateProfile);
    }

    /**
     * Creates a AndroidWorkProfilePkcsCertificateProfile with a new object
     *
     * @param newAndroidWorkProfilePkcsCertificateProfile the new object to create
     * @return the created AndroidWorkProfilePkcsCertificateProfile
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public AndroidWorkProfilePkcsCertificateProfile post(@Nonnull final AndroidWorkProfilePkcsCertificateProfile newAndroidWorkProfilePkcsCertificateProfile) throws ClientException {
        return send(HttpMethod.POST, newAndroidWorkProfilePkcsCertificateProfile);
    }

    /**
     * Creates a AndroidWorkProfilePkcsCertificateProfile with a new object
     *
     * @param newAndroidWorkProfilePkcsCertificateProfile the object to create/update
     * @return a future with the result
     */
    @Nonnull
    public java.util.concurrent.CompletableFuture<AndroidWorkProfilePkcsCertificateProfile> putAsync(@Nonnull final AndroidWorkProfilePkcsCertificateProfile newAndroidWorkProfilePkcsCertificateProfile) {
        return sendAsync(HttpMethod.PUT, newAndroidWorkProfilePkcsCertificateProfile);
    }

    /**
     * Creates a AndroidWorkProfilePkcsCertificateProfile with a new object
     *
     * @param newAndroidWorkProfilePkcsCertificateProfile the object to create/update
     * @return the created AndroidWorkProfilePkcsCertificateProfile
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public AndroidWorkProfilePkcsCertificateProfile put(@Nonnull final AndroidWorkProfilePkcsCertificateProfile newAndroidWorkProfilePkcsCertificateProfile) throws ClientException {
        return send(HttpMethod.PUT, newAndroidWorkProfilePkcsCertificateProfile);
    }

    /**
     * Sets the select clause for the request
     *
     * @param value the select clause
     * @return the updated request
     */
     @Nonnull
     public AndroidWorkProfilePkcsCertificateProfileRequest select(@Nonnull final String value) {
         addSelectOption(value);
         return this;
     }

    /**
     * Sets the expand clause for the request
     *
     * @param value the expand clause
     * @return the updated request
     */
     @Nonnull
     public AndroidWorkProfilePkcsCertificateProfileRequest expand(@Nonnull final String value) {
         addExpandOption(value);
         return this;
     }

}

