// Template Source: BaseEntityRequest.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.models.AppleVpnConfiguration;
import com.microsoft.graph.models.DeviceConfigurationGroupAssignment;
import com.microsoft.graph.models.DeviceConfigurationAssignment;
import com.microsoft.graph.models.HasPayloadLinkResultItem;
import com.microsoft.graph.models.DeviceConfigurationTargetedUserAndDevice;
import com.microsoft.graph.models.WindowsAssignedAccessProfile;
import com.microsoft.graph.models.WindowsPrivacyDataAccessControlItem;
import com.microsoft.graph.models.IosAvailableUpdateVersion;
import java.util.Arrays;
import java.util.EnumSet;
import javax.annotation.Nullable;
import javax.annotation.Nonnull;
import com.microsoft.graph.core.IBaseClient;
import com.microsoft.graph.http.BaseRequest;
import com.microsoft.graph.http.HttpMethod;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Apple Vpn Configuration Request.
 */
public class AppleVpnConfigurationRequest extends BaseRequest<AppleVpnConfiguration> {
	
    /**
     * The request for the AppleVpnConfiguration
     *
     * @param requestUrl     the request URL
     * @param client         the service client
     * @param requestOptions the options for this request
     * @param responseClass  the class of the response
     */
    public AppleVpnConfigurationRequest(@Nonnull final String requestUrl,
            @Nonnull final IBaseClient<?> client,
            @Nullable final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions,
            @Nonnull final Class<? extends AppleVpnConfiguration> responseClass) {
        super(requestUrl, client, requestOptions, responseClass);
    }

    /**
     * The request for the AppleVpnConfiguration
     *
     * @param requestUrl     the request URL
     * @param client         the service client
     * @param requestOptions the options for this request
     */
    public AppleVpnConfigurationRequest(@Nonnull final String requestUrl, @Nonnull final IBaseClient<?> client, @Nullable final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        super(requestUrl, client, requestOptions, AppleVpnConfiguration.class);
    }

    /**
     * Gets the AppleVpnConfiguration from the service
     *
     * @return a future with the result
     */
    @Nonnull
    public java.util.concurrent.CompletableFuture<AppleVpnConfiguration> getAsync() {
        return sendAsync(HttpMethod.GET, null);
    }

    /**
     * Gets the AppleVpnConfiguration from the service
     *
     * @return the AppleVpnConfiguration from the request
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public AppleVpnConfiguration get() throws ClientException {
       return send(HttpMethod.GET, null);
    }

    /**
     * Delete this item from the service
     *
     * @return a future with the deletion result
     */
    @Nonnull
    public java.util.concurrent.CompletableFuture<AppleVpnConfiguration> deleteAsync() {
        return sendAsync(HttpMethod.DELETE, null);
    }

    /**
     * Delete this item from the service
     * @return the resulting response if the service returns anything on deletion
     *
     * @throws ClientException if there was an exception during the delete operation
     */
    @Nullable
    public AppleVpnConfiguration delete() throws ClientException {
        return send(HttpMethod.DELETE, null);
    }

    /**
     * Patches this AppleVpnConfiguration with a source
     *
     * @param sourceAppleVpnConfiguration the source object with updates
     * @return a future with the result
     */
    @Nonnull
    public java.util.concurrent.CompletableFuture<AppleVpnConfiguration> patchAsync(@Nonnull final AppleVpnConfiguration sourceAppleVpnConfiguration) {
        return sendAsync(HttpMethod.PATCH, sourceAppleVpnConfiguration);
    }

    /**
     * Patches this AppleVpnConfiguration with a source
     *
     * @param sourceAppleVpnConfiguration the source object with updates
     * @return the updated AppleVpnConfiguration
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public AppleVpnConfiguration patch(@Nonnull final AppleVpnConfiguration sourceAppleVpnConfiguration) throws ClientException {
        return send(HttpMethod.PATCH, sourceAppleVpnConfiguration);
    }

    /**
     * Creates a AppleVpnConfiguration with a new object
     *
     * @param newAppleVpnConfiguration the new object to create
     * @return a future with the result
     */
    @Nonnull
    public java.util.concurrent.CompletableFuture<AppleVpnConfiguration> postAsync(@Nonnull final AppleVpnConfiguration newAppleVpnConfiguration) {
        return sendAsync(HttpMethod.POST, newAppleVpnConfiguration);
    }

    /**
     * Creates a AppleVpnConfiguration with a new object
     *
     * @param newAppleVpnConfiguration the new object to create
     * @return the created AppleVpnConfiguration
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public AppleVpnConfiguration post(@Nonnull final AppleVpnConfiguration newAppleVpnConfiguration) throws ClientException {
        return send(HttpMethod.POST, newAppleVpnConfiguration);
    }

    /**
     * Creates a AppleVpnConfiguration with a new object
     *
     * @param newAppleVpnConfiguration the object to create/update
     * @return a future with the result
     */
    @Nonnull
    public java.util.concurrent.CompletableFuture<AppleVpnConfiguration> putAsync(@Nonnull final AppleVpnConfiguration newAppleVpnConfiguration) {
        return sendAsync(HttpMethod.PUT, newAppleVpnConfiguration);
    }

    /**
     * Creates a AppleVpnConfiguration with a new object
     *
     * @param newAppleVpnConfiguration the object to create/update
     * @return the created AppleVpnConfiguration
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public AppleVpnConfiguration put(@Nonnull final AppleVpnConfiguration newAppleVpnConfiguration) throws ClientException {
        return send(HttpMethod.PUT, newAppleVpnConfiguration);
    }

    /**
     * Sets the select clause for the request
     *
     * @param value the select clause
     * @return the updated request
     */
     @Nonnull
     public AppleVpnConfigurationRequest select(@Nonnull final String value) {
         addSelectOption(value);
         return this;
     }

    /**
     * Sets the expand clause for the request
     *
     * @param value the expand clause
     * @return the updated request
     */
     @Nonnull
     public AppleVpnConfigurationRequest expand(@Nonnull final String value) {
         addExpandOption(value);
         return this;
     }

}

