// Template Source: BaseEntityRequest.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.models.AzureAuthorizationSystemTypeAction;
import java.util.Arrays;
import java.util.EnumSet;
import javax.annotation.Nullable;
import javax.annotation.Nonnull;
import com.microsoft.graph.core.IBaseClient;
import com.microsoft.graph.http.BaseRequest;
import com.microsoft.graph.http.HttpMethod;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Azure Authorization System Type Action Request.
 */
public class AzureAuthorizationSystemTypeActionRequest extends BaseRequest<AzureAuthorizationSystemTypeAction> {
	
    /**
     * The request for the AzureAuthorizationSystemTypeAction
     *
     * @param requestUrl     the request URL
     * @param client         the service client
     * @param requestOptions the options for this request
     */
    public AzureAuthorizationSystemTypeActionRequest(@Nonnull final String requestUrl, @Nonnull final IBaseClient<?> client, @Nullable final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        super(requestUrl, client, requestOptions, AzureAuthorizationSystemTypeAction.class);
    }

    /**
     * Gets the AzureAuthorizationSystemTypeAction from the service
     *
     * @return a future with the result
     */
    @Nonnull
    public java.util.concurrent.CompletableFuture<AzureAuthorizationSystemTypeAction> getAsync() {
        return sendAsync(HttpMethod.GET, null);
    }

    /**
     * Gets the AzureAuthorizationSystemTypeAction from the service
     *
     * @return the AzureAuthorizationSystemTypeAction from the request
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public AzureAuthorizationSystemTypeAction get() throws ClientException {
       return send(HttpMethod.GET, null);
    }

    /**
     * Delete this item from the service
     *
     * @return a future with the deletion result
     */
    @Nonnull
    public java.util.concurrent.CompletableFuture<AzureAuthorizationSystemTypeAction> deleteAsync() {
        return sendAsync(HttpMethod.DELETE, null);
    }

    /**
     * Delete this item from the service
     * @return the resulting response if the service returns anything on deletion
     *
     * @throws ClientException if there was an exception during the delete operation
     */
    @Nullable
    public AzureAuthorizationSystemTypeAction delete() throws ClientException {
        return send(HttpMethod.DELETE, null);
    }

    /**
     * Patches this AzureAuthorizationSystemTypeAction with a source
     *
     * @param sourceAzureAuthorizationSystemTypeAction the source object with updates
     * @return a future with the result
     */
    @Nonnull
    public java.util.concurrent.CompletableFuture<AzureAuthorizationSystemTypeAction> patchAsync(@Nonnull final AzureAuthorizationSystemTypeAction sourceAzureAuthorizationSystemTypeAction) {
        return sendAsync(HttpMethod.PATCH, sourceAzureAuthorizationSystemTypeAction);
    }

    /**
     * Patches this AzureAuthorizationSystemTypeAction with a source
     *
     * @param sourceAzureAuthorizationSystemTypeAction the source object with updates
     * @return the updated AzureAuthorizationSystemTypeAction
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public AzureAuthorizationSystemTypeAction patch(@Nonnull final AzureAuthorizationSystemTypeAction sourceAzureAuthorizationSystemTypeAction) throws ClientException {
        return send(HttpMethod.PATCH, sourceAzureAuthorizationSystemTypeAction);
    }

    /**
     * Creates a AzureAuthorizationSystemTypeAction with a new object
     *
     * @param newAzureAuthorizationSystemTypeAction the new object to create
     * @return a future with the result
     */
    @Nonnull
    public java.util.concurrent.CompletableFuture<AzureAuthorizationSystemTypeAction> postAsync(@Nonnull final AzureAuthorizationSystemTypeAction newAzureAuthorizationSystemTypeAction) {
        return sendAsync(HttpMethod.POST, newAzureAuthorizationSystemTypeAction);
    }

    /**
     * Creates a AzureAuthorizationSystemTypeAction with a new object
     *
     * @param newAzureAuthorizationSystemTypeAction the new object to create
     * @return the created AzureAuthorizationSystemTypeAction
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public AzureAuthorizationSystemTypeAction post(@Nonnull final AzureAuthorizationSystemTypeAction newAzureAuthorizationSystemTypeAction) throws ClientException {
        return send(HttpMethod.POST, newAzureAuthorizationSystemTypeAction);
    }

    /**
     * Creates a AzureAuthorizationSystemTypeAction with a new object
     *
     * @param newAzureAuthorizationSystemTypeAction the object to create/update
     * @return a future with the result
     */
    @Nonnull
    public java.util.concurrent.CompletableFuture<AzureAuthorizationSystemTypeAction> putAsync(@Nonnull final AzureAuthorizationSystemTypeAction newAzureAuthorizationSystemTypeAction) {
        return sendAsync(HttpMethod.PUT, newAzureAuthorizationSystemTypeAction);
    }

    /**
     * Creates a AzureAuthorizationSystemTypeAction with a new object
     *
     * @param newAzureAuthorizationSystemTypeAction the object to create/update
     * @return the created AzureAuthorizationSystemTypeAction
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public AzureAuthorizationSystemTypeAction put(@Nonnull final AzureAuthorizationSystemTypeAction newAzureAuthorizationSystemTypeAction) throws ClientException {
        return send(HttpMethod.PUT, newAzureAuthorizationSystemTypeAction);
    }

    /**
     * Sets the select clause for the request
     *
     * @param value the select clause
     * @return the updated request
     */
     @Nonnull
     public AzureAuthorizationSystemTypeActionRequest select(@Nonnull final String value) {
         addSelectOption(value);
         return this;
     }

    /**
     * Sets the expand clause for the request
     *
     * @param value the expand clause
     * @return the updated request
     */
     @Nonnull
     public AzureAuthorizationSystemTypeActionRequest expand(@Nonnull final String value) {
         addExpandOption(value);
         return this;
     }

}

