// Template Source: BaseEntityRequestBuilder.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.models.Company;
import java.util.Arrays;
import java.util.EnumSet;
import javax.annotation.Nullable;
import javax.annotation.Nonnull;
import com.microsoft.graph.core.IBaseClient;
import com.microsoft.graph.http.BaseRequestBuilder;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Company Request Builder.
 */
public class CompanyRequestBuilder extends BaseRequestBuilder<Company> {

    /**
     * The request builder for the Company
     *
     * @param requestUrl     the request URL
     * @param client         the service client
     * @param requestOptions the options for this request
     */
    public CompanyRequestBuilder(@Nonnull final String requestUrl, @Nonnull final IBaseClient<?> client, @Nullable final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        super(requestUrl, client, requestOptions);
    }

    /**
     * Creates the request
     *
     * @param requestOptions the options for this request
     * @return the CompanyRequest instance
     */
    @Nonnull
    public CompanyRequest buildRequest(@Nullable final com.microsoft.graph.options.Option... requestOptions) {
        return buildRequest(getOptions(requestOptions));
    }

    /**
     * Creates the request with specific requestOptions instead of the existing requestOptions
     *
     * @param requestOptions the options for this request
     * @return the CompanyRequest instance
     */
    @Nonnull
    public CompanyRequest buildRequest(@Nonnull final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        return new com.microsoft.graph.requests.CompanyRequest(getRequestUrl(), getClient(), requestOptions);
    }


    /**
     *  Gets a request builder for the Account collection
     *
     * @return the collection request builder
     */
    @Nonnull
    public com.microsoft.graph.requests.AccountCollectionRequestBuilder accounts() {
        return new com.microsoft.graph.requests.AccountCollectionRequestBuilder(getRequestUrlWithAdditionalSegment("accounts"), getClient(), null);
    }

    /**
     * Gets a request builder for the Account item
     *
     * @return the request builder
     * @param id the item identifier
     */
    @Nonnull
    public com.microsoft.graph.requests.AccountRequestBuilder accounts(@Nonnull final String id) {
        return new com.microsoft.graph.requests.AccountRequestBuilder(getRequestUrlWithAdditionalSegment("accounts") + "/" + id, getClient(), null);
    }
    /**
     *  Gets a request builder for the AgedAccountsPayable collection
     *
     * @return the collection request builder
     */
    @Nonnull
    public com.microsoft.graph.requests.AgedAccountsPayableCollectionRequestBuilder agedAccountsPayable() {
        return new com.microsoft.graph.requests.AgedAccountsPayableCollectionRequestBuilder(getRequestUrlWithAdditionalSegment("agedAccountsPayable"), getClient(), null);
    }

    /**
     * Gets a request builder for the AgedAccountsPayable item
     *
     * @return the request builder
     * @param id the item identifier
     */
    @Nonnull
    public com.microsoft.graph.requests.AgedAccountsPayableRequestBuilder agedAccountsPayable(@Nonnull final String id) {
        return new com.microsoft.graph.requests.AgedAccountsPayableRequestBuilder(getRequestUrlWithAdditionalSegment("agedAccountsPayable") + "/" + id, getClient(), null);
    }
    /**
     *  Gets a request builder for the AgedAccountsReceivable collection
     *
     * @return the collection request builder
     */
    @Nonnull
    public com.microsoft.graph.requests.AgedAccountsReceivableCollectionRequestBuilder agedAccountsReceivable() {
        return new com.microsoft.graph.requests.AgedAccountsReceivableCollectionRequestBuilder(getRequestUrlWithAdditionalSegment("agedAccountsReceivable"), getClient(), null);
    }

    /**
     * Gets a request builder for the AgedAccountsReceivable item
     *
     * @return the request builder
     * @param id the item identifier
     */
    @Nonnull
    public com.microsoft.graph.requests.AgedAccountsReceivableRequestBuilder agedAccountsReceivable(@Nonnull final String id) {
        return new com.microsoft.graph.requests.AgedAccountsReceivableRequestBuilder(getRequestUrlWithAdditionalSegment("agedAccountsReceivable") + "/" + id, getClient(), null);
    }
    /**
     *  Gets a request builder for the CompanyInformation collection
     *
     * @return the collection request builder
     */
    @Nonnull
    public com.microsoft.graph.requests.CompanyInformationCollectionRequestBuilder companyInformation() {
        return new com.microsoft.graph.requests.CompanyInformationCollectionRequestBuilder(getRequestUrlWithAdditionalSegment("companyInformation"), getClient(), null);
    }

    /**
     * Gets a request builder for the CompanyInformation item
     *
     * @return the request builder
     * @param id the item identifier
     */
    @Nonnull
    public com.microsoft.graph.requests.CompanyInformationRequestBuilder companyInformation(@Nonnull final String id) {
        return new com.microsoft.graph.requests.CompanyInformationRequestBuilder(getRequestUrlWithAdditionalSegment("companyInformation") + "/" + id, getClient(), null);
    }
    /**
     *  Gets a request builder for the CountryRegion collection
     *
     * @return the collection request builder
     */
    @Nonnull
    public com.microsoft.graph.requests.CountryRegionCollectionRequestBuilder countriesRegions() {
        return new com.microsoft.graph.requests.CountryRegionCollectionRequestBuilder(getRequestUrlWithAdditionalSegment("countriesRegions"), getClient(), null);
    }

    /**
     * Gets a request builder for the CountryRegion item
     *
     * @return the request builder
     * @param id the item identifier
     */
    @Nonnull
    public com.microsoft.graph.requests.CountryRegionRequestBuilder countriesRegions(@Nonnull final String id) {
        return new com.microsoft.graph.requests.CountryRegionRequestBuilder(getRequestUrlWithAdditionalSegment("countriesRegions") + "/" + id, getClient(), null);
    }
    /**
     *  Gets a request builder for the Currency collection
     *
     * @return the collection request builder
     */
    @Nonnull
    public com.microsoft.graph.requests.CurrencyCollectionRequestBuilder currencies() {
        return new com.microsoft.graph.requests.CurrencyCollectionRequestBuilder(getRequestUrlWithAdditionalSegment("currencies"), getClient(), null);
    }

    /**
     * Gets a request builder for the Currency item
     *
     * @return the request builder
     * @param id the item identifier
     */
    @Nonnull
    public com.microsoft.graph.requests.CurrencyRequestBuilder currencies(@Nonnull final String id) {
        return new com.microsoft.graph.requests.CurrencyRequestBuilder(getRequestUrlWithAdditionalSegment("currencies") + "/" + id, getClient(), null);
    }
    /**
     *  Gets a request builder for the CustomerPaymentJournal collection
     *
     * @return the collection request builder
     */
    @Nonnull
    public com.microsoft.graph.requests.CustomerPaymentJournalCollectionRequestBuilder customerPaymentJournals() {
        return new com.microsoft.graph.requests.CustomerPaymentJournalCollectionRequestBuilder(getRequestUrlWithAdditionalSegment("customerPaymentJournals"), getClient(), null);
    }

    /**
     * Gets a request builder for the CustomerPaymentJournal item
     *
     * @return the request builder
     * @param id the item identifier
     */
    @Nonnull
    public com.microsoft.graph.requests.CustomerPaymentJournalRequestBuilder customerPaymentJournals(@Nonnull final String id) {
        return new com.microsoft.graph.requests.CustomerPaymentJournalRequestBuilder(getRequestUrlWithAdditionalSegment("customerPaymentJournals") + "/" + id, getClient(), null);
    }
    /**
     *  Gets a request builder for the CustomerPayment collection
     *
     * @return the collection request builder
     */
    @Nonnull
    public com.microsoft.graph.requests.CustomerPaymentCollectionRequestBuilder customerPayments() {
        return new com.microsoft.graph.requests.CustomerPaymentCollectionRequestBuilder(getRequestUrlWithAdditionalSegment("customerPayments"), getClient(), null);
    }

    /**
     * Gets a request builder for the CustomerPayment item
     *
     * @return the request builder
     * @param id the item identifier
     */
    @Nonnull
    public com.microsoft.graph.requests.CustomerPaymentRequestBuilder customerPayments(@Nonnull final String id) {
        return new com.microsoft.graph.requests.CustomerPaymentRequestBuilder(getRequestUrlWithAdditionalSegment("customerPayments") + "/" + id, getClient(), null);
    }
    /**
     *  Gets a request builder for the Customer collection
     *
     * @return the collection request builder
     */
    @Nonnull
    public com.microsoft.graph.requests.CustomerCollectionRequestBuilder customers() {
        return new com.microsoft.graph.requests.CustomerCollectionRequestBuilder(getRequestUrlWithAdditionalSegment("customers"), getClient(), null);
    }

    /**
     * Gets a request builder for the Customer item
     *
     * @return the request builder
     * @param id the item identifier
     */
    @Nonnull
    public com.microsoft.graph.requests.CustomerRequestBuilder customers(@Nonnull final String id) {
        return new com.microsoft.graph.requests.CustomerRequestBuilder(getRequestUrlWithAdditionalSegment("customers") + "/" + id, getClient(), null);
    }
    /**
     *  Gets a request builder for the Dimension collection
     *
     * @return the collection request builder
     */
    @Nonnull
    public com.microsoft.graph.requests.DimensionCollectionRequestBuilder dimensions() {
        return new com.microsoft.graph.requests.DimensionCollectionRequestBuilder(getRequestUrlWithAdditionalSegment("dimensions"), getClient(), null);
    }

    /**
     * Gets a request builder for the Dimension item
     *
     * @return the request builder
     * @param id the item identifier
     */
    @Nonnull
    public com.microsoft.graph.requests.DimensionRequestBuilder dimensions(@Nonnull final String id) {
        return new com.microsoft.graph.requests.DimensionRequestBuilder(getRequestUrlWithAdditionalSegment("dimensions") + "/" + id, getClient(), null);
    }
    /**
     *  Gets a request builder for the DimensionValue collection
     *
     * @return the collection request builder
     */
    @Nonnull
    public com.microsoft.graph.requests.DimensionValueCollectionRequestBuilder dimensionValues() {
        return new com.microsoft.graph.requests.DimensionValueCollectionRequestBuilder(getRequestUrlWithAdditionalSegment("dimensionValues"), getClient(), null);
    }

    /**
     * Gets a request builder for the DimensionValue item
     *
     * @return the request builder
     * @param id the item identifier
     */
    @Nonnull
    public com.microsoft.graph.requests.DimensionValueRequestBuilder dimensionValues(@Nonnull final String id) {
        return new com.microsoft.graph.requests.DimensionValueRequestBuilder(getRequestUrlWithAdditionalSegment("dimensionValues") + "/" + id, getClient(), null);
    }
    /**
     *  Gets a request builder for the Employee collection
     *
     * @return the collection request builder
     */
    @Nonnull
    public com.microsoft.graph.requests.EmployeeCollectionRequestBuilder employees() {
        return new com.microsoft.graph.requests.EmployeeCollectionRequestBuilder(getRequestUrlWithAdditionalSegment("employees"), getClient(), null);
    }

    /**
     * Gets a request builder for the Employee item
     *
     * @return the request builder
     * @param id the item identifier
     */
    @Nonnull
    public com.microsoft.graph.requests.EmployeeRequestBuilder employees(@Nonnull final String id) {
        return new com.microsoft.graph.requests.EmployeeRequestBuilder(getRequestUrlWithAdditionalSegment("employees") + "/" + id, getClient(), null);
    }
    /**
     *  Gets a request builder for the GeneralLedgerEntry collection
     *
     * @return the collection request builder
     */
    @Nonnull
    public com.microsoft.graph.requests.GeneralLedgerEntryCollectionRequestBuilder generalLedgerEntries() {
        return new com.microsoft.graph.requests.GeneralLedgerEntryCollectionRequestBuilder(getRequestUrlWithAdditionalSegment("generalLedgerEntries"), getClient(), null);
    }

    /**
     * Gets a request builder for the GeneralLedgerEntry item
     *
     * @return the request builder
     * @param id the item identifier
     */
    @Nonnull
    public com.microsoft.graph.requests.GeneralLedgerEntryRequestBuilder generalLedgerEntries(@Nonnull final String id) {
        return new com.microsoft.graph.requests.GeneralLedgerEntryRequestBuilder(getRequestUrlWithAdditionalSegment("generalLedgerEntries") + "/" + id, getClient(), null);
    }
    /**
     *  Gets a request builder for the ItemCategory collection
     *
     * @return the collection request builder
     */
    @Nonnull
    public com.microsoft.graph.requests.ItemCategoryCollectionRequestBuilder itemCategories() {
        return new com.microsoft.graph.requests.ItemCategoryCollectionRequestBuilder(getRequestUrlWithAdditionalSegment("itemCategories"), getClient(), null);
    }

    /**
     * Gets a request builder for the ItemCategory item
     *
     * @return the request builder
     * @param id the item identifier
     */
    @Nonnull
    public com.microsoft.graph.requests.ItemCategoryRequestBuilder itemCategories(@Nonnull final String id) {
        return new com.microsoft.graph.requests.ItemCategoryRequestBuilder(getRequestUrlWithAdditionalSegment("itemCategories") + "/" + id, getClient(), null);
    }
    /**
     *  Gets a request builder for the Item collection
     *
     * @return the collection request builder
     */
    @Nonnull
    public com.microsoft.graph.requests.ItemCollectionRequestBuilder items() {
        return new com.microsoft.graph.requests.ItemCollectionRequestBuilder(getRequestUrlWithAdditionalSegment("items"), getClient(), null);
    }

    /**
     * Gets a request builder for the Item item
     *
     * @return the request builder
     * @param id the item identifier
     */
    @Nonnull
    public com.microsoft.graph.requests.ItemRequestBuilder items(@Nonnull final String id) {
        return new com.microsoft.graph.requests.ItemRequestBuilder(getRequestUrlWithAdditionalSegment("items") + "/" + id, getClient(), null);
    }
    /**
     *  Gets a request builder for the JournalLine collection
     *
     * @return the collection request builder
     */
    @Nonnull
    public com.microsoft.graph.requests.JournalLineCollectionRequestBuilder journalLines() {
        return new com.microsoft.graph.requests.JournalLineCollectionRequestBuilder(getRequestUrlWithAdditionalSegment("journalLines"), getClient(), null);
    }

    /**
     * Gets a request builder for the JournalLine item
     *
     * @return the request builder
     * @param id the item identifier
     */
    @Nonnull
    public com.microsoft.graph.requests.JournalLineRequestBuilder journalLines(@Nonnull final String id) {
        return new com.microsoft.graph.requests.JournalLineRequestBuilder(getRequestUrlWithAdditionalSegment("journalLines") + "/" + id, getClient(), null);
    }
    /**
     *  Gets a request builder for the Journal collection
     *
     * @return the collection request builder
     */
    @Nonnull
    public com.microsoft.graph.requests.JournalCollectionRequestBuilder journals() {
        return new com.microsoft.graph.requests.JournalCollectionRequestBuilder(getRequestUrlWithAdditionalSegment("journals"), getClient(), null);
    }

    /**
     * Gets a request builder for the Journal item
     *
     * @return the request builder
     * @param id the item identifier
     */
    @Nonnull
    public com.microsoft.graph.requests.JournalRequestBuilder journals(@Nonnull final String id) {
        return new com.microsoft.graph.requests.JournalRequestBuilder(getRequestUrlWithAdditionalSegment("journals") + "/" + id, getClient(), null);
    }
    /**
     *  Gets a request builder for the PaymentMethod collection
     *
     * @return the collection request builder
     */
    @Nonnull
    public com.microsoft.graph.requests.PaymentMethodCollectionRequestBuilder paymentMethods() {
        return new com.microsoft.graph.requests.PaymentMethodCollectionRequestBuilder(getRequestUrlWithAdditionalSegment("paymentMethods"), getClient(), null);
    }

    /**
     * Gets a request builder for the PaymentMethod item
     *
     * @return the request builder
     * @param id the item identifier
     */
    @Nonnull
    public com.microsoft.graph.requests.PaymentMethodRequestBuilder paymentMethods(@Nonnull final String id) {
        return new com.microsoft.graph.requests.PaymentMethodRequestBuilder(getRequestUrlWithAdditionalSegment("paymentMethods") + "/" + id, getClient(), null);
    }
    /**
     *  Gets a request builder for the PaymentTerm collection
     *
     * @return the collection request builder
     */
    @Nonnull
    public com.microsoft.graph.requests.PaymentTermCollectionRequestBuilder paymentTerms() {
        return new com.microsoft.graph.requests.PaymentTermCollectionRequestBuilder(getRequestUrlWithAdditionalSegment("paymentTerms"), getClient(), null);
    }

    /**
     * Gets a request builder for the PaymentTerm item
     *
     * @return the request builder
     * @param id the item identifier
     */
    @Nonnull
    public com.microsoft.graph.requests.PaymentTermRequestBuilder paymentTerms(@Nonnull final String id) {
        return new com.microsoft.graph.requests.PaymentTermRequestBuilder(getRequestUrlWithAdditionalSegment("paymentTerms") + "/" + id, getClient(), null);
    }
    /**
     *  Gets a request builder for the Picture collection
     *
     * @return the collection request builder
     */
    @Nonnull
    public com.microsoft.graph.requests.PictureCollectionRequestBuilder picture() {
        return new com.microsoft.graph.requests.PictureCollectionRequestBuilder(getRequestUrlWithAdditionalSegment("picture"), getClient(), null);
    }

    /**
     * Gets a request builder for the Picture item
     *
     * @return the request builder
     * @param id the item identifier
     */
    @Nonnull
    public com.microsoft.graph.requests.PictureRequestBuilder picture(@Nonnull final String id) {
        return new com.microsoft.graph.requests.PictureRequestBuilder(getRequestUrlWithAdditionalSegment("picture") + "/" + id, getClient(), null);
    }
    /**
     *  Gets a request builder for the PurchaseInvoiceLine collection
     *
     * @return the collection request builder
     */
    @Nonnull
    public com.microsoft.graph.requests.PurchaseInvoiceLineCollectionRequestBuilder purchaseInvoiceLines() {
        return new com.microsoft.graph.requests.PurchaseInvoiceLineCollectionRequestBuilder(getRequestUrlWithAdditionalSegment("purchaseInvoiceLines"), getClient(), null);
    }

    /**
     * Gets a request builder for the PurchaseInvoiceLine item
     *
     * @return the request builder
     * @param id the item identifier
     */
    @Nonnull
    public com.microsoft.graph.requests.PurchaseInvoiceLineRequestBuilder purchaseInvoiceLines(@Nonnull final String id) {
        return new com.microsoft.graph.requests.PurchaseInvoiceLineRequestBuilder(getRequestUrlWithAdditionalSegment("purchaseInvoiceLines") + "/" + id, getClient(), null);
    }
    /**
     *  Gets a request builder for the PurchaseInvoice collection
     *
     * @return the collection request builder
     */
    @Nonnull
    public com.microsoft.graph.requests.PurchaseInvoiceCollectionRequestBuilder purchaseInvoices() {
        return new com.microsoft.graph.requests.PurchaseInvoiceCollectionRequestBuilder(getRequestUrlWithAdditionalSegment("purchaseInvoices"), getClient(), null);
    }

    /**
     * Gets a request builder for the PurchaseInvoice item
     *
     * @return the request builder
     * @param id the item identifier
     */
    @Nonnull
    public com.microsoft.graph.requests.PurchaseInvoiceRequestBuilder purchaseInvoices(@Nonnull final String id) {
        return new com.microsoft.graph.requests.PurchaseInvoiceRequestBuilder(getRequestUrlWithAdditionalSegment("purchaseInvoices") + "/" + id, getClient(), null);
    }
    /**
     *  Gets a request builder for the SalesCreditMemoLine collection
     *
     * @return the collection request builder
     */
    @Nonnull
    public com.microsoft.graph.requests.SalesCreditMemoLineCollectionRequestBuilder salesCreditMemoLines() {
        return new com.microsoft.graph.requests.SalesCreditMemoLineCollectionRequestBuilder(getRequestUrlWithAdditionalSegment("salesCreditMemoLines"), getClient(), null);
    }

    /**
     * Gets a request builder for the SalesCreditMemoLine item
     *
     * @return the request builder
     * @param id the item identifier
     */
    @Nonnull
    public com.microsoft.graph.requests.SalesCreditMemoLineRequestBuilder salesCreditMemoLines(@Nonnull final String id) {
        return new com.microsoft.graph.requests.SalesCreditMemoLineRequestBuilder(getRequestUrlWithAdditionalSegment("salesCreditMemoLines") + "/" + id, getClient(), null);
    }
    /**
     *  Gets a request builder for the SalesCreditMemo collection
     *
     * @return the collection request builder
     */
    @Nonnull
    public com.microsoft.graph.requests.SalesCreditMemoCollectionRequestBuilder salesCreditMemos() {
        return new com.microsoft.graph.requests.SalesCreditMemoCollectionRequestBuilder(getRequestUrlWithAdditionalSegment("salesCreditMemos"), getClient(), null);
    }

    /**
     * Gets a request builder for the SalesCreditMemo item
     *
     * @return the request builder
     * @param id the item identifier
     */
    @Nonnull
    public com.microsoft.graph.requests.SalesCreditMemoRequestBuilder salesCreditMemos(@Nonnull final String id) {
        return new com.microsoft.graph.requests.SalesCreditMemoRequestBuilder(getRequestUrlWithAdditionalSegment("salesCreditMemos") + "/" + id, getClient(), null);
    }
    /**
     *  Gets a request builder for the SalesInvoiceLine collection
     *
     * @return the collection request builder
     */
    @Nonnull
    public com.microsoft.graph.requests.SalesInvoiceLineCollectionRequestBuilder salesInvoiceLines() {
        return new com.microsoft.graph.requests.SalesInvoiceLineCollectionRequestBuilder(getRequestUrlWithAdditionalSegment("salesInvoiceLines"), getClient(), null);
    }

    /**
     * Gets a request builder for the SalesInvoiceLine item
     *
     * @return the request builder
     * @param id the item identifier
     */
    @Nonnull
    public com.microsoft.graph.requests.SalesInvoiceLineRequestBuilder salesInvoiceLines(@Nonnull final String id) {
        return new com.microsoft.graph.requests.SalesInvoiceLineRequestBuilder(getRequestUrlWithAdditionalSegment("salesInvoiceLines") + "/" + id, getClient(), null);
    }
    /**
     *  Gets a request builder for the SalesInvoice collection
     *
     * @return the collection request builder
     */
    @Nonnull
    public com.microsoft.graph.requests.SalesInvoiceCollectionRequestBuilder salesInvoices() {
        return new com.microsoft.graph.requests.SalesInvoiceCollectionRequestBuilder(getRequestUrlWithAdditionalSegment("salesInvoices"), getClient(), null);
    }

    /**
     * Gets a request builder for the SalesInvoice item
     *
     * @return the request builder
     * @param id the item identifier
     */
    @Nonnull
    public com.microsoft.graph.requests.SalesInvoiceRequestBuilder salesInvoices(@Nonnull final String id) {
        return new com.microsoft.graph.requests.SalesInvoiceRequestBuilder(getRequestUrlWithAdditionalSegment("salesInvoices") + "/" + id, getClient(), null);
    }
    /**
     *  Gets a request builder for the SalesOrderLine collection
     *
     * @return the collection request builder
     */
    @Nonnull
    public com.microsoft.graph.requests.SalesOrderLineCollectionRequestBuilder salesOrderLines() {
        return new com.microsoft.graph.requests.SalesOrderLineCollectionRequestBuilder(getRequestUrlWithAdditionalSegment("salesOrderLines"), getClient(), null);
    }

    /**
     * Gets a request builder for the SalesOrderLine item
     *
     * @return the request builder
     * @param id the item identifier
     */
    @Nonnull
    public com.microsoft.graph.requests.SalesOrderLineRequestBuilder salesOrderLines(@Nonnull final String id) {
        return new com.microsoft.graph.requests.SalesOrderLineRequestBuilder(getRequestUrlWithAdditionalSegment("salesOrderLines") + "/" + id, getClient(), null);
    }
    /**
     *  Gets a request builder for the SalesOrder collection
     *
     * @return the collection request builder
     */
    @Nonnull
    public com.microsoft.graph.requests.SalesOrderCollectionRequestBuilder salesOrders() {
        return new com.microsoft.graph.requests.SalesOrderCollectionRequestBuilder(getRequestUrlWithAdditionalSegment("salesOrders"), getClient(), null);
    }

    /**
     * Gets a request builder for the SalesOrder item
     *
     * @return the request builder
     * @param id the item identifier
     */
    @Nonnull
    public com.microsoft.graph.requests.SalesOrderRequestBuilder salesOrders(@Nonnull final String id) {
        return new com.microsoft.graph.requests.SalesOrderRequestBuilder(getRequestUrlWithAdditionalSegment("salesOrders") + "/" + id, getClient(), null);
    }
    /**
     *  Gets a request builder for the SalesQuoteLine collection
     *
     * @return the collection request builder
     */
    @Nonnull
    public com.microsoft.graph.requests.SalesQuoteLineCollectionRequestBuilder salesQuoteLines() {
        return new com.microsoft.graph.requests.SalesQuoteLineCollectionRequestBuilder(getRequestUrlWithAdditionalSegment("salesQuoteLines"), getClient(), null);
    }

    /**
     * Gets a request builder for the SalesQuoteLine item
     *
     * @return the request builder
     * @param id the item identifier
     */
    @Nonnull
    public com.microsoft.graph.requests.SalesQuoteLineRequestBuilder salesQuoteLines(@Nonnull final String id) {
        return new com.microsoft.graph.requests.SalesQuoteLineRequestBuilder(getRequestUrlWithAdditionalSegment("salesQuoteLines") + "/" + id, getClient(), null);
    }
    /**
     *  Gets a request builder for the SalesQuote collection
     *
     * @return the collection request builder
     */
    @Nonnull
    public com.microsoft.graph.requests.SalesQuoteCollectionRequestBuilder salesQuotes() {
        return new com.microsoft.graph.requests.SalesQuoteCollectionRequestBuilder(getRequestUrlWithAdditionalSegment("salesQuotes"), getClient(), null);
    }

    /**
     * Gets a request builder for the SalesQuote item
     *
     * @return the request builder
     * @param id the item identifier
     */
    @Nonnull
    public com.microsoft.graph.requests.SalesQuoteRequestBuilder salesQuotes(@Nonnull final String id) {
        return new com.microsoft.graph.requests.SalesQuoteRequestBuilder(getRequestUrlWithAdditionalSegment("salesQuotes") + "/" + id, getClient(), null);
    }
    /**
     *  Gets a request builder for the ShipmentMethod collection
     *
     * @return the collection request builder
     */
    @Nonnull
    public com.microsoft.graph.requests.ShipmentMethodCollectionRequestBuilder shipmentMethods() {
        return new com.microsoft.graph.requests.ShipmentMethodCollectionRequestBuilder(getRequestUrlWithAdditionalSegment("shipmentMethods"), getClient(), null);
    }

    /**
     * Gets a request builder for the ShipmentMethod item
     *
     * @return the request builder
     * @param id the item identifier
     */
    @Nonnull
    public com.microsoft.graph.requests.ShipmentMethodRequestBuilder shipmentMethods(@Nonnull final String id) {
        return new com.microsoft.graph.requests.ShipmentMethodRequestBuilder(getRequestUrlWithAdditionalSegment("shipmentMethods") + "/" + id, getClient(), null);
    }
    /**
     *  Gets a request builder for the TaxArea collection
     *
     * @return the collection request builder
     */
    @Nonnull
    public com.microsoft.graph.requests.TaxAreaCollectionRequestBuilder taxAreas() {
        return new com.microsoft.graph.requests.TaxAreaCollectionRequestBuilder(getRequestUrlWithAdditionalSegment("taxAreas"), getClient(), null);
    }

    /**
     * Gets a request builder for the TaxArea item
     *
     * @return the request builder
     * @param id the item identifier
     */
    @Nonnull
    public com.microsoft.graph.requests.TaxAreaRequestBuilder taxAreas(@Nonnull final String id) {
        return new com.microsoft.graph.requests.TaxAreaRequestBuilder(getRequestUrlWithAdditionalSegment("taxAreas") + "/" + id, getClient(), null);
    }
    /**
     *  Gets a request builder for the TaxGroup collection
     *
     * @return the collection request builder
     */
    @Nonnull
    public com.microsoft.graph.requests.TaxGroupCollectionRequestBuilder taxGroups() {
        return new com.microsoft.graph.requests.TaxGroupCollectionRequestBuilder(getRequestUrlWithAdditionalSegment("taxGroups"), getClient(), null);
    }

    /**
     * Gets a request builder for the TaxGroup item
     *
     * @return the request builder
     * @param id the item identifier
     */
    @Nonnull
    public com.microsoft.graph.requests.TaxGroupRequestBuilder taxGroups(@Nonnull final String id) {
        return new com.microsoft.graph.requests.TaxGroupRequestBuilder(getRequestUrlWithAdditionalSegment("taxGroups") + "/" + id, getClient(), null);
    }
    /**
     *  Gets a request builder for the UnitOfMeasure collection
     *
     * @return the collection request builder
     */
    @Nonnull
    public com.microsoft.graph.requests.UnitOfMeasureCollectionRequestBuilder unitsOfMeasure() {
        return new com.microsoft.graph.requests.UnitOfMeasureCollectionRequestBuilder(getRequestUrlWithAdditionalSegment("unitsOfMeasure"), getClient(), null);
    }

    /**
     * Gets a request builder for the UnitOfMeasure item
     *
     * @return the request builder
     * @param id the item identifier
     */
    @Nonnull
    public com.microsoft.graph.requests.UnitOfMeasureRequestBuilder unitsOfMeasure(@Nonnull final String id) {
        return new com.microsoft.graph.requests.UnitOfMeasureRequestBuilder(getRequestUrlWithAdditionalSegment("unitsOfMeasure") + "/" + id, getClient(), null);
    }
    /**
     *  Gets a request builder for the Vendor collection
     *
     * @return the collection request builder
     */
    @Nonnull
    public com.microsoft.graph.requests.VendorCollectionRequestBuilder vendors() {
        return new com.microsoft.graph.requests.VendorCollectionRequestBuilder(getRequestUrlWithAdditionalSegment("vendors"), getClient(), null);
    }

    /**
     * Gets a request builder for the Vendor item
     *
     * @return the request builder
     * @param id the item identifier
     */
    @Nonnull
    public com.microsoft.graph.requests.VendorRequestBuilder vendors(@Nonnull final String id) {
        return new com.microsoft.graph.requests.VendorRequestBuilder(getRequestUrlWithAdditionalSegment("vendors") + "/" + id, getClient(), null);
    }
}
