// Template Source: BaseEntityCollectionRequestBuilder.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.models.WebApplicationSegment;
import com.microsoft.graph.models.CorsConfiguration_v2;
import java.util.Arrays;
import java.util.EnumSet;
import javax.annotation.Nullable;
import javax.annotation.Nonnull;

import com.microsoft.graph.requests.CorsConfiguration_v2CollectionRequestBuilder;
import com.microsoft.graph.requests.CorsConfiguration_v2RequestBuilder;
import com.microsoft.graph.requests.CorsConfiguration_v2CollectionRequest;
import com.microsoft.graph.http.BaseCollectionRequestBuilder;
import com.microsoft.graph.core.IBaseClient;
import com.microsoft.graph.http.PrimitiveRequestBuilder;
// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Cors Configuration_v2Collection Request Builder.
 */
public class CorsConfiguration_v2CollectionRequestBuilder extends BaseCollectionRequestBuilder<CorsConfiguration_v2, CorsConfiguration_v2RequestBuilder, CorsConfiguration_v2CollectionResponse, CorsConfiguration_v2CollectionPage, CorsConfiguration_v2CollectionRequest> {

    /**
     * The request builder for this collection of WebApplicationSegment
     *
     * @param requestUrl     the request URL
     * @param client         the service client
     * @param requestOptions the options for this request
     */
    public CorsConfiguration_v2CollectionRequestBuilder(@Nonnull final String requestUrl, @Nonnull final IBaseClient<?> client, @Nullable final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        super(requestUrl, client, requestOptions, CorsConfiguration_v2RequestBuilder.class, CorsConfiguration_v2CollectionRequest.class);
    }



    /**
     * Gets the raw count request for the collection
     * @return The raw count request for the collection
     */
    @Nonnull
    public PrimitiveRequestBuilder<Long> count() {
        return new PrimitiveRequestBuilder<Long>(getRequestUrlWithAdditionalSegment("$count"), getClient(), null, Long.class);
    }
}
