// Template Source: BaseEntityRequest.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.models.CredentialUserRegistrationDetails;
import java.util.Arrays;
import java.util.EnumSet;
import javax.annotation.Nullable;
import javax.annotation.Nonnull;
import com.microsoft.graph.core.IBaseClient;
import com.microsoft.graph.http.BaseRequest;
import com.microsoft.graph.http.HttpMethod;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Credential User Registration Details Request.
 */
public class CredentialUserRegistrationDetailsRequest extends BaseRequest<CredentialUserRegistrationDetails> {
	
    /**
     * The request for the CredentialUserRegistrationDetails
     *
     * @param requestUrl     the request URL
     * @param client         the service client
     * @param requestOptions the options for this request
     */
    public CredentialUserRegistrationDetailsRequest(@Nonnull final String requestUrl, @Nonnull final IBaseClient<?> client, @Nullable final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        super(requestUrl, client, requestOptions, CredentialUserRegistrationDetails.class);
    }

    /**
     * Gets the CredentialUserRegistrationDetails from the service
     *
     * @return a future with the result
     */
    @Nonnull
    public java.util.concurrent.CompletableFuture<CredentialUserRegistrationDetails> getAsync() {
        return sendAsync(HttpMethod.GET, null);
    }

    /**
     * Gets the CredentialUserRegistrationDetails from the service
     *
     * @return the CredentialUserRegistrationDetails from the request
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public CredentialUserRegistrationDetails get() throws ClientException {
       return send(HttpMethod.GET, null);
    }

    /**
     * Delete this item from the service
     *
     * @return a future with the deletion result
     */
    @Nonnull
    public java.util.concurrent.CompletableFuture<CredentialUserRegistrationDetails> deleteAsync() {
        return sendAsync(HttpMethod.DELETE, null);
    }

    /**
     * Delete this item from the service
     * @return the resulting response if the service returns anything on deletion
     *
     * @throws ClientException if there was an exception during the delete operation
     */
    @Nullable
    public CredentialUserRegistrationDetails delete() throws ClientException {
        return send(HttpMethod.DELETE, null);
    }

    /**
     * Patches this CredentialUserRegistrationDetails with a source
     *
     * @param sourceCredentialUserRegistrationDetails the source object with updates
     * @return a future with the result
     */
    @Nonnull
    public java.util.concurrent.CompletableFuture<CredentialUserRegistrationDetails> patchAsync(@Nonnull final CredentialUserRegistrationDetails sourceCredentialUserRegistrationDetails) {
        return sendAsync(HttpMethod.PATCH, sourceCredentialUserRegistrationDetails);
    }

    /**
     * Patches this CredentialUserRegistrationDetails with a source
     *
     * @param sourceCredentialUserRegistrationDetails the source object with updates
     * @return the updated CredentialUserRegistrationDetails
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public CredentialUserRegistrationDetails patch(@Nonnull final CredentialUserRegistrationDetails sourceCredentialUserRegistrationDetails) throws ClientException {
        return send(HttpMethod.PATCH, sourceCredentialUserRegistrationDetails);
    }

    /**
     * Creates a CredentialUserRegistrationDetails with a new object
     *
     * @param newCredentialUserRegistrationDetails the new object to create
     * @return a future with the result
     */
    @Nonnull
    public java.util.concurrent.CompletableFuture<CredentialUserRegistrationDetails> postAsync(@Nonnull final CredentialUserRegistrationDetails newCredentialUserRegistrationDetails) {
        return sendAsync(HttpMethod.POST, newCredentialUserRegistrationDetails);
    }

    /**
     * Creates a CredentialUserRegistrationDetails with a new object
     *
     * @param newCredentialUserRegistrationDetails the new object to create
     * @return the created CredentialUserRegistrationDetails
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public CredentialUserRegistrationDetails post(@Nonnull final CredentialUserRegistrationDetails newCredentialUserRegistrationDetails) throws ClientException {
        return send(HttpMethod.POST, newCredentialUserRegistrationDetails);
    }

    /**
     * Creates a CredentialUserRegistrationDetails with a new object
     *
     * @param newCredentialUserRegistrationDetails the object to create/update
     * @return a future with the result
     */
    @Nonnull
    public java.util.concurrent.CompletableFuture<CredentialUserRegistrationDetails> putAsync(@Nonnull final CredentialUserRegistrationDetails newCredentialUserRegistrationDetails) {
        return sendAsync(HttpMethod.PUT, newCredentialUserRegistrationDetails);
    }

    /**
     * Creates a CredentialUserRegistrationDetails with a new object
     *
     * @param newCredentialUserRegistrationDetails the object to create/update
     * @return the created CredentialUserRegistrationDetails
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public CredentialUserRegistrationDetails put(@Nonnull final CredentialUserRegistrationDetails newCredentialUserRegistrationDetails) throws ClientException {
        return send(HttpMethod.PUT, newCredentialUserRegistrationDetails);
    }

    /**
     * Sets the select clause for the request
     *
     * @param value the select clause
     * @return the updated request
     */
     @Nonnull
     public CredentialUserRegistrationDetailsRequest select(@Nonnull final String value) {
         addSelectOption(value);
         return this;
     }

    /**
     * Sets the expand clause for the request
     *
     * @param value the expand clause
     * @return the updated request
     */
     @Nonnull
     public CredentialUserRegistrationDetailsRequest expand(@Nonnull final String value) {
         addExpandOption(value);
         return this;
     }

}

