// Template Source: BaseMethodCollectionRequestBuilder.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.models.PolicyPlatformType;
import com.microsoft.graph.models.DeviceManagementResourceAccessProfileBase;
import java.util.Arrays;
import java.util.EnumSet;
import javax.annotation.Nullable;
import javax.annotation.Nonnull;

import com.microsoft.graph.requests.DeviceManagementResourceAccessProfileBaseQueryByPlatformTypeCollectionRequestBuilder;
import com.microsoft.graph.requests.DeviceManagementResourceAccessProfileBaseQueryByPlatformTypeCollectionRequest;
import com.microsoft.graph.requests.DeviceManagementResourceAccessProfileBaseQueryByPlatformTypeCollectionResponse;
import com.microsoft.graph.models.DeviceManagementResourceAccessProfileBaseQueryByPlatformTypeParameterSet;
import com.microsoft.graph.options.FunctionOption;
import com.microsoft.graph.core.IBaseClient;
import com.microsoft.graph.http.BaseActionCollectionRequestBuilder;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Device Management Resource Access Profile Base Query By Platform Type Collection Request Builder.
 */
public class DeviceManagementResourceAccessProfileBaseQueryByPlatformTypeCollectionRequestBuilder extends BaseActionCollectionRequestBuilder<DeviceManagementResourceAccessProfileBase, DeviceManagementResourceAccessProfileBaseQueryByPlatformTypeCollectionRequestBuilder, DeviceManagementResourceAccessProfileBaseQueryByPlatformTypeCollectionResponse, DeviceManagementResourceAccessProfileBaseQueryByPlatformTypeCollectionPage, DeviceManagementResourceAccessProfileBaseQueryByPlatformTypeCollectionRequest> {

    /**
     * The request builder for this collection of DeviceManagementResourceAccessProfileBase
     *
     * @param requestUrl     the request URL
     * @param client         the service client
     * @param requestOptions the options for this request
     */
    public DeviceManagementResourceAccessProfileBaseQueryByPlatformTypeCollectionRequestBuilder(@Nonnull final String requestUrl, @Nonnull final IBaseClient<?> client, @Nullable final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        super(requestUrl, client, requestOptions, DeviceManagementResourceAccessProfileBaseQueryByPlatformTypeCollectionRequestBuilder.class, DeviceManagementResourceAccessProfileBaseQueryByPlatformTypeCollectionRequest.class);
    }
    private DeviceManagementResourceAccessProfileBaseQueryByPlatformTypeParameterSet body;
    /**
     * The request builder for this collection of DeviceManagementResourceAccessProfileBase
     *
     * @param requestUrl     the request URL
     * @param client         the service client
     * @param requestOptions the options for this request
     * @param parameters     the parameters for the service method
     */
    public DeviceManagementResourceAccessProfileBaseQueryByPlatformTypeCollectionRequestBuilder(@Nonnull final String requestUrl, @Nonnull final IBaseClient<?> client, @Nullable final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions, @Nonnull final DeviceManagementResourceAccessProfileBaseQueryByPlatformTypeParameterSet parameters) {
        super(requestUrl, client, requestOptions, DeviceManagementResourceAccessProfileBaseQueryByPlatformTypeCollectionRequestBuilder.class, DeviceManagementResourceAccessProfileBaseQueryByPlatformTypeCollectionRequest.class);
        this.body = parameters;
    }
    /**
     * Creates the request
     *
     * @param requestOptions the options for this request
     * @return the DeviceManagementResourceAccessProfileBaseQueryByPlatformTypeCollectionRequest instance
     */
    @Override
    @Nonnull
    public DeviceManagementResourceAccessProfileBaseQueryByPlatformTypeCollectionRequest buildRequest(@Nullable final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        final DeviceManagementResourceAccessProfileBaseQueryByPlatformTypeCollectionRequest request = super.buildRequest(requestOptions);
            request.body = this.body;
            return request;
    }
}
