// Template Source: BaseEntityCollectionRequestBuilder.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.models.DeviceManagement;
import com.microsoft.graph.models.DeviceManagementIntent;
import com.microsoft.graph.models.DeviceManagementIntentAssignment;
import com.microsoft.graph.models.DeviceManagementSettingInstance;
import com.microsoft.graph.models.DeviceManagementSettingComparison;
import com.microsoft.graph.models.DeviceManagementIntentCustomizedSetting;
import java.util.Arrays;
import java.util.EnumSet;
import javax.annotation.Nullable;
import javax.annotation.Nonnull;

import com.microsoft.graph.requests.DeviceManagementIntentCollectionRequestBuilder;
import com.microsoft.graph.requests.DeviceManagementIntentRequestBuilder;
import com.microsoft.graph.requests.DeviceManagementIntentCollectionRequest;
import com.microsoft.graph.http.BaseCollectionRequestBuilder;
import com.microsoft.graph.core.IBaseClient;
import com.microsoft.graph.http.PrimitiveRequestBuilder;
import com.microsoft.graph.models.DeviceManagementIntentAssignParameterSet;
import com.microsoft.graph.models.DeviceManagementIntentCreateCopyParameterSet;
import com.microsoft.graph.models.DeviceManagementIntentMigrateToTemplateParameterSet;
import com.microsoft.graph.models.DeviceManagementIntentUpdateSettingsParameterSet;
import com.microsoft.graph.models.DeviceManagementIntentCompareParameterSet;
// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Device Management Intent Collection Request Builder.
 */
public class DeviceManagementIntentCollectionRequestBuilder extends BaseCollectionRequestBuilder<DeviceManagementIntent, DeviceManagementIntentRequestBuilder, DeviceManagementIntentCollectionResponse, DeviceManagementIntentCollectionPage, DeviceManagementIntentCollectionRequest> {

    /**
     * The request builder for this collection of DeviceManagement
     *
     * @param requestUrl     the request URL
     * @param client         the service client
     * @param requestOptions the options for this request
     */
    public DeviceManagementIntentCollectionRequestBuilder(@Nonnull final String requestUrl, @Nonnull final IBaseClient<?> client, @Nullable final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        super(requestUrl, client, requestOptions, DeviceManagementIntentRequestBuilder.class, DeviceManagementIntentCollectionRequest.class);
    }



    /**
     * Gets the raw count request for the collection
     * @return The raw count request for the collection
     */
    @Nonnull
    public PrimitiveRequestBuilder<Long> count() {
        return new PrimitiveRequestBuilder<Long>(getRequestUrlWithAdditionalSegment("$count"), getClient(), null, Long.class);
    }
}
