// Template Source: BaseEntityRequestBuilder.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.models.GroupPolicyCategory;
import java.util.Arrays;
import java.util.EnumSet;
import javax.annotation.Nullable;
import javax.annotation.Nonnull;
import com.microsoft.graph.core.IBaseClient;
import com.microsoft.graph.http.BaseRequestBuilder;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Group Policy Category Request Builder.
 */
public class GroupPolicyCategoryRequestBuilder extends BaseRequestBuilder<GroupPolicyCategory> {

    /**
     * The request builder for the GroupPolicyCategory
     *
     * @param requestUrl     the request URL
     * @param client         the service client
     * @param requestOptions the options for this request
     */
    public GroupPolicyCategoryRequestBuilder(@Nonnull final String requestUrl, @Nonnull final IBaseClient<?> client, @Nullable final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        super(requestUrl, client, requestOptions);
    }

    /**
     * Creates the request
     *
     * @param requestOptions the options for this request
     * @return the GroupPolicyCategoryRequest instance
     */
    @Nonnull
    public GroupPolicyCategoryRequest buildRequest(@Nullable final com.microsoft.graph.options.Option... requestOptions) {
        return buildRequest(getOptions(requestOptions));
    }

    /**
     * Creates the request with specific requestOptions instead of the existing requestOptions
     *
     * @param requestOptions the options for this request
     * @return the GroupPolicyCategoryRequest instance
     */
    @Nonnull
    public GroupPolicyCategoryRequest buildRequest(@Nonnull final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        return new com.microsoft.graph.requests.GroupPolicyCategoryRequest(getRequestUrl(), getClient(), requestOptions);
    }


    /**
     *  Gets a request builder for the GroupPolicyCategory collection
     *
     * @return the collection request builder
     */
    @Nonnull
    public com.microsoft.graph.requests.GroupPolicyCategoryCollectionWithReferencesRequestBuilder children() {
        return new com.microsoft.graph.requests.GroupPolicyCategoryCollectionWithReferencesRequestBuilder(getRequestUrlWithAdditionalSegment("children"), getClient(), null);
    }

    /**
     * Gets a request builder for the GroupPolicyCategory item
     *
     * @return the request builder
     * @param id the item identifier
     */
    @Nonnull
    public com.microsoft.graph.requests.GroupPolicyCategoryWithReferenceRequestBuilder children(@Nonnull final String id) {
        return new com.microsoft.graph.requests.GroupPolicyCategoryWithReferenceRequestBuilder(getRequestUrlWithAdditionalSegment("children") + "/" + id, getClient(), null);
    }

    /**
     * Gets the request builder for GroupPolicyDefinitionFile
     *
     * @return the GroupPolicyDefinitionFileWithReferenceRequestBuilder instance
     */
    @Nonnull
    public com.microsoft.graph.requests.GroupPolicyDefinitionFileWithReferenceRequestBuilder definitionFile() {
        return new com.microsoft.graph.requests.GroupPolicyDefinitionFileWithReferenceRequestBuilder(getRequestUrlWithAdditionalSegment("definitionFile"), getClient(), null);
    }
    /**
     *  Gets a request builder for the GroupPolicyDefinition collection
     *
     * @return the collection request builder
     */
    @Nonnull
    public com.microsoft.graph.requests.GroupPolicyDefinitionCollectionWithReferencesRequestBuilder definitions() {
        return new com.microsoft.graph.requests.GroupPolicyDefinitionCollectionWithReferencesRequestBuilder(getRequestUrlWithAdditionalSegment("definitions"), getClient(), null);
    }

    /**
     * Gets a request builder for the GroupPolicyDefinition item
     *
     * @return the request builder
     * @param id the item identifier
     */
    @Nonnull
    public com.microsoft.graph.requests.GroupPolicyDefinitionWithReferenceRequestBuilder definitions(@Nonnull final String id) {
        return new com.microsoft.graph.requests.GroupPolicyDefinitionWithReferenceRequestBuilder(getRequestUrlWithAdditionalSegment("definitions") + "/" + id, getClient(), null);
    }

    /**
     * Gets the request builder for GroupPolicyCategory
     *
     * @return the GroupPolicyCategoryWithReferenceRequestBuilder instance
     */
    @Nonnull
    public com.microsoft.graph.requests.GroupPolicyCategoryWithReferenceRequestBuilder parent() {
        return new com.microsoft.graph.requests.GroupPolicyCategoryWithReferenceRequestBuilder(getRequestUrlWithAdditionalSegment("parent"), getClient(), null);
    }
}
