// Template Source: BaseEntityCollectionWithReferencesPage.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.models.MonthlyUserInsightMetricsRoot;
import com.microsoft.graph.models.InsightSummary;
import java.util.Arrays;
import java.util.EnumSet;
import javax.annotation.Nullable;
import javax.annotation.Nonnull;

import com.microsoft.graph.requests.InsightSummaryCollectionWithReferencesRequestBuilder;
import com.microsoft.graph.requests.InsightSummaryCollectionWithReferencesPage;
import com.microsoft.graph.requests.InsightSummaryCollectionResponse;
import com.microsoft.graph.models.InsightSummary;
import com.google.gson.JsonObject;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import com.microsoft.graph.http.BaseCollectionPage;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Insight Summary Collection With References Page.
 */
public class InsightSummaryCollectionWithReferencesPage extends BaseCollectionPage<InsightSummary, InsightSummaryCollectionWithReferencesRequestBuilder> {

    /**
     * A collection page for InsightSummary
     *
     * @param response the serialized InsightSummaryCollectionResponse from the service
     * @param builder  the request builder for the next collection page
     */
    public InsightSummaryCollectionWithReferencesPage(@Nonnull final InsightSummaryCollectionResponse response, @Nullable final InsightSummaryCollectionWithReferencesRequestBuilder builder) {
        super(response.value, builder, response.additionalDataManager());
    }

    /**
     * Creates the collection page for InsightSummary
     *
     * @param pageContents       the contents of this page
     * @param nextRequestBuilder the request builder for the next page
     */
    public InsightSummaryCollectionWithReferencesPage(@Nonnull final java.util.List<InsightSummary> pageContents, @Nullable final InsightSummaryCollectionWithReferencesRequestBuilder nextRequestBuilder) {
        super(pageContents, nextRequestBuilder);
    }
}
