// Template Source: BaseEntityRequest.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.models.MultiTenantOrganizationPartnerConfigurationTemplate;
import java.util.Arrays;
import java.util.EnumSet;
import javax.annotation.Nullable;
import javax.annotation.Nonnull;
import com.microsoft.graph.core.IBaseClient;
import com.microsoft.graph.http.BaseRequest;
import com.microsoft.graph.http.HttpMethod;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Multi Tenant Organization Partner Configuration Template Request.
 */
public class MultiTenantOrganizationPartnerConfigurationTemplateRequest extends BaseRequest<MultiTenantOrganizationPartnerConfigurationTemplate> {
	
    /**
     * The request for the MultiTenantOrganizationPartnerConfigurationTemplate
     *
     * @param requestUrl     the request URL
     * @param client         the service client
     * @param requestOptions the options for this request
     */
    public MultiTenantOrganizationPartnerConfigurationTemplateRequest(@Nonnull final String requestUrl, @Nonnull final IBaseClient<?> client, @Nullable final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        super(requestUrl, client, requestOptions, MultiTenantOrganizationPartnerConfigurationTemplate.class);
    }

    /**
     * Gets the MultiTenantOrganizationPartnerConfigurationTemplate from the service
     *
     * @return a future with the result
     */
    @Nonnull
    public java.util.concurrent.CompletableFuture<MultiTenantOrganizationPartnerConfigurationTemplate> getAsync() {
        return sendAsync(HttpMethod.GET, null);
    }

    /**
     * Gets the MultiTenantOrganizationPartnerConfigurationTemplate from the service
     *
     * @return the MultiTenantOrganizationPartnerConfigurationTemplate from the request
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public MultiTenantOrganizationPartnerConfigurationTemplate get() throws ClientException {
       return send(HttpMethod.GET, null);
    }

    /**
     * Delete this item from the service
     *
     * @return a future with the deletion result
     */
    @Nonnull
    public java.util.concurrent.CompletableFuture<MultiTenantOrganizationPartnerConfigurationTemplate> deleteAsync() {
        return sendAsync(HttpMethod.DELETE, null);
    }

    /**
     * Delete this item from the service
     * @return the resulting response if the service returns anything on deletion
     *
     * @throws ClientException if there was an exception during the delete operation
     */
    @Nullable
    public MultiTenantOrganizationPartnerConfigurationTemplate delete() throws ClientException {
        return send(HttpMethod.DELETE, null);
    }

    /**
     * Patches this MultiTenantOrganizationPartnerConfigurationTemplate with a source
     *
     * @param sourceMultiTenantOrganizationPartnerConfigurationTemplate the source object with updates
     * @return a future with the result
     */
    @Nonnull
    public java.util.concurrent.CompletableFuture<MultiTenantOrganizationPartnerConfigurationTemplate> patchAsync(@Nonnull final MultiTenantOrganizationPartnerConfigurationTemplate sourceMultiTenantOrganizationPartnerConfigurationTemplate) {
        return sendAsync(HttpMethod.PATCH, sourceMultiTenantOrganizationPartnerConfigurationTemplate);
    }

    /**
     * Patches this MultiTenantOrganizationPartnerConfigurationTemplate with a source
     *
     * @param sourceMultiTenantOrganizationPartnerConfigurationTemplate the source object with updates
     * @return the updated MultiTenantOrganizationPartnerConfigurationTemplate
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public MultiTenantOrganizationPartnerConfigurationTemplate patch(@Nonnull final MultiTenantOrganizationPartnerConfigurationTemplate sourceMultiTenantOrganizationPartnerConfigurationTemplate) throws ClientException {
        return send(HttpMethod.PATCH, sourceMultiTenantOrganizationPartnerConfigurationTemplate);
    }

    /**
     * Creates a MultiTenantOrganizationPartnerConfigurationTemplate with a new object
     *
     * @param newMultiTenantOrganizationPartnerConfigurationTemplate the new object to create
     * @return a future with the result
     */
    @Nonnull
    public java.util.concurrent.CompletableFuture<MultiTenantOrganizationPartnerConfigurationTemplate> postAsync(@Nonnull final MultiTenantOrganizationPartnerConfigurationTemplate newMultiTenantOrganizationPartnerConfigurationTemplate) {
        return sendAsync(HttpMethod.POST, newMultiTenantOrganizationPartnerConfigurationTemplate);
    }

    /**
     * Creates a MultiTenantOrganizationPartnerConfigurationTemplate with a new object
     *
     * @param newMultiTenantOrganizationPartnerConfigurationTemplate the new object to create
     * @return the created MultiTenantOrganizationPartnerConfigurationTemplate
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public MultiTenantOrganizationPartnerConfigurationTemplate post(@Nonnull final MultiTenantOrganizationPartnerConfigurationTemplate newMultiTenantOrganizationPartnerConfigurationTemplate) throws ClientException {
        return send(HttpMethod.POST, newMultiTenantOrganizationPartnerConfigurationTemplate);
    }

    /**
     * Creates a MultiTenantOrganizationPartnerConfigurationTemplate with a new object
     *
     * @param newMultiTenantOrganizationPartnerConfigurationTemplate the object to create/update
     * @return a future with the result
     */
    @Nonnull
    public java.util.concurrent.CompletableFuture<MultiTenantOrganizationPartnerConfigurationTemplate> putAsync(@Nonnull final MultiTenantOrganizationPartnerConfigurationTemplate newMultiTenantOrganizationPartnerConfigurationTemplate) {
        return sendAsync(HttpMethod.PUT, newMultiTenantOrganizationPartnerConfigurationTemplate);
    }

    /**
     * Creates a MultiTenantOrganizationPartnerConfigurationTemplate with a new object
     *
     * @param newMultiTenantOrganizationPartnerConfigurationTemplate the object to create/update
     * @return the created MultiTenantOrganizationPartnerConfigurationTemplate
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public MultiTenantOrganizationPartnerConfigurationTemplate put(@Nonnull final MultiTenantOrganizationPartnerConfigurationTemplate newMultiTenantOrganizationPartnerConfigurationTemplate) throws ClientException {
        return send(HttpMethod.PUT, newMultiTenantOrganizationPartnerConfigurationTemplate);
    }

    /**
     * Sets the select clause for the request
     *
     * @param value the select clause
     * @return the updated request
     */
     @Nonnull
     public MultiTenantOrganizationPartnerConfigurationTemplateRequest select(@Nonnull final String value) {
         addSelectOption(value);
         return this;
     }

    /**
     * Sets the expand clause for the request
     *
     * @param value the expand clause
     * @return the updated request
     */
     @Nonnull
     public MultiTenantOrganizationPartnerConfigurationTemplateRequest expand(@Nonnull final String value) {
         addExpandOption(value);
         return this;
     }

}

