// Template Source: BaseEntityRequest.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.models.OverprovisionedAwsResourceFinding;
import java.util.Arrays;
import java.util.EnumSet;
import javax.annotation.Nullable;
import javax.annotation.Nonnull;
import com.microsoft.graph.core.IBaseClient;
import com.microsoft.graph.http.BaseRequest;
import com.microsoft.graph.http.HttpMethod;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Overprovisioned Aws Resource Finding Request.
 */
public class OverprovisionedAwsResourceFindingRequest extends BaseRequest<OverprovisionedAwsResourceFinding> {
	
    /**
     * The request for the OverprovisionedAwsResourceFinding
     *
     * @param requestUrl     the request URL
     * @param client         the service client
     * @param requestOptions the options for this request
     */
    public OverprovisionedAwsResourceFindingRequest(@Nonnull final String requestUrl, @Nonnull final IBaseClient<?> client, @Nullable final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        super(requestUrl, client, requestOptions, OverprovisionedAwsResourceFinding.class);
    }

    /**
     * Gets the OverprovisionedAwsResourceFinding from the service
     *
     * @return a future with the result
     */
    @Nonnull
    public java.util.concurrent.CompletableFuture<OverprovisionedAwsResourceFinding> getAsync() {
        return sendAsync(HttpMethod.GET, null);
    }

    /**
     * Gets the OverprovisionedAwsResourceFinding from the service
     *
     * @return the OverprovisionedAwsResourceFinding from the request
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public OverprovisionedAwsResourceFinding get() throws ClientException {
       return send(HttpMethod.GET, null);
    }

    /**
     * Delete this item from the service
     *
     * @return a future with the deletion result
     */
    @Nonnull
    public java.util.concurrent.CompletableFuture<OverprovisionedAwsResourceFinding> deleteAsync() {
        return sendAsync(HttpMethod.DELETE, null);
    }

    /**
     * Delete this item from the service
     * @return the resulting response if the service returns anything on deletion
     *
     * @throws ClientException if there was an exception during the delete operation
     */
    @Nullable
    public OverprovisionedAwsResourceFinding delete() throws ClientException {
        return send(HttpMethod.DELETE, null);
    }

    /**
     * Patches this OverprovisionedAwsResourceFinding with a source
     *
     * @param sourceOverprovisionedAwsResourceFinding the source object with updates
     * @return a future with the result
     */
    @Nonnull
    public java.util.concurrent.CompletableFuture<OverprovisionedAwsResourceFinding> patchAsync(@Nonnull final OverprovisionedAwsResourceFinding sourceOverprovisionedAwsResourceFinding) {
        return sendAsync(HttpMethod.PATCH, sourceOverprovisionedAwsResourceFinding);
    }

    /**
     * Patches this OverprovisionedAwsResourceFinding with a source
     *
     * @param sourceOverprovisionedAwsResourceFinding the source object with updates
     * @return the updated OverprovisionedAwsResourceFinding
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public OverprovisionedAwsResourceFinding patch(@Nonnull final OverprovisionedAwsResourceFinding sourceOverprovisionedAwsResourceFinding) throws ClientException {
        return send(HttpMethod.PATCH, sourceOverprovisionedAwsResourceFinding);
    }

    /**
     * Creates a OverprovisionedAwsResourceFinding with a new object
     *
     * @param newOverprovisionedAwsResourceFinding the new object to create
     * @return a future with the result
     */
    @Nonnull
    public java.util.concurrent.CompletableFuture<OverprovisionedAwsResourceFinding> postAsync(@Nonnull final OverprovisionedAwsResourceFinding newOverprovisionedAwsResourceFinding) {
        return sendAsync(HttpMethod.POST, newOverprovisionedAwsResourceFinding);
    }

    /**
     * Creates a OverprovisionedAwsResourceFinding with a new object
     *
     * @param newOverprovisionedAwsResourceFinding the new object to create
     * @return the created OverprovisionedAwsResourceFinding
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public OverprovisionedAwsResourceFinding post(@Nonnull final OverprovisionedAwsResourceFinding newOverprovisionedAwsResourceFinding) throws ClientException {
        return send(HttpMethod.POST, newOverprovisionedAwsResourceFinding);
    }

    /**
     * Creates a OverprovisionedAwsResourceFinding with a new object
     *
     * @param newOverprovisionedAwsResourceFinding the object to create/update
     * @return a future with the result
     */
    @Nonnull
    public java.util.concurrent.CompletableFuture<OverprovisionedAwsResourceFinding> putAsync(@Nonnull final OverprovisionedAwsResourceFinding newOverprovisionedAwsResourceFinding) {
        return sendAsync(HttpMethod.PUT, newOverprovisionedAwsResourceFinding);
    }

    /**
     * Creates a OverprovisionedAwsResourceFinding with a new object
     *
     * @param newOverprovisionedAwsResourceFinding the object to create/update
     * @return the created OverprovisionedAwsResourceFinding
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public OverprovisionedAwsResourceFinding put(@Nonnull final OverprovisionedAwsResourceFinding newOverprovisionedAwsResourceFinding) throws ClientException {
        return send(HttpMethod.PUT, newOverprovisionedAwsResourceFinding);
    }

    /**
     * Sets the select clause for the request
     *
     * @param value the select clause
     * @return the updated request
     */
     @Nonnull
     public OverprovisionedAwsResourceFindingRequest select(@Nonnull final String value) {
         addSelectOption(value);
         return this;
     }

    /**
     * Sets the expand clause for the request
     *
     * @param value the expand clause
     * @return the updated request
     */
     @Nonnull
     public OverprovisionedAwsResourceFindingRequest expand(@Nonnull final String value) {
         addExpandOption(value);
         return this;
     }

}

