// Template Source: BaseMethodCollectionRequestBuilder.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.models.PlannerTask;
import java.util.Arrays;
import java.util.EnumSet;
import javax.annotation.Nullable;
import javax.annotation.Nonnull;

import com.microsoft.graph.requests.PlannerTaskDeltaCollectionRequestBuilder;
import com.microsoft.graph.requests.PlannerTaskDeltaCollectionRequest;
import com.microsoft.graph.requests.PlannerTaskDeltaCollectionResponse;
import com.microsoft.graph.options.FunctionOption;
import com.microsoft.graph.core.IBaseClient;
import com.microsoft.graph.http.BaseFunctionCollectionRequestBuilder;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Planner Task Delta Collection Request Builder.
 */
public class PlannerTaskDeltaCollectionRequestBuilder extends BaseFunctionCollectionRequestBuilder<PlannerTask, PlannerTaskDeltaCollectionRequestBuilder, PlannerTaskDeltaCollectionResponse, PlannerTaskDeltaCollectionPage, PlannerTaskDeltaCollectionRequest> {

    /**
     * The request builder for this collection of PlannerTask
     *
     * @param requestUrl     the request URL
     * @param client         the service client
     * @param requestOptions the options for this request
     */
    public PlannerTaskDeltaCollectionRequestBuilder(@Nonnull final String requestUrl, @Nonnull final IBaseClient<?> client, @Nullable final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        super(requestUrl, client, requestOptions, PlannerTaskDeltaCollectionRequestBuilder.class, PlannerTaskDeltaCollectionRequest.class);
    }
    /**
     * Creates the request
     *
     * @param requestOptions the options for this request
     * @return the PlannerTaskDeltaCollectionRequest instance
     */
    @Override
    @Nonnull
    public PlannerTaskDeltaCollectionRequest buildRequest(@Nullable final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        final PlannerTaskDeltaCollectionRequest request = super.buildRequest(requestOptions);
        return request;
    }
}
