// Template Source: BaseMethodCollectionPage.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.models.TeamsDeviceUsageDistributionUserCounts;
import java.util.Arrays;
import java.util.EnumSet;
import javax.annotation.Nullable;
import javax.annotation.Nonnull;

import com.microsoft.graph.http.BaseCollectionPage;
import com.microsoft.graph.requests.ReportRootGetTeamsDeviceUsageDistributionUserCountsCollectionRequestBuilder;
import com.microsoft.graph.requests.ReportRootGetTeamsDeviceUsageDistributionUserCountsCollectionPage;
import com.microsoft.graph.requests.ReportRootGetTeamsDeviceUsageDistributionUserCountsCollectionResponse;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Report Root Get Teams Device Usage Distribution User Counts Collection Page.
 */
public class ReportRootGetTeamsDeviceUsageDistributionUserCountsCollectionPage extends BaseCollectionPage<TeamsDeviceUsageDistributionUserCounts, ReportRootGetTeamsDeviceUsageDistributionUserCountsCollectionRequestBuilder> {

    /**
     * A collection page for TeamsDeviceUsageDistributionUserCounts.
     *
     * @param response The serialized ReportRootGetTeamsDeviceUsageDistributionUserCountsCollectionResponse from the service
     * @param builder The request builder for the next collection page
     */
    public ReportRootGetTeamsDeviceUsageDistributionUserCountsCollectionPage(@Nonnull final ReportRootGetTeamsDeviceUsageDistributionUserCountsCollectionResponse response, @Nonnull final ReportRootGetTeamsDeviceUsageDistributionUserCountsCollectionRequestBuilder builder) {
       super(response, builder);
    }

	/**
     * Creates the collection page for ReportRootGetTeamsDeviceUsageDistributionUserCounts
     *
     * @param pageContents       the contents of this page
     * @param nextRequestBuilder the request builder for the next page
     */
    public ReportRootGetTeamsDeviceUsageDistributionUserCountsCollectionPage(@Nonnull final java.util.List<TeamsDeviceUsageDistributionUserCounts> pageContents, @Nullable final ReportRootGetTeamsDeviceUsageDistributionUserCountsCollectionRequestBuilder nextRequestBuilder) {
        super(pageContents, nextRequestBuilder);
    }
}
