// Template Source: BaseEntityCollectionPage.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests;
import com.microsoft.graph.models.VirtualEventRegistrant;
import com.microsoft.graph.requests.VirtualEventRegistrantCollectionRequestBuilder;
import javax.annotation.Nullable;
import javax.annotation.Nonnull;
import com.microsoft.graph.requests.VirtualEventRegistrantCollectionResponse;
import com.microsoft.graph.http.BaseCollectionPage;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Virtual Event Registrant Collection Page.
 */
public class VirtualEventRegistrantCollectionPage extends BaseCollectionPage<VirtualEventRegistrant, VirtualEventRegistrantCollectionRequestBuilder> {

    /**
     * A collection page for VirtualEventRegistrant
     *
     * @param response the serialized VirtualEventRegistrantCollectionResponse from the service
     * @param builder  the request builder for the next collection page
     */
    public VirtualEventRegistrantCollectionPage(@Nonnull final VirtualEventRegistrantCollectionResponse response, @Nonnull final VirtualEventRegistrantCollectionRequestBuilder builder) {
        super(response, builder);
    }

    /**
     * Creates the collection page for VirtualEventRegistrant
     *
     * @param pageContents       the contents of this page
     * @param nextRequestBuilder the request builder for the next page
     */
    public VirtualEventRegistrantCollectionPage(@Nonnull final java.util.List<VirtualEventRegistrant> pageContents, @Nullable final VirtualEventRegistrantCollectionRequestBuilder nextRequestBuilder) {
        super(pageContents, nextRequestBuilder);
    }
}
