// Template Source: BaseEntityRequest.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.models.WindowsManagedDevice;
import com.microsoft.graph.models.CloudPcBulkRemoteActionResult;
import com.microsoft.graph.models.RestoreTimeRange;
import com.microsoft.graph.models.CloudPcReviewStatus;
import com.microsoft.graph.models.PowerliftDownloadRequest;
import com.microsoft.graph.models.ManagedDeviceRemoteAction;
import com.microsoft.graph.models.BulkManagedDeviceActionResult;
import com.microsoft.graph.models.AdministratorConfiguredDeviceComplianceState;
import com.microsoft.graph.models.DeviceLogCollectionRequest;
import com.microsoft.graph.models.DeviceLogCollectionResponse;
import com.microsoft.graph.models.ConfigurationManagerAction;
import com.microsoft.graph.models.UpdateWindowsDeviceAccountActionParameter;
import com.microsoft.graph.models.ObliterationBehavior;
import com.microsoft.graph.models.PowerliftIncidentMetadata;
import com.microsoft.graph.models.CloudPcRemoteActionResult;
import com.microsoft.graph.models.DeviceCompliancePolicySettingState;
import com.microsoft.graph.models.OemWarranty;
import java.util.Arrays;
import java.util.EnumSet;
import javax.annotation.Nullable;
import javax.annotation.Nonnull;
import com.microsoft.graph.core.IBaseClient;
import com.microsoft.graph.http.BaseRequest;
import com.microsoft.graph.http.HttpMethod;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Windows Managed Device Request.
 */
public class WindowsManagedDeviceRequest extends BaseRequest<WindowsManagedDevice> {
	
    /**
     * The request for the WindowsManagedDevice
     *
     * @param requestUrl     the request URL
     * @param client         the service client
     * @param requestOptions the options for this request
     */
    public WindowsManagedDeviceRequest(@Nonnull final String requestUrl, @Nonnull final IBaseClient<?> client, @Nullable final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        super(requestUrl, client, requestOptions, WindowsManagedDevice.class);
    }

    /**
     * Gets the WindowsManagedDevice from the service
     *
     * @return a future with the result
     */
    @Nonnull
    public java.util.concurrent.CompletableFuture<WindowsManagedDevice> getAsync() {
        return sendAsync(HttpMethod.GET, null);
    }

    /**
     * Gets the WindowsManagedDevice from the service
     *
     * @return the WindowsManagedDevice from the request
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public WindowsManagedDevice get() throws ClientException {
       return send(HttpMethod.GET, null);
    }

    /**
     * Delete this item from the service
     *
     * @return a future with the deletion result
     */
    @Nonnull
    public java.util.concurrent.CompletableFuture<WindowsManagedDevice> deleteAsync() {
        return sendAsync(HttpMethod.DELETE, null);
    }

    /**
     * Delete this item from the service
     * @return the resulting response if the service returns anything on deletion
     *
     * @throws ClientException if there was an exception during the delete operation
     */
    @Nullable
    public WindowsManagedDevice delete() throws ClientException {
        return send(HttpMethod.DELETE, null);
    }

    /**
     * Patches this WindowsManagedDevice with a source
     *
     * @param sourceWindowsManagedDevice the source object with updates
     * @return a future with the result
     */
    @Nonnull
    public java.util.concurrent.CompletableFuture<WindowsManagedDevice> patchAsync(@Nonnull final WindowsManagedDevice sourceWindowsManagedDevice) {
        return sendAsync(HttpMethod.PATCH, sourceWindowsManagedDevice);
    }

    /**
     * Patches this WindowsManagedDevice with a source
     *
     * @param sourceWindowsManagedDevice the source object with updates
     * @return the updated WindowsManagedDevice
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public WindowsManagedDevice patch(@Nonnull final WindowsManagedDevice sourceWindowsManagedDevice) throws ClientException {
        return send(HttpMethod.PATCH, sourceWindowsManagedDevice);
    }

    /**
     * Creates a WindowsManagedDevice with a new object
     *
     * @param newWindowsManagedDevice the new object to create
     * @return a future with the result
     */
    @Nonnull
    public java.util.concurrent.CompletableFuture<WindowsManagedDevice> postAsync(@Nonnull final WindowsManagedDevice newWindowsManagedDevice) {
        return sendAsync(HttpMethod.POST, newWindowsManagedDevice);
    }

    /**
     * Creates a WindowsManagedDevice with a new object
     *
     * @param newWindowsManagedDevice the new object to create
     * @return the created WindowsManagedDevice
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public WindowsManagedDevice post(@Nonnull final WindowsManagedDevice newWindowsManagedDevice) throws ClientException {
        return send(HttpMethod.POST, newWindowsManagedDevice);
    }

    /**
     * Creates a WindowsManagedDevice with a new object
     *
     * @param newWindowsManagedDevice the object to create/update
     * @return a future with the result
     */
    @Nonnull
    public java.util.concurrent.CompletableFuture<WindowsManagedDevice> putAsync(@Nonnull final WindowsManagedDevice newWindowsManagedDevice) {
        return sendAsync(HttpMethod.PUT, newWindowsManagedDevice);
    }

    /**
     * Creates a WindowsManagedDevice with a new object
     *
     * @param newWindowsManagedDevice the object to create/update
     * @return the created WindowsManagedDevice
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public WindowsManagedDevice put(@Nonnull final WindowsManagedDevice newWindowsManagedDevice) throws ClientException {
        return send(HttpMethod.PUT, newWindowsManagedDevice);
    }

    /**
     * Sets the select clause for the request
     *
     * @param value the select clause
     * @return the updated request
     */
     @Nonnull
     public WindowsManagedDeviceRequest select(@Nonnull final String value) {
         addSelectOption(value);
         return this;
     }

    /**
     * Sets the expand clause for the request
     *
     * @param value the expand clause
     * @return the updated request
     */
     @Nonnull
     public WindowsManagedDeviceRequest expand(@Nonnull final String value) {
         addExpandOption(value);
         return this;
     }

}

