// Template Source: BaseEntityRequest.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.industrydata.requests;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.industrydata.models.FileDataConnector;
import java.util.Arrays;
import java.util.EnumSet;
import javax.annotation.Nullable;
import javax.annotation.Nonnull;
import com.microsoft.graph.core.IBaseClient;
import com.microsoft.graph.http.BaseRequest;
import com.microsoft.graph.http.HttpMethod;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the File Data Connector Request.
 */
public class FileDataConnectorRequest extends BaseRequest<FileDataConnector> {
	
    /**
     * The request for the FileDataConnector
     *
     * @param requestUrl     the request URL
     * @param client         the service client
     * @param requestOptions the options for this request
     * @param responseClass  the class of the response
     */
    public FileDataConnectorRequest(@Nonnull final String requestUrl,
            @Nonnull final IBaseClient<?> client,
            @Nullable final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions,
            @Nonnull final Class<? extends FileDataConnector> responseClass) {
        super(requestUrl, client, requestOptions, responseClass);
    }

    /**
     * The request for the FileDataConnector
     *
     * @param requestUrl     the request URL
     * @param client         the service client
     * @param requestOptions the options for this request
     */
    public FileDataConnectorRequest(@Nonnull final String requestUrl, @Nonnull final IBaseClient<?> client, @Nullable final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        super(requestUrl, client, requestOptions, FileDataConnector.class);
    }

    /**
     * Gets the FileDataConnector from the service
     *
     * @return a future with the result
     */
    @Nonnull
    public java.util.concurrent.CompletableFuture<FileDataConnector> getAsync() {
        return sendAsync(HttpMethod.GET, null);
    }

    /**
     * Gets the FileDataConnector from the service
     *
     * @return the FileDataConnector from the request
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public FileDataConnector get() throws ClientException {
       return send(HttpMethod.GET, null);
    }

    /**
     * Delete this item from the service
     *
     * @return a future with the deletion result
     */
    @Nonnull
    public java.util.concurrent.CompletableFuture<FileDataConnector> deleteAsync() {
        return sendAsync(HttpMethod.DELETE, null);
    }

    /**
     * Delete this item from the service
     * @return the resulting response if the service returns anything on deletion
     *
     * @throws ClientException if there was an exception during the delete operation
     */
    @Nullable
    public FileDataConnector delete() throws ClientException {
        return send(HttpMethod.DELETE, null);
    }

    /**
     * Patches this FileDataConnector with a source
     *
     * @param sourceFileDataConnector the source object with updates
     * @return a future with the result
     */
    @Nonnull
    public java.util.concurrent.CompletableFuture<FileDataConnector> patchAsync(@Nonnull final FileDataConnector sourceFileDataConnector) {
        return sendAsync(HttpMethod.PATCH, sourceFileDataConnector);
    }

    /**
     * Patches this FileDataConnector with a source
     *
     * @param sourceFileDataConnector the source object with updates
     * @return the updated FileDataConnector
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public FileDataConnector patch(@Nonnull final FileDataConnector sourceFileDataConnector) throws ClientException {
        return send(HttpMethod.PATCH, sourceFileDataConnector);
    }

    /**
     * Creates a FileDataConnector with a new object
     *
     * @param newFileDataConnector the new object to create
     * @return a future with the result
     */
    @Nonnull
    public java.util.concurrent.CompletableFuture<FileDataConnector> postAsync(@Nonnull final FileDataConnector newFileDataConnector) {
        return sendAsync(HttpMethod.POST, newFileDataConnector);
    }

    /**
     * Creates a FileDataConnector with a new object
     *
     * @param newFileDataConnector the new object to create
     * @return the created FileDataConnector
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public FileDataConnector post(@Nonnull final FileDataConnector newFileDataConnector) throws ClientException {
        return send(HttpMethod.POST, newFileDataConnector);
    }

    /**
     * Creates a FileDataConnector with a new object
     *
     * @param newFileDataConnector the object to create/update
     * @return a future with the result
     */
    @Nonnull
    public java.util.concurrent.CompletableFuture<FileDataConnector> putAsync(@Nonnull final FileDataConnector newFileDataConnector) {
        return sendAsync(HttpMethod.PUT, newFileDataConnector);
    }

    /**
     * Creates a FileDataConnector with a new object
     *
     * @param newFileDataConnector the object to create/update
     * @return the created FileDataConnector
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public FileDataConnector put(@Nonnull final FileDataConnector newFileDataConnector) throws ClientException {
        return send(HttpMethod.PUT, newFileDataConnector);
    }

    /**
     * Sets the select clause for the request
     *
     * @param value the select clause
     * @return the updated request
     */
     @Nonnull
     public FileDataConnectorRequest select(@Nonnull final String value) {
         addSelectOption(value);
         return this;
     }

    /**
     * Sets the expand clause for the request
     *
     * @param value the expand clause
     * @return the updated request
     */
     @Nonnull
     public FileDataConnectorRequest expand(@Nonnull final String value) {
         addExpandOption(value);
         return this;
     }

}

