// Template Source: BaseEntityRequest.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.industrydata.requests;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.industrydata.models.InboundFileFlow;
import java.util.Arrays;
import java.util.EnumSet;
import javax.annotation.Nullable;
import javax.annotation.Nonnull;
import com.microsoft.graph.core.IBaseClient;
import com.microsoft.graph.http.BaseRequest;
import com.microsoft.graph.http.HttpMethod;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Inbound File Flow Request.
 */
public class InboundFileFlowRequest extends BaseRequest<InboundFileFlow> {
	
    /**
     * The request for the InboundFileFlow
     *
     * @param requestUrl     the request URL
     * @param client         the service client
     * @param requestOptions the options for this request
     */
    public InboundFileFlowRequest(@Nonnull final String requestUrl, @Nonnull final IBaseClient<?> client, @Nullable final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        super(requestUrl, client, requestOptions, InboundFileFlow.class);
    }

    /**
     * Gets the InboundFileFlow from the service
     *
     * @return a future with the result
     */
    @Nonnull
    public java.util.concurrent.CompletableFuture<InboundFileFlow> getAsync() {
        return sendAsync(HttpMethod.GET, null);
    }

    /**
     * Gets the InboundFileFlow from the service
     *
     * @return the InboundFileFlow from the request
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public InboundFileFlow get() throws ClientException {
       return send(HttpMethod.GET, null);
    }

    /**
     * Delete this item from the service
     *
     * @return a future with the deletion result
     */
    @Nonnull
    public java.util.concurrent.CompletableFuture<InboundFileFlow> deleteAsync() {
        return sendAsync(HttpMethod.DELETE, null);
    }

    /**
     * Delete this item from the service
     * @return the resulting response if the service returns anything on deletion
     *
     * @throws ClientException if there was an exception during the delete operation
     */
    @Nullable
    public InboundFileFlow delete() throws ClientException {
        return send(HttpMethod.DELETE, null);
    }

    /**
     * Patches this InboundFileFlow with a source
     *
     * @param sourceInboundFileFlow the source object with updates
     * @return a future with the result
     */
    @Nonnull
    public java.util.concurrent.CompletableFuture<InboundFileFlow> patchAsync(@Nonnull final InboundFileFlow sourceInboundFileFlow) {
        return sendAsync(HttpMethod.PATCH, sourceInboundFileFlow);
    }

    /**
     * Patches this InboundFileFlow with a source
     *
     * @param sourceInboundFileFlow the source object with updates
     * @return the updated InboundFileFlow
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public InboundFileFlow patch(@Nonnull final InboundFileFlow sourceInboundFileFlow) throws ClientException {
        return send(HttpMethod.PATCH, sourceInboundFileFlow);
    }

    /**
     * Creates a InboundFileFlow with a new object
     *
     * @param newInboundFileFlow the new object to create
     * @return a future with the result
     */
    @Nonnull
    public java.util.concurrent.CompletableFuture<InboundFileFlow> postAsync(@Nonnull final InboundFileFlow newInboundFileFlow) {
        return sendAsync(HttpMethod.POST, newInboundFileFlow);
    }

    /**
     * Creates a InboundFileFlow with a new object
     *
     * @param newInboundFileFlow the new object to create
     * @return the created InboundFileFlow
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public InboundFileFlow post(@Nonnull final InboundFileFlow newInboundFileFlow) throws ClientException {
        return send(HttpMethod.POST, newInboundFileFlow);
    }

    /**
     * Creates a InboundFileFlow with a new object
     *
     * @param newInboundFileFlow the object to create/update
     * @return a future with the result
     */
    @Nonnull
    public java.util.concurrent.CompletableFuture<InboundFileFlow> putAsync(@Nonnull final InboundFileFlow newInboundFileFlow) {
        return sendAsync(HttpMethod.PUT, newInboundFileFlow);
    }

    /**
     * Creates a InboundFileFlow with a new object
     *
     * @param newInboundFileFlow the object to create/update
     * @return the created InboundFileFlow
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public InboundFileFlow put(@Nonnull final InboundFileFlow newInboundFileFlow) throws ClientException {
        return send(HttpMethod.PUT, newInboundFileFlow);
    }

    /**
     * Sets the select clause for the request
     *
     * @param value the select clause
     * @return the updated request
     */
     @Nonnull
     public InboundFileFlowRequest select(@Nonnull final String value) {
         addSelectOption(value);
         return this;
     }

    /**
     * Sets the expand clause for the request
     *
     * @param value the expand clause
     * @return the updated request
     */
     @Nonnull
     public InboundFileFlowRequest expand(@Nonnull final String value) {
         addExpandOption(value);
         return this;
     }

}

