on:
  push:
    branches:
      - dev

permissions:
  contents: write
  pull-requests: write

name: release-bot

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          config-file: release-please-config.json # Set to update gradle.properties, pom.xml & CHANGELOG.md
          manifest-file: .release-please-manifest.json
          target-branch: dev
